<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>2.86102e-06</Pose0>
        <Pose1>9.53674e-07</Pose1>
        <Pose2>-1.57812e-06</Pose2>
        <Pose3>2.86102e-06</Pose3>
        <Pose4>9.05991e-06</Pose4>
        <Pose5>-6.48339e-07</Pose5>
        <Pose6>-1.68589e-06</Pose6>
        <Pose7>-3.74826e-06</Pose7>
        <Pose8>-6.10947e-07</Pose8>
        <Pose9>1.43051e-06</Pose9>
        <Pose10>-1.07011e-05</Pose10>
        <Pose11>1.14441e-05</Pose11>
        <Pose12>-3.79318e-06</Pose12>
        <Pose13>-5.87837e-06</Pose13>
        <Pose14>-5.89371e-06</Pose14>
        <Pose15>6.19888e-06</Pose15>
        <Pose16>1.43051e-06</Pose16>
        <Pose17>-5.14757e-06</Pose17>
        <Pose18>1.19209e-05</Pose18>
        <Pose19>-1.20635e-06</Pose19>
        <Pose20>1.90735e-06</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0.7839</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
    </newAction0>
    <newAction1>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>4.29153e-06</Pose0>
        <Pose1>9.53674e-07</Pose1>
        <Pose2>9.53674e-07</Pose2>
        <Pose3>-4.56717e-06</Pose3>
        <Pose4>-1.02067e-05</Pose4>
        <Pose5>-8.92204e-06</Pose5>
        <Pose6>9.53674e-06</Pose6>
        <Pose7>-1.00492e-06</Pose7>
        <Pose8>-1.28323e-06</Pose8>
        <Pose9>2.38419e-06</Pose9>
        <Pose10>-5.7276e-06</Pose10>
        <Pose11>7.15256e-06</Pose11>
        <Pose12>-7.62946e-07</Pose12>
        <Pose13>-7.60685e-06</Pose13>
        <Pose14>-5.67421e-06</Pose14>
        <Pose15>1.90735e-06</Pose15>
        <Pose16>2.38419e-06</Pose16>
        <Pose17>1.90735e-06</Pose17>
        <Pose18>4.29153e-06</Pose18>
        <Pose19>2.86102e-06</Pose19>
        <Pose20>-2.18923e-06</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0.7839</HandPose2>
        <HandPose3>0.924</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
    </newAction1>
    <newAction2>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>2.38419e-06</Pose0>
        <Pose1>-4.18874e-07</Pose1>
        <Pose2>-1.31164e-06</Pose2>
        <Pose3>1.90735e-06</Pose3>
        <Pose4>4.29153e-06</Pose4>
        <Pose5>-2.1791e-06</Pose5>
        <Pose6>7.15256e-06</Pose6>
        <Pose7>-3.70212e-06</Pose7>
        <Pose8>-3.08407e-06</Pose8>
        <Pose9>1.43051e-06</Pose9>
        <Pose10>-7.18372e-06</Pose10>
        <Pose11>1.04904e-05</Pose11>
        <Pose12>-6.28931e-07</Pose12>
        <Pose13>-7.91511e-06</Pose13>
        <Pose14>-2.61871e-06</Pose14>
        <Pose15>4.29153e-06</Pose15>
        <Pose16>-4.10912e-07</Pose16>
        <Pose17>4.29153e-06</Pose17>
        <Pose18>-6.87359e-06</Pose18>
        <Pose19>4.76837e-07</Pose19>
        <Pose20>-1.60777e-06</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0.7839</HandPose2>
        <HandPose3>0.924</HandPose3>
        <HandPose4>1.189</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
    </newAction2>
    <newAction3>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>1.90735e-06</Pose0>
        <Pose1>-6.51143e-07</Pose1>
        <Pose2>-1.82477e-06</Pose2>
        <Pose3>9.53674e-07</Pose3>
        <Pose4>4.29153e-06</Pose4>
        <Pose5>9.53674e-07</Pose5>
        <Pose6>-4.10817e-06</Pose6>
        <Pose7>-5.46285e-06</Pose7>
        <Pose8>-3.56537e-06</Pose8>
        <Pose9>1.90735e-06</Pose9>
        <Pose10>-3.47697e-06</Pose10>
        <Pose11>8.58307e-06</Pose11>
        <Pose12>-4.12697e-06</Pose12>
        <Pose13>-8.51664e-06</Pose13>
        <Pose14>-2.08095e-06</Pose14>
        <Pose15>2.38419e-06</Pose15>
        <Pose16>9.53674e-07</Pose16>
        <Pose17>3.33786e-06</Pose17>
        <Pose18>6.19888e-06</Pose18>
        <Pose19>1.43051e-06</Pose19>
        <Pose20>-1.19058e-06</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0.7839</HandPose2>
        <HandPose3>0.924</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
    </newAction3>
    <newAction4>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>4.29153e-06</Pose0>
        <Pose1>9.53674e-07</Pose1>
        <Pose2>-1.76439e-06</Pose2>
        <Pose3>-4.48706e-06</Pose3>
        <Pose4>7.15256e-06</Pose4>
        <Pose5>-6.73591e-07</Pose5>
        <Pose6>-4.47175e-06</Pose6>
        <Pose7>-5.74196e-06</Pose7>
        <Pose8>9.53674e-07</Pose8>
        <Pose9>2.38419e-06</Pose9>
        <Pose10>-9.09939e-06</Pose10>
        <Pose11>9.53674e-06</Pose11>
        <Pose12>-1.14413e-06</Pose12>
        <Pose13>-7.46025e-06</Pose13>
        <Pose14>-5.00409e-06</Pose14>
        <Pose15>2.38419e-06</Pose15>
        <Pose16>4.76837e-07</Pose16>
        <Pose17>2.86102e-06</Pose17>
        <Pose18>1.90735e-06</Pose18>
        <Pose19>4.76837e-07</Pose19>
        <Pose20>2.86102e-06</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0.7839</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
    </newAction4>
    <newAction5>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>3.8147e-06</Pose0>
        <Pose1>-6.82316e-07</Pose1>
        <Pose2>-1.83617e-06</Pose2>
        <Pose3>1.43051e-06</Pose3>
        <Pose4>-5.83276e-06</Pose4>
        <Pose5>-1.04115e-05</Pose5>
        <Pose6>4.76837e-07</Pose6>
        <Pose7>-4.20329e-06</Pose7>
        <Pose8>-1.2694e-06</Pose8>
        <Pose9>1.90735e-06</Pose9>
        <Pose10>-3.93932e-06</Pose10>
        <Pose11>1.09673e-05</Pose11>
        <Pose12>-7.49651e-07</Pose12>
        <Pose13>-7.5037e-06</Pose13>
        <Pose14>1.43051e-06</Pose14>
        <Pose15>4.29153e-06</Pose15>
        <Pose16>2.86102e-06</Pose16>
        <Pose17>-8.91394e-06</Pose17>
        <Pose18>-2.26807e-06</Pose18>
        <Pose19>5.24521e-06</Pose19>
        <Pose20>2.38419e-06</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
    </newAction5>
</Actions>
