<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.062728</Pose0>
        <Pose1>-0.062728</Pose1>
        <Pose2>-0.062728</Pose2>
        <Pose3>-0.062728</Pose3>
        <Pose4>-0.062728</Pose4>
        <Pose5>-0.062728</Pose5>
        <Pose6>-0.062728</Pose6>
        <Pose7>-4.96029e-06</Pose7>
        <Pose8>-0.00187926</Pose8>
        <Pose9>-0.35796</Pose9>
        <Pose10>-0.000199416</Pose10>
        <Pose11>-0.062728</Pose11>
        <Pose12>-0.062728</Pose12>
        <Pose13>-0.062728</Pose13>
        <Pose14>-3.00241e-06</Pose14>
        <Pose15>-0.000188253</Pose15>
        <Pose16>3.40512e-23</Pose16>
        <Pose17>-0.000199439</Pose17>
        <Pose18>-0.062728</Pose18>
        <Pose19>-0.062728</Pose19>
        <Pose20>-0.062728</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-0.0924698</Pose0>
        <Pose1>-0.0924698</Pose1>
        <Pose2>-0.0924698</Pose2>
        <Pose3>-0.0924698</Pose3>
        <Pose4>-0.0924698</Pose4>
        <Pose5>-0.0924698</Pose5>
        <Pose6>-0.0924698</Pose6>
        <Pose7>-4.96029e-06</Pose7>
        <Pose8>-0.00187926</Pose8>
        <Pose9>-0.3768</Pose9>
        <Pose10>-0.000199416</Pose10>
        <Pose11>-0.0924698</Pose11>
        <Pose12>-0.0924698</Pose12>
        <Pose13>-0.0924698</Pose13>
        <Pose14>-3.01943e-06</Pose14>
        <Pose15>-0.0187987</Pose15>
        <Pose16>4.55457e-23</Pose16>
        <Pose17>-0.000199431</Pose17>
        <Pose18>-0.0924698</Pose18>
        <Pose19>-0.0924698</Pose19>
        <Pose20>-0.0924698</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>-0.130347</Pose0>
        <Pose1>-0.130347</Pose1>
        <Pose2>-0.130347</Pose2>
        <Pose3>-0.130347</Pose3>
        <Pose4>-0.130347</Pose4>
        <Pose5>-0.130347</Pose5>
        <Pose6>-0.130347</Pose6>
        <Pose7>-4.96029e-06</Pose7>
        <Pose8>-0.00187926</Pose8>
        <Pose9>0.3768</Pose9>
        <Pose10>-0.000199416</Pose10>
        <Pose11>-0.130347</Pose11>
        <Pose12>-0.130347</Pose12>
        <Pose13>-0.130347</Pose13>
        <Pose14>-3.03169e-06</Pose14>
        <Pose15>-0.0187987</Pose15>
        <Pose16>4.53615e-23</Pose16>
        <Pose17>-0.000199426</Pose17>
        <Pose18>-0.130347</Pose18>
        <Pose19>-0.130347</Pose19>
        <Pose20>-0.130347</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction2>
    <newAction3>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-0.17553</Pose0>
        <Pose1>-0.17553</Pose1>
        <Pose2>-0.17553</Pose2>
        <Pose3>-0.17553</Pose3>
        <Pose4>-0.17553</Pose4>
        <Pose5>-0.17553</Pose5>
        <Pose6>-0.17553</Pose6>
        <Pose7>-4.96029e-06</Pose7>
        <Pose8>-0.00187926</Pose8>
        <Pose9>0.3768</Pose9>
        <Pose10>-0.000199416</Pose10>
        <Pose11>-0.17553</Pose11>
        <Pose12>-0.17553</Pose12>
        <Pose13>-0.17553</Pose13>
        <Pose14>-3.10812e-06</Pose14>
        <Pose15>-0.0187984</Pose15>
        <Pose16>4.33327e-23</Pose16>
        <Pose17>-0.000199392</Pose17>
        <Pose18>-0.17553</Pose18>
        <Pose19>-0.17553</Pose19>
        <Pose20>-0.17553</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction3>
    <newAction4>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.222202</Pose0>
        <Pose1>-0.222202</Pose1>
        <Pose2>-0.222202</Pose2>
        <Pose3>-0.222202</Pose3>
        <Pose4>-0.222202</Pose4>
        <Pose5>-0.222202</Pose5>
        <Pose6>-0.222202</Pose6>
        <Pose7>-4.96029e-06</Pose7>
        <Pose8>-0.00187926</Pose8>
        <Pose9>-2.92771e-13</Pose9>
        <Pose10>-0.000199416</Pose10>
        <Pose11>-0.222202</Pose11>
        <Pose12>-0.222202</Pose12>
        <Pose13>-0.222202</Pose13>
        <Pose14>-3.1171e-06</Pose14>
        <Pose15>-0.0187984</Pose15>
        <Pose16>0.3768</Pose16>
        <Pose17>-0.000199388</Pose17>
        <Pose18>-0.222202</Pose18>
        <Pose19>-0.222202</Pose19>
        <Pose20>-0.222202</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction4>
    <newAction5>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-0.29561</Pose0>
        <Pose1>-0.29561</Pose1>
        <Pose2>-0.29561</Pose2>
        <Pose3>-0.29561</Pose3>
        <Pose4>-0.29561</Pose4>
        <Pose5>-0.29561</Pose5>
        <Pose6>-0.29561</Pose6>
        <Pose7>-4.96029e-06</Pose7>
        <Pose8>-0.00187926</Pose8>
        <Pose9>-1.03775e-14</Pose9>
        <Pose10>-0.000199416</Pose10>
        <Pose11>-0.29561</Pose11>
        <Pose12>-0.29561</Pose12>
        <Pose13>-0.29561</Pose13>
        <Pose14>-2.96493e-06</Pose14>
        <Pose15>-0.0187989</Pose15>
        <Pose16>0.3768</Pose16>
        <Pose17>-0.000199455</Pose17>
        <Pose18>-0.29561</Pose18>
        <Pose19>-0.29561</Pose19>
        <Pose20>-0.29561</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction5>
    <newAction6>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>-0.366572</Pose0>
        <Pose1>-0.366572</Pose1>
        <Pose2>-0.366572</Pose2>
        <Pose3>-0.366572</Pose3>
        <Pose4>-0.366572</Pose4>
        <Pose5>-0.366572</Pose5>
        <Pose6>-0.366572</Pose6>
        <Pose7>-4.96029e-06</Pose7>
        <Pose8>-0.00187926</Pose8>
        <Pose9>-6.30817e-16</Pose9>
        <Pose10>-0.000199416</Pose10>
        <Pose11>-0.366572</Pose11>
        <Pose12>-0.366572</Pose12>
        <Pose13>-0.366572</Pose13>
        <Pose14>-3.05955e-06</Pose14>
        <Pose15>-0.0187986</Pose15>
        <Pose16>-0.3768</Pose16>
        <Pose17>-0.000199412</Pose17>
        <Pose18>-0.366572</Pose18>
        <Pose19>-0.366572</Pose19>
        <Pose20>-0.366572</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction6>
    <newAction7>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-0.486132</Pose0>
        <Pose1>-0.486132</Pose1>
        <Pose2>-0.486132</Pose2>
        <Pose3>-0.486132</Pose3>
        <Pose4>-0.486132</Pose4>
        <Pose5>-0.486132</Pose5>
        <Pose6>-0.486132</Pose6>
        <Pose7>-4.96029e-06</Pose7>
        <Pose8>-0.00187926</Pose8>
        <Pose9>-1.17754e-17</Pose9>
        <Pose10>-0.000199416</Pose10>
        <Pose11>-0.486132</Pose11>
        <Pose12>-0.486132</Pose12>
        <Pose13>-0.486132</Pose13>
        <Pose14>-2.9892e-06</Pose14>
        <Pose15>-0.0187988</Pose15>
        <Pose16>-0.3768</Pose16>
        <Pose17>-0.000199444</Pose17>
        <Pose18>-0.486132</Pose18>
        <Pose19>-0.486132</Pose19>
        <Pose20>-0.486132</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction7>
    <newAction8>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.592925</Pose0>
        <Pose1>-0.592925</Pose1>
        <Pose2>-0.592925</Pose2>
        <Pose3>-0.592925</Pose3>
        <Pose4>-0.592925</Pose4>
        <Pose5>-0.592925</Pose5>
        <Pose6>-0.592925</Pose6>
        <Pose7>-4.96029e-06</Pose7>
        <Pose8>-0.00187926</Pose8>
        <Pose9>-6.02485e-19</Pose9>
        <Pose10>-0.000199416</Pose10>
        <Pose11>-0.592925</Pose11>
        <Pose12>-0.592925</Pose12>
        <Pose13>-0.592925</Pose13>
        <Pose14>-3.00413e-06</Pose14>
        <Pose15>-0.0187988</Pose15>
        <Pose16>7.56905e-13</Pose16>
        <Pose17>-0.000199437</Pose17>
        <Pose18>-0.592925</Pose18>
        <Pose19>-0.592925</Pose19>
        <Pose20>-0.592925</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction8>
    <newAction9>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>-0.747331</Pose0>
        <Pose1>-0.747331</Pose1>
        <Pose2>-0.747331</Pose2>
        <Pose3>-0.747331</Pose3>
        <Pose4>-0.747331</Pose4>
        <Pose5>-0.747331</Pose5>
        <Pose6>-0.747331</Pose6>
        <Pose7>0.18529</Pose7>
        <Pose8>-0.0018793</Pose8>
        <Pose9>-1.51881e-20</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>-0.747331</Pose11>
        <Pose12>-0.747331</Pose12>
        <Pose13>-0.747331</Pose13>
        <Pose14>0.143712</Pose14>
        <Pose15>-0.0187989</Pose15>
        <Pose16>1.48516e-14</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>-0.747331</Pose18>
        <Pose19>-0.747331</Pose19>
        <Pose20>-0.747331</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction9>
    <newAction10>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.163786</Pose0>
        <Pose1>-0.163786</Pose1>
        <Pose2>-0.163786</Pose2>
        <Pose3>-0.163786</Pose3>
        <Pose4>-0.163786</Pose4>
        <Pose5>-0.163786</Pose5>
        <Pose6>-0.163786</Pose6>
        <Pose7>0.35476</Pose7>
        <Pose8>-0.00187898</Pose8>
        <Pose9>1.11261e-14</Pose9>
        <Pose10>-0.851877</Pose10>
        <Pose11>-0.163786</Pose11>
        <Pose12>-0.163786</Pose12>
        <Pose13>-0.163786</Pose13>
        <Pose14>0.302788</Pose14>
        <Pose15>-0.0187985</Pose15>
        <Pose16>2.13906e-14</Pose16>
        <Pose17>-0.851878</Pose17>
        <Pose18>-0.163786</Pose18>
        <Pose19>-0.163786</Pose19>
        <Pose20>-0.163786</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction10>
    <newAction11>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-1.21542</Pose0>
        <Pose1>-1.21542</Pose1>
        <Pose2>-1.21542</Pose2>
        <Pose3>-1.21542</Pose3>
        <Pose4>-1.21542</Pose4>
        <Pose5>-1.21542</Pose5>
        <Pose6>-1.21542</Pose6>
        <Pose7>0.227324</Pose7>
        <Pose8>-0.0018793</Pose8>
        <Pose9>-0.377428</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>-1.21542</Pose11>
        <Pose12>-1.21542</Pose12>
        <Pose13>-1.21542</Pose13>
        <Pose14>0.29241</Pose14>
        <Pose15>-0.018799</Pose15>
        <Pose16>-0.314628</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>-1.21542</Pose18>
        <Pose19>-1.21542</Pose19>
        <Pose20>-1.21542</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction11>
    <newAction12>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.303042</Pose0>
        <Pose1>-0.303042</Pose1>
        <Pose2>-0.303042</Pose2>
        <Pose3>-0.303042</Pose3>
        <Pose4>-0.303042</Pose4>
        <Pose5>-0.303042</Pose5>
        <Pose6>-0.303042</Pose6>
        <Pose7>0.258945</Pose7>
        <Pose8>-0.00187895</Pose8>
        <Pose9>-0.3768</Pose9>
        <Pose10>-0.851879</Pose10>
        <Pose11>-0.303042</Pose11>
        <Pose12>-0.303042</Pose12>
        <Pose13>-0.303042</Pose13>
        <Pose14>0.473177</Pose14>
        <Pose15>-0.0187984</Pose15>
        <Pose16>-0.314</Pose16>
        <Pose17>-0.851876</Pose17>
        <Pose18>-0.303042</Pose18>
        <Pose19>-0.303042</Pose19>
        <Pose20>-0.303042</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction12>
    <newAction13>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>-1.64124</Pose0>
        <Pose1>-1.64124</Pose1>
        <Pose2>-1.64124</Pose2>
        <Pose3>-1.64124</Pose3>
        <Pose4>-1.64124</Pose4>
        <Pose5>-1.64124</Pose5>
        <Pose6>-1.64124</Pose6>
        <Pose7>0.0266494</Pose7>
        <Pose8>-0.00187928</Pose8>
        <Pose9>0.376172</Pose9>
        <Pose10>-0.851888</Pose10>
        <Pose11>-1.64124</Pose11>
        <Pose12>-1.64124</Pose12>
        <Pose13>-1.64124</Pose13>
        <Pose14>0.0370466</Pose14>
        <Pose15>-0.0187989</Pose15>
        <Pose16>0.376172</Pose16>
        <Pose17>-0.851888</Pose17>
        <Pose18>-1.64124</Pose18>
        <Pose19>-1.64124</Pose19>
        <Pose20>-1.64124</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction13>
    <newAction14>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-1.84991</Pose0>
        <Pose1>-1.84991</Pose1>
        <Pose2>-1.84991</Pose2>
        <Pose3>-1.84991</Pose3>
        <Pose4>-1.84991</Pose4>
        <Pose5>-1.84991</Pose5>
        <Pose6>-1.84991</Pose6>
        <Pose7>0.10032</Pose7>
        <Pose8>-0.00187928</Pose8>
        <Pose9>0.376172</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>-1.84991</Pose11>
        <Pose12>-1.84991</Pose12>
        <Pose13>-1.84991</Pose13>
        <Pose14>0.0478938</Pose14>
        <Pose15>-0.0187987</Pose15>
        <Pose16>0.376172</Pose16>
        <Pose17>-0.851888</Pose17>
        <Pose18>-1.84991</Pose18>
        <Pose19>-1.84991</Pose19>
        <Pose20>-1.84991</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction14>
    <newAction15>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-2.0645</Pose0>
        <Pose1>-2.0645</Pose1>
        <Pose2>-2.0645</Pose2>
        <Pose3>-2.0645</Pose3>
        <Pose4>-2.0645</Pose4>
        <Pose5>-2.0645</Pose5>
        <Pose6>-2.0645</Pose6>
        <Pose7>0.164048</Pose7>
        <Pose8>-0.0018793</Pose8>
        <Pose9>-1.82889e-13</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>-2.0645</Pose11>
        <Pose12>-2.0645</Pose12>
        <Pose13>-2.0645</Pose13>
        <Pose14>0.196592</Pose14>
        <Pose15>-0.0187986</Pose15>
        <Pose16>-0.000628</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>-2.0645</Pose18>
        <Pose19>-2.0645</Pose19>
        <Pose20>-2.0645</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction15>
    <newAction16>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-2.32062</Pose0>
        <Pose1>-2.32062</Pose1>
        <Pose2>-2.32062</Pose2>
        <Pose3>-2.32062</Pose3>
        <Pose4>-2.32062</Pose4>
        <Pose5>-2.32062</Pose5>
        <Pose6>-2.32062</Pose6>
        <Pose7>0.18529</Pose7>
        <Pose8>-0.0018793</Pose8>
        <Pose9>-6.29084e-15</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>-2.32062</Pose11>
        <Pose12>-2.32062</Pose12>
        <Pose13>-2.32062</Pose13>
        <Pose14>0.090379</Pose14>
        <Pose15>-0.0187989</Pose15>
        <Pose16>-0.000628</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>-2.32062</Pose18>
        <Pose19>-2.32062</Pose19>
        <Pose20>-2.32062</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction16>
    <newAction17>
        <Time>6</Time>
        <Count>21</Count>
        <Pose0>-2.58295</Pose0>
        <Pose1>-2.58295</Pose1>
        <Pose2>-2.58295</Pose2>
        <Pose3>-2.58295</Pose3>
        <Pose4>-2.58295</Pose4>
        <Pose5>-2.58295</Pose5>
        <Pose6>-2.58295</Pose6>
        <Pose7>-1.67186e-05</Pose7>
        <Pose8>-0.00187928</Pose8>
        <Pose9>-2.1951e-16</Pose9>
        <Pose10>-0.851888</Pose10>
        <Pose11>-2.58295</Pose11>
        <Pose12>-2.58295</Pose12>
        <Pose13>-2.58295</Pose13>
        <Pose14>-1.48656e-05</Pose14>
        <Pose15>-0.0187986</Pose15>
        <Pose16>-6.46476e-16</Pose16>
        <Pose17>-0.851888</Pose17>
        <Pose18>-2.58295</Pose18>
        <Pose19>-2.58295</Pose19>
        <Pose20>-2.58295</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction17>
    <newAction18>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>-2.80293</Pose0>
        <Pose1>-2.80293</Pose1>
        <Pose2>-2.80293</Pose2>
        <Pose3>-2.80293</Pose3>
        <Pose4>-2.80293</Pose4>
        <Pose5>-2.80293</Pose5>
        <Pose6>-2.80293</Pose6>
        <Pose7>0.406306</Pose7>
        <Pose8>0.142665</Pose8>
        <Pose9>-1.40729e-17</Pose9>
        <Pose10>-0.851884</Pose10>
        <Pose11>-2.80293</Pose11>
        <Pose12>-2.80293</Pose12>
        <Pose13>-2.80293</Pose13>
        <Pose14>0.50529</Pose14>
        <Pose15>-0.142872</Pose15>
        <Pose16>-4.42556e-17</Pose16>
        <Pose17>-0.851884</Pose17>
        <Pose18>-2.80293</Pose18>
        <Pose19>-2.80293</Pose19>
        <Pose20>-2.80293</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction18>
    <newAction19>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>2.5253</Pose0>
        <Pose1>2.5253</Pose1>
        <Pose2>2.5253</Pose2>
        <Pose3>2.5253</Pose3>
        <Pose4>2.5253</Pose4>
        <Pose5>2.5253</Pose5>
        <Pose6>2.5253</Pose6>
        <Pose7>0.406284</Pose7>
        <Pose8>0.14266</Pose8>
        <Pose9>-9.11775e-19</Pose9>
        <Pose10>-0.851877</Pose10>
        <Pose11>2.5253</Pose11>
        <Pose12>2.5253</Pose12>
        <Pose13>2.5253</Pose13>
        <Pose14>0.898481</Pose14>
        <Pose15>-0.142871</Pose15>
        <Pose16>-9.5747e-18</Pose16>
        <Pose17>-0.851876</Pose17>
        <Pose18>2.5253</Pose18>
        <Pose19>2.5253</Pose19>
        <Pose20>2.5253</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction19>
    <newAction20>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>2.25016</Pose0>
        <Pose1>2.25016</Pose1>
        <Pose2>2.25016</Pose2>
        <Pose3>2.25016</Pose3>
        <Pose4>2.25016</Pose4>
        <Pose5>2.25016</Pose5>
        <Pose6>2.25016</Pose6>
        <Pose7>0.0582872</Pose7>
        <Pose8>0.142663</Pose8>
        <Pose9>-5.07245e-21</Pose9>
        <Pose10>-0.851888</Pose10>
        <Pose11>2.25016</Pose11>
        <Pose12>2.25016</Pose12>
        <Pose13>2.25016</Pose13>
        <Pose14>0.406307</Pose14>
        <Pose15>-0.14287</Pose15>
        <Pose16>-1.36616e-18</Pose16>
        <Pose17>-0.851884</Pose17>
        <Pose18>2.25016</Pose18>
        <Pose19>2.25016</Pose19>
        <Pose20>2.25016</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction20>
    <newAction21>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.98467</Pose0>
        <Pose1>1.98467</Pose1>
        <Pose2>1.98467</Pose2>
        <Pose3>1.98467</Pose3>
        <Pose4>1.98467</Pose4>
        <Pose5>1.98467</Pose5>
        <Pose6>1.98467</Pose6>
        <Pose7>0.11118</Pose7>
        <Pose8>0.142668</Pose8>
        <Pose9>1.04295e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>1.98467</Pose11>
        <Pose12>1.98467</Pose12>
        <Pose13>1.98467</Pose13>
        <Pose14>0.406328</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.03684e-23</Pose16>
        <Pose17>-0.851892</Pose17>
        <Pose18>1.98467</Pose18>
        <Pose19>1.98467</Pose19>
        <Pose20>1.98467</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction21>
    <newAction22>
        <Time>6</Time>
        <Count>21</Count>
        <Pose0>1.76027</Pose0>
        <Pose1>1.76027</Pose1>
        <Pose2>1.76027</Pose2>
        <Pose3>1.76027</Pose3>
        <Pose4>1.76027</Pose4>
        <Pose5>1.76027</Pose5>
        <Pose6>1.76027</Pose6>
        <Pose7>0.316362</Pose7>
        <Pose8>0.101514</Pose8>
        <Pose9>7.54404e-24</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>1.76027</Pose11>
        <Pose12>1.76027</Pose12>
        <Pose13>1.76027</Pose13>
        <Pose14>0.316364</Pose14>
        <Pose15>-0.14287</Pose15>
        <Pose16>-2.2073e-19</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>1.76027</Pose18>
        <Pose19>1.76027</Pose19>
        <Pose20>1.76027</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction22>
    <newAction23>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>1.59498</Pose0>
        <Pose1>1.59498</Pose1>
        <Pose2>1.59498</Pose2>
        <Pose3>1.59498</Pose3>
        <Pose4>1.59498</Pose4>
        <Pose5>1.59498</Pose5>
        <Pose6>1.59498</Pose6>
        <Pose7>0.316362</Pose7>
        <Pose8>0.101514</Pose8>
        <Pose9>3.31168e-23</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>1.59498</Pose11>
        <Pose12>1.59498</Pose12>
        <Pose13>1.59498</Pose13>
        <Pose14>0.316364</Pose14>
        <Pose15>-0.14287</Pose15>
        <Pose16>-8.95286e-20</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>1.59498</Pose18>
        <Pose19>1.59498</Pose19>
        <Pose20>1.59498</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction23>
    <newAction24>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-2.66608</Pose0>
        <Pose1>-2.66608</Pose1>
        <Pose2>-2.66608</Pose2>
        <Pose3>-2.66608</Pose3>
        <Pose4>-2.66608</Pose4>
        <Pose5>-2.66608</Pose5>
        <Pose6>-2.66608</Pose6>
        <Pose7>0.316382</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.58942e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>-2.66608</Pose11>
        <Pose12>-2.66608</Pose12>
        <Pose13>-2.66608</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.32153e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>-2.66608</Pose18>
        <Pose19>-2.66608</Pose19>
        <Pose20>-2.66608</Pose20>
        <Count>10</Count>
        <HandPose0>0.084</HandPose0>
        <HandPose1>0.083</HandPose1>
        <HandPose2>0.081</HandPose2>
        <HandPose3>0.085</HandPose3>
        <HandPose4>0.084</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction24>
    <newAction25>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>2.35281</Pose0>
        <Pose1>2.35281</Pose1>
        <Pose2>2.35281</Pose2>
        <Pose3>2.35281</Pose3>
        <Pose4>2.35281</Pose4>
        <Pose5>2.35281</Pose5>
        <Pose6>2.35281</Pose6>
        <Pose7>0.316382</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.58684e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>2.35281</Pose11>
        <Pose12>2.35281</Pose12>
        <Pose13>2.35281</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.27562e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>2.35281</Pose18>
        <Pose19>2.35281</Pose19>
        <Pose20>2.35281</Pose20>
        <Count>10</Count>
        <HandPose0>0.084</HandPose0>
        <HandPose1>0.083</HandPose1>
        <HandPose2>0.081</HandPose2>
        <HandPose3>0.085</HandPose3>
        <HandPose4>0.084</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction25>
    <newAction26>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>1.09906</Pose0>
        <Pose1>1.09906</Pose1>
        <Pose2>1.09906</Pose2>
        <Pose3>1.09906</Pose3>
        <Pose4>1.09906</Pose4>
        <Pose5>1.09906</Pose5>
        <Pose6>1.09906</Pose6>
        <Pose7>0.316362</Pose7>
        <Pose8>0.101514</Pose8>
        <Pose9>2.90864e-23</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>1.09906</Pose11>
        <Pose12>1.09906</Pose12>
        <Pose13>1.09906</Pose13>
        <Pose14>0.316364</Pose14>
        <Pose15>-0.14287</Pose15>
        <Pose16>-1.27511e-21</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>1.09906</Pose18>
        <Pose19>1.09906</Pose19>
        <Pose20>1.09906</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction26>
    <newAction27>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>1.02495</Pose0>
        <Pose1>1.02495</Pose1>
        <Pose2>1.02495</Pose2>
        <Pose3>1.02495</Pose3>
        <Pose4>1.02495</Pose4>
        <Pose5>1.02495</Pose5>
        <Pose6>1.02495</Pose6>
        <Pose7>0.316362</Pose7>
        <Pose8>0.101514</Pose8>
        <Pose9>2.85755e-23</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>1.02495</Pose11>
        <Pose12>1.02495</Pose12>
        <Pose13>1.02495</Pose13>
        <Pose14>0.316364</Pose14>
        <Pose15>-0.142871</Pose15>
        <Pose16>-3.45961e-22</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>1.02495</Pose18>
        <Pose19>1.02495</Pose19>
        <Pose20>1.02495</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction27>
    <newAction28>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>0.982563</Pose0>
        <Pose1>0.982563</Pose1>
        <Pose2>0.982563</Pose2>
        <Pose3>0.982563</Pose3>
        <Pose4>0.982563</Pose4>
        <Pose5>0.982563</Pose5>
        <Pose6>0.982563</Pose6>
        <Pose7>0.316362</Pose7>
        <Pose8>0.101514</Pose8>
        <Pose9>3.07723e-23</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>0.982563</Pose11>
        <Pose12>0.982563</Pose12>
        <Pose13>0.982563</Pose13>
        <Pose14>0.316364</Pose14>
        <Pose15>-0.142871</Pose15>
        <Pose16>-9.12093e-23</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>0.982563</Pose18>
        <Pose19>0.982563</Pose19>
        <Pose20>0.982563</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0.023</HandPose5>
        <HandPose6>0.061</HandPose6>
        <HandPose7>0.067</HandPose7>
        <HandPose8>0.083</HandPose8>
        <HandPose9>0.068</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction28>
    <newAction29>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.964457</Pose0>
        <Pose1>0.964457</Pose1>
        <Pose2>0.964457</Pose2>
        <Pose3>0.964457</Pose3>
        <Pose4>0.964457</Pose4>
        <Pose5>0.964457</Pose5>
        <Pose6>0.964457</Pose6>
        <Pose7>0.316362</Pose7>
        <Pose8>0.101514</Pose8>
        <Pose9>2.83653e-23</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>0.964457</Pose11>
        <Pose12>0.964457</Pose12>
        <Pose13>0.964457</Pose13>
        <Pose14>0.316364</Pose14>
        <Pose15>-0.142871</Pose15>
        <Pose16>-2.34131e-23</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>0.964457</Pose18>
        <Pose19>0.964457</Pose19>
        <Pose20>0.964457</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0.023</HandPose5>
        <HandPose6>0.061</HandPose6>
        <HandPose7>0.067</HandPose7>
        <HandPose8>0.083</HandPose8>
        <HandPose9>0.068</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction29>
    <newAction30>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>0.9538</Pose0>
        <Pose1>0.9538</Pose1>
        <Pose2>0.9538</Pose2>
        <Pose3>0.9538</Pose3>
        <Pose4>0.9538</Pose4>
        <Pose5>0.9538</Pose5>
        <Pose6>0.9538</Pose6>
        <Pose7>0.316362</Pose7>
        <Pose8>0.101514</Pose8>
        <Pose9>2.89224e-23</Pose9>
        <Pose10>-0.851886</Pose10>
        <Pose11>0.9538</Pose11>
        <Pose12>0.9538</Pose12>
        <Pose13>0.9538</Pose13>
        <Pose14>0.316364</Pose14>
        <Pose15>-0.14287</Pose15>
        <Pose16>1.07752e-23</Pose16>
        <Pose17>-0.851886</Pose17>
        <Pose18>0.9538</Pose18>
        <Pose19>0.9538</Pose19>
        <Pose20>0.9538</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction30>
    <newAction31>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>0.970688</Pose0>
        <Pose1>0.970688</Pose1>
        <Pose2>0.970688</Pose2>
        <Pose3>0.970688</Pose3>
        <Pose4>0.970688</Pose4>
        <Pose5>0.970688</Pose5>
        <Pose6>0.970688</Pose6>
        <Pose7>-4.89046e-06</Pose7>
        <Pose8>-0.00187927</Pose8>
        <Pose9>2.81897e-13</Pose9>
        <Pose10>-0.000199486</Pose10>
        <Pose11>0.970688</Pose11>
        <Pose12>0.970688</Pose12>
        <Pose13>0.970688</Pose13>
        <Pose14>-3.00107e-06</Pose14>
        <Pose15>-0.000187968</Pose15>
        <Pose16>-1.40617e-14</Pose16>
        <Pose17>-0.000199478</Pose17>
        <Pose18>0.970688</Pose18>
        <Pose19>0.970688</Pose19>
        <Pose20>0.970688</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction31>
</Actions>
