<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>2.1627</Pose0>
        <Pose1>2.1627</Pose1>
        <Pose2>2.1627</Pose2>
        <Pose3>2.1627</Pose3>
        <Pose4>2.1627</Pose4>
        <Pose5>2.1627</Pose5>
        <Pose6>2.1627</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>-0.35796</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>2.1627</Pose11>
        <Pose12>2.1627</Pose12>
        <Pose13>2.1627</Pose13>
        <Pose14>-1.52945e-06</Pose14>
        <Pose15>-0.000188017</Pose15>
        <Pose16>1.12958e-23</Pose16>
        <Pose17>-0.000199707</Pose17>
        <Pose18>2.1627</Pose18>
        <Pose19>2.1627</Pose19>
        <Pose20>2.1627</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.592925</Pose0>
        <Pose1>-0.592925</Pose1>
        <Pose2>-0.592925</Pose2>
        <Pose3>-0.592925</Pose3>
        <Pose4>-0.592925</Pose4>
        <Pose5>-0.592925</Pose5>
        <Pose6>-0.592925</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>-0.3768</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>-0.592925</Pose11>
        <Pose12>-0.592925</Pose12>
        <Pose13>-0.592925</Pose13>
        <Pose14>-1.54935e-06</Pose14>
        <Pose15>-0.0187992</Pose15>
        <Pose16>2.24287e-23</Pose16>
        <Pose17>-0.000199698</Pose17>
        <Pose18>-0.592925</Pose18>
        <Pose19>-0.592925</Pose19>
        <Pose20>-0.592925</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>8</Time>
        <Count>21</Count>
        <Pose0>-1.28816</Pose0>
        <Pose1>-1.28816</Pose1>
        <Pose2>-1.28816</Pose2>
        <Pose3>-1.28816</Pose3>
        <Pose4>-1.28816</Pose4>
        <Pose5>-1.28816</Pose5>
        <Pose6>-1.28816</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>0.3768</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>-1.28816</Pose11>
        <Pose12>-1.28816</Pose12>
        <Pose13>-1.28816</Pose13>
        <Pose14>-1.51112e-06</Pose14>
        <Pose15>-0.0187994</Pose15>
        <Pose16>2.27187e-23</Pose16>
        <Pose17>-0.000199715</Pose17>
        <Pose18>-1.28816</Pose18>
        <Pose19>-1.28816</Pose19>
        <Pose20>-1.28816</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction2>
    <newAction3>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-1.52516</Pose0>
        <Pose1>-1.52516</Pose1>
        <Pose2>-1.52516</Pose2>
        <Pose3>-1.52516</Pose3>
        <Pose4>-1.52516</Pose4>
        <Pose5>-1.52516</Pose5>
        <Pose6>-1.52516</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>0.3768</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>-1.52516</Pose11>
        <Pose12>-1.52516</Pose12>
        <Pose13>-1.52516</Pose13>
        <Pose14>-1.54967e-06</Pose14>
        <Pose15>-0.0187992</Pose15>
        <Pose16>2.27348e-23</Pose16>
        <Pose17>-0.000199698</Pose17>
        <Pose18>-1.52516</Pose18>
        <Pose19>-1.52516</Pose19>
        <Pose20>-1.52516</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction3>
    <newAction4>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>1.5713</Pose0>
        <Pose1>1.5713</Pose1>
        <Pose2>1.5713</Pose2>
        <Pose3>1.5713</Pose3>
        <Pose4>1.5713</Pose4>
        <Pose5>1.5713</Pose5>
        <Pose6>1.5713</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>2.68306e-23</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>1.5713</Pose11>
        <Pose12>1.5713</Pose12>
        <Pose13>1.5713</Pose13>
        <Pose14>-1.53124e-06</Pose14>
        <Pose15>-0.0187993</Pose15>
        <Pose16>0.3768</Pose16>
        <Pose17>-0.000199706</Pose17>
        <Pose18>1.5713</Pose18>
        <Pose19>1.5713</Pose19>
        <Pose20>1.5713</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction4>
    <newAction5>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.47793</Pose0>
        <Pose1>1.47793</Pose1>
        <Pose2>1.47793</Pose2>
        <Pose3>1.47793</Pose3>
        <Pose4>1.47793</Pose4>
        <Pose5>1.47793</Pose5>
        <Pose6>1.47793</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>2.57883e-23</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>1.47793</Pose11>
        <Pose12>1.47793</Pose12>
        <Pose13>1.47793</Pose13>
        <Pose14>-1.46922e-06</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>0.3768</Pose16>
        <Pose17>-0.000199733</Pose17>
        <Pose18>1.47793</Pose18>
        <Pose19>1.47793</Pose19>
        <Pose20>1.47793</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction5>
    <newAction6>
        <Time>8</Time>
        <Count>21</Count>
        <Pose0>1.19064</Pose0>
        <Pose1>1.19064</Pose1>
        <Pose2>1.19064</Pose2>
        <Pose3>1.19064</Pose3>
        <Pose4>1.19064</Pose4>
        <Pose5>1.19064</Pose5>
        <Pose6>1.19064</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>1.97846e-23</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>1.19064</Pose11>
        <Pose12>1.19064</Pose12>
        <Pose13>1.19064</Pose13>
        <Pose14>-1.52317e-06</Pose14>
        <Pose15>-0.0187993</Pose15>
        <Pose16>-0.3768</Pose16>
        <Pose17>-0.000199709</Pose17>
        <Pose18>1.19064</Pose18>
        <Pose19>1.19064</Pose19>
        <Pose20>1.19064</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction6>
    <newAction7>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.14286</Pose0>
        <Pose1>1.14286</Pose1>
        <Pose2>1.14286</Pose2>
        <Pose3>1.14286</Pose3>
        <Pose4>1.14286</Pose4>
        <Pose5>1.14286</Pose5>
        <Pose6>1.14286</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>2.04431e-23</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>1.14286</Pose11>
        <Pose12>1.14286</Pose12>
        <Pose13>1.14286</Pose13>
        <Pose14>-1.47079e-06</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>-0.3768</Pose16>
        <Pose17>-0.000199732</Pose17>
        <Pose18>1.14286</Pose18>
        <Pose19>1.14286</Pose19>
        <Pose20>1.14286</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction7>
    <newAction8>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>1.02495</Pose0>
        <Pose1>1.02495</Pose1>
        <Pose2>1.02495</Pose2>
        <Pose3>1.02495</Pose3>
        <Pose4>1.02495</Pose4>
        <Pose5>1.02495</Pose5>
        <Pose6>1.02495</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>1.49005e-23</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>1.02495</Pose11>
        <Pose12>1.02495</Pose12>
        <Pose13>1.02495</Pose13>
        <Pose14>-1.53006e-06</Pose14>
        <Pose15>-0.0187993</Pose15>
        <Pose16>5.52042e-15</Pose16>
        <Pose17>-0.000199706</Pose17>
        <Pose18>1.02495</Pose18>
        <Pose19>1.02495</Pose19>
        <Pose20>1.02495</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction8>
    <newAction9>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-2.78829</Pose0>
        <Pose1>-2.78829</Pose1>
        <Pose2>-2.78829</Pose2>
        <Pose3>-2.78829</Pose3>
        <Pose4>-2.78829</Pose4>
        <Pose5>-2.78829</Pose5>
        <Pose6>-2.78829</Pose6>
        <Pose7>0.185305</Pose7>
        <Pose8>-0.00187965</Pose8>
        <Pose9>1.76364e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>-2.78829</Pose11>
        <Pose12>-2.78829</Pose12>
        <Pose13>-2.78829</Pose13>
        <Pose14>0.143724</Pose14>
        <Pose15>-0.0187994</Pose15>
        <Pose16>1.58363e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>-2.78829</Pose18>
        <Pose19>-2.78829</Pose19>
        <Pose20>-2.78829</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction9>
    <newAction10>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>3.07635</Pose0>
        <Pose1>3.07635</Pose1>
        <Pose2>3.07635</Pose2>
        <Pose3>3.07635</Pose3>
        <Pose4>3.07635</Pose4>
        <Pose5>3.07635</Pose5>
        <Pose6>3.07635</Pose6>
        <Pose7>0.3548</Pose7>
        <Pose8>-0.00187966</Pose8>
        <Pose9>1.11316e-14</Pose9>
        <Pose10>-0.851892</Pose10>
        <Pose11>3.07635</Pose11>
        <Pose12>3.07635</Pose12>
        <Pose13>3.07635</Pose13>
        <Pose14>0.302823</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>1.94481e-14</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>3.07635</Pose18>
        <Pose19>3.07635</Pose19>
        <Pose20>3.07635</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction10>
    <newAction11>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>-1.87229</Pose0>
        <Pose1>-1.87229</Pose1>
        <Pose2>-1.87229</Pose2>
        <Pose3>-1.87229</Pose3>
        <Pose4>-1.87229</Pose4>
        <Pose5>-1.87229</Pose5>
        <Pose6>-1.87229</Pose6>
        <Pose7>0.22734</Pose7>
        <Pose8>-0.00187965</Pose8>
        <Pose9>-0.377428</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>-1.87229</Pose11>
        <Pose12>-1.87229</Pose12>
        <Pose13>-1.87229</Pose13>
        <Pose14>0.292427</Pose14>
        <Pose15>-0.0187994</Pose15>
        <Pose16>-0.314628</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>-1.87229</Pose18>
        <Pose19>-1.87229</Pose19>
        <Pose20>-1.87229</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction11>
    <newAction12>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>2.5253</Pose0>
        <Pose1>2.5253</Pose1>
        <Pose2>2.5253</Pose2>
        <Pose3>2.5253</Pose3>
        <Pose4>2.5253</Pose4>
        <Pose5>2.5253</Pose5>
        <Pose6>2.5253</Pose6>
        <Pose7>0.258979</Pose7>
        <Pose8>-0.00187965</Pose8>
        <Pose9>-0.3768</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>2.5253</Pose11>
        <Pose12>2.5253</Pose12>
        <Pose13>2.5253</Pose13>
        <Pose14>0.473222</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>-0.314</Pose16>
        <Pose17>-0.851892</Pose17>
        <Pose18>2.5253</Pose18>
        <Pose19>2.5253</Pose19>
        <Pose20>2.5253</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction12>
    <newAction13>
        <Time>8</Time>
        <Count>21</Count>
        <Pose0>1.75198</Pose0>
        <Pose1>1.75198</Pose1>
        <Pose2>1.75198</Pose2>
        <Pose3>1.75198</Pose3>
        <Pose4>1.75198</Pose4>
        <Pose5>1.75198</Pose5>
        <Pose6>1.75198</Pose6>
        <Pose7>0.0266587</Pose7>
        <Pose8>-0.00187964</Pose8>
        <Pose9>0.376172</Pose9>
        <Pose10>-0.851894</Pose10>
        <Pose11>1.75198</Pose11>
        <Pose12>1.75198</Pose12>
        <Pose13>1.75198</Pose13>
        <Pose14>0.0370553</Pose14>
        <Pose15>-0.0187994</Pose15>
        <Pose16>0.376172</Pose16>
        <Pose17>-0.851894</Pose17>
        <Pose18>1.75198</Pose18>
        <Pose19>1.75198</Pose19>
        <Pose20>1.75198</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction13>
    <newAction14>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.13381</Pose0>
        <Pose1>1.13381</Pose1>
        <Pose2>1.13381</Pose2>
        <Pose3>1.13381</Pose3>
        <Pose4>1.13381</Pose4>
        <Pose5>1.13381</Pose5>
        <Pose6>1.13381</Pose6>
        <Pose7>0.100332</Pose7>
        <Pose8>-0.00187964</Pose8>
        <Pose9>0.376172</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>1.13381</Pose11>
        <Pose12>1.13381</Pose12>
        <Pose13>1.13381</Pose13>
        <Pose14>0.0479029</Pose14>
        <Pose15>-0.0187994</Pose15>
        <Pose16>0.376172</Pose16>
        <Pose17>-0.851894</Pose17>
        <Pose18>1.13381</Pose18>
        <Pose19>1.13381</Pose19>
        <Pose20>1.13381</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction14>
    <newAction15>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>1.01638</Pose0>
        <Pose1>1.01638</Pose1>
        <Pose2>1.01638</Pose2>
        <Pose3>1.01638</Pose3>
        <Pose4>1.01638</Pose4>
        <Pose5>1.01638</Pose5>
        <Pose6>1.01638</Pose6>
        <Pose7>0.164062</Pose7>
        <Pose8>-0.00187965</Pose8>
        <Pose9>-1.03539e-15</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>1.01638</Pose11>
        <Pose12>1.01638</Pose12>
        <Pose13>1.01638</Pose13>
        <Pose14>0.196606</Pose14>
        <Pose15>-0.0187993</Pose15>
        <Pose16>-0.000628</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>1.01638</Pose18>
        <Pose19>1.01638</Pose19>
        <Pose20>1.01638</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction15>
    <newAction16>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>0.955515</Pose0>
        <Pose1>0.955515</Pose1>
        <Pose2>0.955515</Pose2>
        <Pose3>0.955515</Pose3>
        <Pose4>0.955515</Pose4>
        <Pose5>0.955515</Pose5>
        <Pose6>0.955515</Pose6>
        <Pose7>0.185305</Pose7>
        <Pose8>-0.00187965</Pose8>
        <Pose9>-1.08989e-19</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>0.955515</Pose11>
        <Pose12>0.955515</Pose12>
        <Pose13>0.955515</Pose13>
        <Pose14>0.0903895</Pose14>
        <Pose15>-0.0187994</Pose15>
        <Pose16>-0.000628</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>0.955515</Pose18>
        <Pose19>0.955515</Pose19>
        <Pose20>0.955515</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction16>
    <newAction17>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>0.953979</Pose0>
        <Pose1>0.953979</Pose1>
        <Pose2>0.953979</Pose2>
        <Pose3>0.953979</Pose3>
        <Pose4>0.953979</Pose4>
        <Pose5>0.953979</Pose5>
        <Pose6>0.953979</Pose6>
        <Pose7>-8.35944e-06</Pose7>
        <Pose8>-0.00187964</Pose8>
        <Pose9>9.77037e-24</Pose9>
        <Pose10>-0.851894</Pose10>
        <Pose11>0.953979</Pose11>
        <Pose12>0.953979</Pose12>
        <Pose13>0.953979</Pose13>
        <Pose14>-7.44251e-06</Pose14>
        <Pose15>-0.0187993</Pose15>
        <Pose16>3.7114e-23</Pose16>
        <Pose17>-0.851894</Pose17>
        <Pose18>0.953979</Pose18>
        <Pose19>0.953979</Pose19>
        <Pose20>0.953979</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction17>
    <newAction18>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>1.14481</Pose0>
        <Pose1>1.14481</Pose1>
        <Pose2>1.14481</Pose2>
        <Pose3>1.14481</Pose3>
        <Pose4>1.14481</Pose4>
        <Pose5>1.14481</Pose5>
        <Pose6>1.14481</Pose6>
        <Pose7>0.406327</Pose7>
        <Pose8>0.142669</Pose8>
        <Pose9>2.20529e-23</Pose9>
        <Pose10>-0.851892</Pose10>
        <Pose11>1.14481</Pose11>
        <Pose12>1.14481</Pose12>
        <Pose13>1.14481</Pose13>
        <Pose14>0.505313</Pose14>
        <Pose15>-0.142876</Pose15>
        <Pose16>9.01011e-24</Pose16>
        <Pose17>-0.851892</Pose17>
        <Pose18>1.14481</Pose18>
        <Pose19>1.14481</Pose19>
        <Pose20>1.14481</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction18>
    <newAction19>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.49002</Pose0>
        <Pose1>1.49002</Pose1>
        <Pose2>1.49002</Pose2>
        <Pose3>1.49002</Pose3>
        <Pose4>1.49002</Pose4>
        <Pose5>1.49002</Pose5>
        <Pose6>1.49002</Pose6>
        <Pose7>0.406327</Pose7>
        <Pose8>0.142669</Pose8>
        <Pose9>8.97284e-24</Pose9>
        <Pose10>-0.851892</Pose10>
        <Pose11>1.49002</Pose11>
        <Pose12>1.49002</Pose12>
        <Pose13>1.49002</Pose13>
        <Pose14>0.898544</Pose14>
        <Pose15>-0.142877</Pose15>
        <Pose16>1.00768e-23</Pose16>
        <Pose17>-0.851892</Pose17>
        <Pose18>1.49002</Pose18>
        <Pose19>1.49002</Pose19>
        <Pose20>1.49002</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction19>
    <newAction20>
        <Time>20</Time>
        <Count>21</Count>
        <Pose0>1.7622</Pose0>
        <Pose1>1.7622</Pose1>
        <Pose2>1.7622</Pose2>
        <Pose3>1.7622</Pose3>
        <Pose4>1.7622</Pose4>
        <Pose5>1.7622</Pose5>
        <Pose6>1.7622</Pose6>
        <Pose7>0.0582976</Pose7>
        <Pose8>0.142668</Pose8>
        <Pose9>1.03483e-23</Pose9>
        <Pose10>-0.851894</Pose10>
        <Pose11>1.7622</Pose11>
        <Pose12>1.7622</Pose12>
        <Pose13>1.7622</Pose13>
        <Pose14>0.406328</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.05972e-23</Pose16>
        <Pose17>-0.851892</Pose17>
        <Pose18>1.7622</Pose18>
        <Pose19>1.7622</Pose19>
        <Pose20>1.7622</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction20>
    <newAction21>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.98467</Pose0>
        <Pose1>1.98467</Pose1>
        <Pose2>1.98467</Pose2>
        <Pose3>1.98467</Pose3>
        <Pose4>1.98467</Pose4>
        <Pose5>1.98467</Pose5>
        <Pose6>1.98467</Pose6>
        <Pose7>0.11118</Pose7>
        <Pose8>0.142668</Pose8>
        <Pose9>1.04295e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>1.98467</Pose11>
        <Pose12>1.98467</Pose12>
        <Pose13>1.98467</Pose13>
        <Pose14>0.406328</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.03684e-23</Pose16>
        <Pose17>-0.851892</Pose17>
        <Pose18>1.98467</Pose18>
        <Pose19>1.98467</Pose19>
        <Pose20>1.98467</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction21>
    <newAction22>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>-0.663603</Pose0>
        <Pose1>-0.663603</Pose1>
        <Pose2>-0.663603</Pose2>
        <Pose3>-0.663603</Pose3>
        <Pose4>-0.663603</Pose4>
        <Pose5>-0.663603</Pose5>
        <Pose6>-0.663603</Pose6>
        <Pose7>0.316381</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.08487e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>-0.663603</Pose11>
        <Pose12>-0.663603</Pose12>
        <Pose13>-0.663603</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.25934e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>-0.663603</Pose18>
        <Pose19>-0.663603</Pose19>
        <Pose20>-0.663603</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction22>
    <newAction23>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-1.30673</Pose0>
        <Pose1>-1.30673</Pose1>
        <Pose2>-1.30673</Pose2>
        <Pose3>-1.30673</Pose3>
        <Pose4>-1.30673</Pose4>
        <Pose5>-1.30673</Pose5>
        <Pose6>-1.30673</Pose6>
        <Pose7>0.316381</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.55538e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>-1.30673</Pose11>
        <Pose12>-1.30673</Pose12>
        <Pose13>-1.30673</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.28169e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>-1.30673</Pose18>
        <Pose19>-1.30673</Pose19>
        <Pose20>-1.30673</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction23>
    <newAction24>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-2.66608</Pose0>
        <Pose1>-2.66608</Pose1>
        <Pose2>-2.66608</Pose2>
        <Pose3>-2.66608</Pose3>
        <Pose4>-2.66608</Pose4>
        <Pose5>-2.66608</Pose5>
        <Pose6>-2.66608</Pose6>
        <Pose7>0.316382</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.58942e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>-2.66608</Pose11>
        <Pose12>-2.66608</Pose12>
        <Pose13>-2.66608</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.32153e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>-2.66608</Pose18>
        <Pose19>-2.66608</Pose19>
        <Pose20>-2.66608</Pose20>
        <Count>10</Count>
        <HandPose0>0.084</HandPose0>
        <HandPose1>0.083</HandPose1>
        <HandPose2>0.081</HandPose2>
        <HandPose3>0.085</HandPose3>
        <HandPose4>0.084</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction24>
    <newAction25>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>2.35281</Pose0>
        <Pose1>2.35281</Pose1>
        <Pose2>2.35281</Pose2>
        <Pose3>2.35281</Pose3>
        <Pose4>2.35281</Pose4>
        <Pose5>2.35281</Pose5>
        <Pose6>2.35281</Pose6>
        <Pose7>0.316382</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.58684e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>2.35281</Pose11>
        <Pose12>2.35281</Pose12>
        <Pose13>2.35281</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.27562e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>2.35281</Pose18>
        <Pose19>2.35281</Pose19>
        <Pose20>2.35281</Pose20>
        <Count>10</Count>
        <HandPose0>0.084</HandPose0>
        <HandPose1>0.083</HandPose1>
        <HandPose2>0.081</HandPose2>
        <HandPose3>0.085</HandPose3>
        <HandPose4>0.084</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction25>
    <newAction26>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>1.69545</Pose0>
        <Pose1>1.69545</Pose1>
        <Pose2>1.69545</Pose2>
        <Pose3>1.69545</Pose3>
        <Pose4>1.69545</Pose4>
        <Pose5>1.69545</Pose5>
        <Pose6>1.69545</Pose6>
        <Pose7>0.316381</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.60886e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>1.69545</Pose11>
        <Pose12>1.69545</Pose12>
        <Pose13>1.69545</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.37329e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>1.69545</Pose18>
        <Pose19>1.69545</Pose19>
        <Pose20>1.69545</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction26>
    <newAction27>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.21897</Pose0>
        <Pose1>1.21897</Pose1>
        <Pose2>1.21897</Pose2>
        <Pose3>1.21897</Pose3>
        <Pose4>1.21897</Pose4>
        <Pose5>1.21897</Pose5>
        <Pose6>1.21897</Pose6>
        <Pose7>0.316381</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.60563e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>1.21897</Pose11>
        <Pose12>1.21897</Pose12>
        <Pose13>1.21897</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142876</Pose15>
        <Pose16>2.30195e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>1.21897</Pose18>
        <Pose19>1.21897</Pose19>
        <Pose20>1.21897</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction27>
    <newAction28>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>1.00314</Pose0>
        <Pose1>1.00314</Pose1>
        <Pose2>1.00314</Pose2>
        <Pose3>1.00314</Pose3>
        <Pose4>1.00314</Pose4>
        <Pose5>1.00314</Pose5>
        <Pose6>1.00314</Pose6>
        <Pose7>0.316381</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.5508e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>1.00314</Pose11>
        <Pose12>1.00314</Pose12>
        <Pose13>1.00314</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.53896e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>1.00314</Pose18>
        <Pose19>1.00314</Pose19>
        <Pose20>1.00314</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0.023</HandPose5>
        <HandPose6>0.061</HandPose6>
        <HandPose7>0.067</HandPose7>
        <HandPose8>0.083</HandPose8>
        <HandPose9>0.068</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction28>
    <newAction29>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>0.951505</Pose0>
        <Pose1>0.951505</Pose1>
        <Pose2>0.951505</Pose2>
        <Pose3>0.951505</Pose3>
        <Pose4>0.951505</Pose4>
        <Pose5>0.951505</Pose5>
        <Pose6>0.951505</Pose6>
        <Pose7>0.316381</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.46787e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>0.951505</Pose11>
        <Pose12>0.951505</Pose12>
        <Pose13>0.951505</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142876</Pose15>
        <Pose16>2.49056e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>0.951505</Pose18>
        <Pose19>0.951505</Pose19>
        <Pose20>0.951505</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0.023</HandPose5>
        <HandPose6>0.061</HandPose6>
        <HandPose7>0.067</HandPose7>
        <HandPose8>0.083</HandPose8>
        <HandPose9>0.068</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction29>
    <newAction30>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>1.01619</Pose0>
        <Pose1>1.01619</Pose1>
        <Pose2>1.01619</Pose2>
        <Pose3>1.01619</Pose3>
        <Pose4>1.01619</Pose4>
        <Pose5>1.01619</Pose5>
        <Pose6>1.01619</Pose6>
        <Pose7>0.316381</Pose7>
        <Pose8>0.101517</Pose8>
        <Pose9>1.48647e-23</Pose9>
        <Pose10>-0.851893</Pose10>
        <Pose11>1.01619</Pose11>
        <Pose12>1.01619</Pose12>
        <Pose13>1.01619</Pose13>
        <Pose14>0.316382</Pose14>
        <Pose15>-0.142875</Pose15>
        <Pose16>2.86009e-23</Pose16>
        <Pose17>-0.851893</Pose17>
        <Pose18>1.01619</Pose18>
        <Pose19>1.01619</Pose19>
        <Pose20>1.01619</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction30>
    <newAction31>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-0.849801</Pose0>
        <Pose1>-0.849801</Pose1>
        <Pose2>-0.849801</Pose2>
        <Pose3>-0.849801</Pose3>
        <Pose4>-0.849801</Pose4>
        <Pose5>-0.849801</Pose5>
        <Pose6>-0.849801</Pose6>
        <Pose7>-2.48022e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>2.81897e-13</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>-0.849801</Pose11>
        <Pose12>-0.849801</Pose12>
        <Pose13>-0.849801</Pose13>
        <Pose14>-1.54467e-06</Pose14>
        <Pose15>-0.000187958</Pose15>
        <Pose16>-1.40651e-14</Pose16>
        <Pose17>-0.0001997</Pose17>
        <Pose18>-0.849801</Pose18>
        <Pose19>-0.849801</Pose19>
        <Pose20>-0.849801</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction31>
</Actions>
