<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>1.24235</Pose0>
        <Pose1>1.24235</Pose1>
        <Pose2>1.24235</Pose2>
        <Pose3>1.24235</Pose3>
        <Pose4>1.24235</Pose4>
        <Pose5>1.24235</Pose5>
        <Pose6>1.24235</Pose6>
        <Pose7>0.903968</Pose7>
        <Pose8>0.0187998</Pose8>
        <Pose9>1.37839e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.24235</Pose11>
        <Pose12>1.24235</Pose12>
        <Pose13>1.24235</Pose13>
        <Pose14>-1.57681e-06</Pose14>
        <Pose15>-0.0187991</Pose15>
        <Pose16>2.26845e-23</Pose16>
        <Pose17>-0.000199686</Pose17>
        <Pose18>1.24235</Pose18>
        <Pose19>1.24235</Pose19>
        <Pose20>1.24235</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.853617</Pose0>
        <Pose1>-0.853617</Pose1>
        <Pose2>-0.853617</Pose2>
        <Pose3>-0.853617</Pose3>
        <Pose4>-0.853617</Pose4>
        <Pose5>-0.853617</Pose5>
        <Pose6>-0.853617</Pose6>
        <Pose7>0.903937</Pose7>
        <Pose8>0.0187997</Pose8>
        <Pose9>2.91061e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-0.853617</Pose11>
        <Pose12>-0.853617</Pose12>
        <Pose13>-0.853617</Pose13>
        <Pose14>-3.0802e-06</Pose14>
        <Pose15>-0.0187985</Pose15>
        <Pose16>4.53295e-23</Pose16>
        <Pose17>-0.000199404</Pose17>
        <Pose18>-0.853617</Pose18>
        <Pose19>-0.853617</Pose19>
        <Pose20>-0.853617</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-0.399368</Pose0>
        <Pose1>-0.399368</Pose1>
        <Pose2>-0.399368</Pose2>
        <Pose3>-0.399368</Pose3>
        <Pose4>-0.399368</Pose4>
        <Pose5>-0.399368</Pose5>
        <Pose6>-0.399368</Pose6>
        <Pose7>0.903905</Pose7>
        <Pose8>0.0187996</Pose8>
        <Pose9>4.26283e-23</Pose9>
        <Pose10>-1.20258</Pose10>
        <Pose11>-0.399368</Pose11>
        <Pose12>-0.399368</Pose12>
        <Pose13>-0.399368</Pose13>
        <Pose14>-4.65223e-06</Pose14>
        <Pose15>-0.0187977</Pose15>
        <Pose16>6.49642e-23</Pose16>
        <Pose17>-0.000199092</Pose17>
        <Pose18>-0.399368</Pose18>
        <Pose19>-0.399368</Pose19>
        <Pose20>-0.399368</Pose20>
        <Count>10</Count>
        <HandPose0>0.005</HandPose0>
        <HandPose1>0.019</HandPose1>
        <HandPose2>0.021</HandPose2>
        <HandPose3>0.03</HandPose3>
        <HandPose4>0.017</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction2>
    <newAction3>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.484132</Pose0>
        <Pose1>-0.484132</Pose1>
        <Pose2>-0.484132</Pose2>
        <Pose3>-0.484132</Pose3>
        <Pose4>-0.484132</Pose4>
        <Pose5>-0.484132</Pose5>
        <Pose6>-0.484132</Pose6>
        <Pose7>0.903905</Pose7>
        <Pose8>0.0187996</Pose8>
        <Pose9>4.45933e-23</Pose9>
        <Pose10>-1.20258</Pose10>
        <Pose11>-0.484132</Pose11>
        <Pose12>-0.484132</Pose12>
        <Pose13>-0.484132</Pose13>
        <Pose14>-4.60726e-06</Pose14>
        <Pose15>-0.0187978</Pose15>
        <Pose16>6.70518e-23</Pose16>
        <Pose17>-0.000199112</Pose17>
        <Pose18>-0.484132</Pose18>
        <Pose19>-0.484132</Pose19>
        <Pose20>-0.484132</Pose20>
        <Count>10</Count>
        <HandPose0>0.005</HandPose0>
        <HandPose1>0.019</HandPose1>
        <HandPose2>0.021</HandPose2>
        <HandPose3>0.03</HandPose3>
        <HandPose4>0.017</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction3>
    <newAction4>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-1.02838</Pose0>
        <Pose1>-1.02838</Pose1>
        <Pose2>-1.02838</Pose2>
        <Pose3>-1.02838</Pose3>
        <Pose4>-1.02838</Pose4>
        <Pose5>-1.02838</Pose5>
        <Pose6>-1.02838</Pose6>
        <Pose7>0.903905</Pose7>
        <Pose8>0.0187995</Pose8>
        <Pose9>3.98123e-23</Pose9>
        <Pose10>-1.20258</Pose10>
        <Pose11>-1.02838</Pose11>
        <Pose12>-1.02838</Pose12>
        <Pose13>-1.02838</Pose13>
        <Pose14>-4.62626e-06</Pose14>
        <Pose15>-0.0187978</Pose15>
        <Pose16>6.80114e-23</Pose16>
        <Pose17>-0.000199103</Pose17>
        <Pose18>-1.02838</Pose18>
        <Pose19>-1.02838</Pose19>
        <Pose20>-1.02838</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction4>
    <newAction5>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>1.9315</Pose0>
        <Pose1>1.9315</Pose1>
        <Pose2>1.9315</Pose2>
        <Pose3>1.9315</Pose3>
        <Pose4>1.9315</Pose4>
        <Pose5>1.9315</Pose5>
        <Pose6>1.9315</Pose6>
        <Pose7>0.858769</Pose7>
        <Pose8>-0.00187974</Pose8>
        <Pose9>1.50005e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.9315</Pose11>
        <Pose12>1.9315</Pose12>
        <Pose13>1.9315</Pose13>
        <Pose14>0.903969</Pose14>
        <Pose15>0.00187991</Pose15>
        <Pose16>2.27152e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.9315</Pose18>
        <Pose19>1.9315</Pose19>
        <Pose20>1.9315</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction5>
    <newAction6>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.81407</Pose0>
        <Pose1>1.81407</Pose1>
        <Pose2>1.81407</Pose2>
        <Pose3>1.81407</Pose3>
        <Pose4>1.81407</Pose4>
        <Pose5>1.81407</Pose5>
        <Pose6>1.81407</Pose6>
        <Pose7>0.858769</Pose7>
        <Pose8>-0.00187974</Pose8>
        <Pose9>1.5699e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.81407</Pose11>
        <Pose12>1.81407</Pose12>
        <Pose13>1.81407</Pose13>
        <Pose14>0.903969</Pose14>
        <Pose15>0.00187989</Pose15>
        <Pose16>2.26934e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.81407</Pose18>
        <Pose19>1.81407</Pose19>
        <Pose20>1.81407</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction6>
    <newAction7>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>1.13944</Pose0>
        <Pose1>1.13944</Pose1>
        <Pose2>1.13944</Pose2>
        <Pose3>1.13944</Pose3>
        <Pose4>1.13944</Pose4>
        <Pose5>1.13944</Pose5>
        <Pose6>1.13944</Pose6>
        <Pose7>0.858769</Pose7>
        <Pose8>-0.00187974</Pose8>
        <Pose9>1.54433e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.13944</Pose11>
        <Pose12>1.13944</Pose12>
        <Pose13>1.13944</Pose13>
        <Pose14>0.903969</Pose14>
        <Pose15>0.00187984</Pose15>
        <Pose16>2.26632e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.13944</Pose18>
        <Pose19>1.13944</Pose19>
        <Pose20>1.13944</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0.013</HandPose5>
        <HandPose6>0.02</HandPose6>
        <HandPose7>0.038</HandPose7>
        <HandPose8>0.031</HandPose8>
        <HandPose9>0.018</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction7>
    <newAction8>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>1.05001</Pose0>
        <Pose1>1.05001</Pose1>
        <Pose2>1.05001</Pose2>
        <Pose3>1.05001</Pose3>
        <Pose4>1.05001</Pose4>
        <Pose5>1.05001</Pose5>
        <Pose6>1.05001</Pose6>
        <Pose7>0.858769</Pose7>
        <Pose8>-0.00187974</Pose8>
        <Pose9>1.52717e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.05001</Pose11>
        <Pose12>1.05001</Pose12>
        <Pose13>1.05001</Pose13>
        <Pose14>0.903969</Pose14>
        <Pose15>0.00187984</Pose15>
        <Pose16>2.26823e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.05001</Pose18>
        <Pose19>1.05001</Pose19>
        <Pose20>1.05001</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0.013</HandPose5>
        <HandPose6>0.02</HandPose6>
        <HandPose7>0.038</HandPose7>
        <HandPose8>0.031</HandPose8>
        <HandPose9>0.018</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction8>
    <newAction9>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>0.953264</Pose0>
        <Pose1>0.953264</Pose1>
        <Pose2>0.953264</Pose2>
        <Pose3>0.953264</Pose3>
        <Pose4>0.953264</Pose4>
        <Pose5>0.953264</Pose5>
        <Pose6>0.953264</Pose6>
        <Pose7>0.858769</Pose7>
        <Pose8>-0.00187974</Pose8>
        <Pose9>1.46834e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>0.953264</Pose11>
        <Pose12>0.953264</Pose12>
        <Pose13>0.953264</Pose13>
        <Pose14>0.903969</Pose14>
        <Pose15>0.00187995</Pose15>
        <Pose16>2.26413e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>0.953264</Pose18>
        <Pose19>0.953264</Pose19>
        <Pose20>0.953264</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction9>
    <newAction10>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>0.955419</Pose0>
        <Pose1>0.955419</Pose1>
        <Pose2>0.955419</Pose2>
        <Pose3>0.955419</Pose3>
        <Pose4>0.955419</Pose4>
        <Pose5>0.955419</Pose5>
        <Pose6>0.955419</Pose6>
        <Pose7>0.81354</Pose7>
        <Pose8>0.204911</Pose8>
        <Pose9>2.74334e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>0.955419</Pose11>
        <Pose12>0.955419</Pose12>
        <Pose13>0.955419</Pose13>
        <Pose14>0.85874</Pose14>
        <Pose15>-0.204911</Pose15>
        <Pose16>4.53544e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>0.955419</Pose18>
        <Pose19>0.955419</Pose19>
        <Pose20>0.955419</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction10>
    <newAction11>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.24972</Pose0>
        <Pose1>1.24972</Pose1>
        <Pose2>1.24972</Pose2>
        <Pose3>1.24972</Pose3>
        <Pose4>1.24972</Pose4>
        <Pose5>1.24972</Pose5>
        <Pose6>1.24972</Pose6>
        <Pose7>0.81357</Pose7>
        <Pose8>0.204916</Pose8>
        <Pose9>1.52801e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.24972</Pose11>
        <Pose12>1.24972</Pose12>
        <Pose13>1.24972</Pose13>
        <Pose14>0.85877</Pose14>
        <Pose15>-0.204916</Pose15>
        <Pose16>2.26786e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.24972</Pose18>
        <Pose19>1.24972</Pose19>
        <Pose20>1.24972</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction11>
    <newAction12>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>0.969903</Pose0>
        <Pose1>0.969903</Pose1>
        <Pose2>0.969903</Pose2>
        <Pose3>0.969903</Pose3>
        <Pose4>0.969903</Pose4>
        <Pose5>0.969903</Pose5>
        <Pose6>0.969903</Pose6>
        <Pose7>0.858738</Pose7>
        <Pose8>-0.00187947</Pose8>
        <Pose9>2.85484e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>0.969903</Pose11>
        <Pose12>0.969903</Pose12>
        <Pose13>0.969903</Pose13>
        <Pose14>0.903938</Pose14>
        <Pose15>0.00187987</Pose15>
        <Pose16>4.58408e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>0.969903</Pose18>
        <Pose19>0.969903</Pose19>
        <Pose20>0.969903</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction12>
    <newAction13>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.3632</Pose0>
        <Pose1>1.3632</Pose1>
        <Pose2>1.3632</Pose2>
        <Pose3>1.3632</Pose3>
        <Pose4>1.3632</Pose4>
        <Pose5>1.3632</Pose5>
        <Pose6>1.3632</Pose6>
        <Pose7>0.858707</Pose7>
        <Pose8>-0.00187921</Pose8>
        <Pose9>4.27225e-23</Pose9>
        <Pose10>-1.20258</Pose10>
        <Pose11>1.3632</Pose11>
        <Pose12>1.3632</Pose12>
        <Pose13>1.3632</Pose13>
        <Pose14>0.903907</Pose14>
        <Pose15>0.00187981</Pose15>
        <Pose16>6.74997e-23</Pose16>
        <Pose17>-1.20258</Pose17>
        <Pose18>1.3632</Pose18>
        <Pose19>1.3632</Pose19>
        <Pose20>1.3632</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction13>
    <newAction14>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.0194316</Pose0>
        <Pose1>-0.0194316</Pose1>
        <Pose2>-0.0194316</Pose2>
        <Pose3>-0.0194316</Pose3>
        <Pose4>-0.0194316</Pose4>
        <Pose5>-0.0194316</Pose5>
        <Pose6>-0.0194316</Pose6>
        <Pose7>-9.70673e-06</Pose7>
        <Pose8>-0.00187966</Pose8>
        <Pose9>1.47042e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-0.0194316</Pose11>
        <Pose12>-0.0194316</Pose12>
        <Pose13>-0.0194316</Pose13>
        <Pose14>-8.76826e-06</Pose14>
        <Pose15>-0.0187994</Pose15>
        <Pose16>2.32227e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>-0.0194316</Pose18>
        <Pose19>-0.0194316</Pose19>
        <Pose20>-0.0194316</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction14>
    <newAction15>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.040647</Pose0>
        <Pose1>-0.040647</Pose1>
        <Pose2>-0.040647</Pose2>
        <Pose3>-0.040647</Pose3>
        <Pose4>-0.040647</Pose4>
        <Pose5>-0.040647</Pose5>
        <Pose6>-0.040647</Pose6>
        <Pose7>-9.7067e-06</Pose7>
        <Pose8>-0.00187966</Pose8>
        <Pose9>1.3492e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-0.040647</Pose11>
        <Pose12>-0.040647</Pose12>
        <Pose13>-0.040647</Pose13>
        <Pose14>-8.76472e-06</Pose14>
        <Pose15>-0.0187994</Pose15>
        <Pose16>2.27611e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>-0.040647</Pose18>
        <Pose19>-0.040647</Pose19>
        <Pose20>-0.040647</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction15>
    <newAction16>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.417958</Pose0>
        <Pose1>-0.417958</Pose1>
        <Pose2>-0.417958</Pose2>
        <Pose3>-0.417958</Pose3>
        <Pose4>-0.417958</Pose4>
        <Pose5>-0.417958</Pose5>
        <Pose6>-0.417958</Pose6>
        <Pose7>0.903968</Pose7>
        <Pose8>-0.00187975</Pose8>
        <Pose9>1.378e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-0.417958</Pose11>
        <Pose12>-0.417958</Pose12>
        <Pose13>-0.417958</Pose13>
        <Pose14>0.903969</Pose14>
        <Pose15>-0.0187996</Pose15>
        <Pose16>2.26851e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>-0.417958</Pose18>
        <Pose19>-0.417958</Pose19>
        <Pose20>-0.417958</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction16>
    <newAction17>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>-0.7722</Pose0>
        <Pose1>-0.7722</Pose1>
        <Pose2>-0.7722</Pose2>
        <Pose3>-0.7722</Pose3>
        <Pose4>-0.7722</Pose4>
        <Pose5>-0.7722</Pose5>
        <Pose6>-0.7722</Pose6>
        <Pose7>0.903968</Pose7>
        <Pose8>-0.00187975</Pose8>
        <Pose9>1.51854e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-0.7722</Pose11>
        <Pose12>-0.7722</Pose12>
        <Pose13>-0.7722</Pose13>
        <Pose14>0.903969</Pose14>
        <Pose15>-0.0187997</Pose15>
        <Pose16>2.26925e-23</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>-0.7722</Pose18>
        <Pose19>-0.7722</Pose19>
        <Pose20>-0.7722</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction17>
    <newAction18>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>1.87209</Pose0>
        <Pose1>1.87209</Pose1>
        <Pose2>1.87209</Pose2>
        <Pose3>1.87209</Pose3>
        <Pose4>1.87209</Pose4>
        <Pose5>1.87209</Pose5>
        <Pose6>1.87209</Pose6>
        <Pose7>0.858769</Pose7>
        <Pose8>-0.00187974</Pose8>
        <Pose9>-0.3768</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.87209</Pose11>
        <Pose12>1.87209</Pose12>
        <Pose13>1.87209</Pose13>
        <Pose14>0.85877</Pose14>
        <Pose15>-0.0187996</Pose15>
        <Pose16>-0.3768</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.87209</Pose18>
        <Pose19>1.87209</Pose19>
        <Pose20>1.87209</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction18>
    <newAction19>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.65329</Pose0>
        <Pose1>1.65329</Pose1>
        <Pose2>1.65329</Pose2>
        <Pose3>1.65329</Pose3>
        <Pose4>1.65329</Pose4>
        <Pose5>1.65329</Pose5>
        <Pose6>1.65329</Pose6>
        <Pose7>0.858769</Pose7>
        <Pose8>-0.00187974</Pose8>
        <Pose9>-0.3768</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.65329</Pose11>
        <Pose12>1.65329</Pose12>
        <Pose13>1.65329</Pose13>
        <Pose14>0.85877</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>-0.3768</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.65329</Pose18>
        <Pose19>1.65329</Pose19>
        <Pose20>1.65329</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction19>
    <newAction20>
        <Time>8</Time>
        <Count>21</Count>
        <Pose0>1.21435</Pose0>
        <Pose1>1.21435</Pose1>
        <Pose2>1.21435</Pose2>
        <Pose3>1.21435</Pose3>
        <Pose4>1.21435</Pose4>
        <Pose5>1.21435</Pose5>
        <Pose6>1.21435</Pose6>
        <Pose7>0.858769</Pose7>
        <Pose8>-0.00187974</Pose8>
        <Pose9>0.3768</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.21435</Pose11>
        <Pose12>1.21435</Pose12>
        <Pose13>1.21435</Pose13>
        <Pose14>0.85877</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>0.3768</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.21435</Pose18>
        <Pose19>1.21435</Pose19>
        <Pose20>1.21435</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction20>
    <newAction21>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>1.09677</Pose0>
        <Pose1>1.09677</Pose1>
        <Pose2>1.09677</Pose2>
        <Pose3>1.09677</Pose3>
        <Pose4>1.09677</Pose4>
        <Pose5>1.09677</Pose5>
        <Pose6>1.09677</Pose6>
        <Pose7>0.858769</Pose7>
        <Pose8>-0.00187974</Pose8>
        <Pose9>0.3768</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.09677</Pose11>
        <Pose12>1.09677</Pose12>
        <Pose13>1.09677</Pose13>
        <Pose14>0.85877</Pose14>
        <Pose15>-0.0187996</Pose15>
        <Pose16>0.3768</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.09677</Pose18>
        <Pose19>1.09677</Pose19>
        <Pose20>1.09677</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction21>
    <newAction22>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>0.962044</Pose0>
        <Pose1>0.962044</Pose1>
        <Pose2>0.962044</Pose2>
        <Pose3>0.962044</Pose3>
        <Pose4>0.962044</Pose4>
        <Pose5>0.962044</Pose5>
        <Pose6>0.962044</Pose6>
        <Pose7>0.81357</Pose7>
        <Pose8>-0.00187973</Pose8>
        <Pose9>-1.80726e-16</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>0.962044</Pose11>
        <Pose12>0.962044</Pose12>
        <Pose13>0.962044</Pose13>
        <Pose14>0.81357</Pose14>
        <Pose15>-0.0187996</Pose15>
        <Pose16>-9.65803e-15</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>0.962044</Pose18>
        <Pose19>0.962044</Pose19>
        <Pose20>0.962044</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction22>
    <newAction23>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>1.88244</Pose0>
        <Pose1>1.88244</Pose1>
        <Pose2>1.88244</Pose2>
        <Pose3>1.88244</Pose3>
        <Pose4>1.88244</Pose4>
        <Pose5>1.88244</Pose5>
        <Pose6>1.88244</Pose6>
        <Pose7>-9.7067e-06</Pose7>
        <Pose8>-0.00187966</Pose8>
        <Pose9>2.96662e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>1.88244</Pose11>
        <Pose12>1.88244</Pose12>
        <Pose13>1.88244</Pose13>
        <Pose14>-8.74664e-06</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>-0.0628</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>1.88244</Pose18>
        <Pose19>1.88244</Pose19>
        <Pose20>1.88244</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction23>
    <newAction24>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>2.18454</Pose0>
        <Pose1>2.18454</Pose1>
        <Pose2>2.18454</Pose2>
        <Pose3>2.18454</Pose3>
        <Pose4>2.18454</Pose4>
        <Pose5>2.18454</Pose5>
        <Pose6>2.18454</Pose6>
        <Pose7>-9.7067e-06</Pose7>
        <Pose8>-0.00187966</Pose8>
        <Pose9>2.03161e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>2.18454</Pose11>
        <Pose12>2.18454</Pose12>
        <Pose13>2.18454</Pose13>
        <Pose14>-8.74244e-06</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>-0.0628</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>2.18454</Pose18>
        <Pose19>2.18454</Pose19>
        <Pose20>2.18454</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction24>
    <newAction25>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-2.13908</Pose0>
        <Pose1>-2.13908</Pose1>
        <Pose2>-2.13908</Pose2>
        <Pose3>-2.13908</Pose3>
        <Pose4>-2.13908</Pose4>
        <Pose5>-2.13908</Pose5>
        <Pose6>-2.13908</Pose6>
        <Pose7>0.903968</Pose7>
        <Pose8>-0.00187975</Pose8>
        <Pose9>8.47471e-24</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-2.13908</Pose11>
        <Pose12>-2.13908</Pose12>
        <Pose13>-2.13908</Pose13>
        <Pose14>-0.632788</Pose14>
        <Pose15>-0.0187996</Pose15>
        <Pose16>-0.0628</Pose16>
        <Pose17>-1.2026</Pose17>
        <Pose18>-2.13908</Pose18>
        <Pose19>-2.13908</Pose19>
        <Pose20>-2.13908</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction25>
    <newAction26>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-1.40937</Pose0>
        <Pose1>-1.40937</Pose1>
        <Pose2>-1.40937</Pose2>
        <Pose3>-1.40937</Pose3>
        <Pose4>-1.40937</Pose4>
        <Pose5>-1.40937</Pose5>
        <Pose6>-1.40937</Pose6>
        <Pose7>0.903968</Pose7>
        <Pose8>-0.00187975</Pose8>
        <Pose9>9.10848e-24</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-1.40937</Pose11>
        <Pose12>-1.40937</Pose12>
        <Pose13>-1.40937</Pose13>
        <Pose14>-0.632788</Pose14>
        <Pose15>-0.0187996</Pose15>
        <Pose16>-0.0628</Pose16>
        <Pose17>-1.2026</Pose17>
        <Pose18>-1.40937</Pose18>
        <Pose19>-1.40937</Pose19>
        <Pose20>-1.40937</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction26>
    <newAction27>
        <Time>35</Time>
        <Count>21</Count>
        <Pose0>-0.305938</Pose0>
        <Pose1>-0.305938</Pose1>
        <Pose2>-0.305938</Pose2>
        <Pose3>-0.305938</Pose3>
        <Pose4>-0.305938</Pose4>
        <Pose5>-0.305938</Pose5>
        <Pose6>-0.305938</Pose6>
        <Pose7>-0.542392</Pose7>
        <Pose8>-0.00187969</Pose8>
        <Pose9>9.77302e-24</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-0.305938</Pose11>
        <Pose12>-0.305938</Pose12>
        <Pose13>-0.305938</Pose13>
        <Pose14>0.903969</Pose14>
        <Pose15>-0.0187996</Pose15>
        <Pose16>-0.0628</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>-0.305938</Pose18>
        <Pose19>-0.305938</Pose19>
        <Pose20>-0.305938</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction27>
    <newAction28>
        <Time>5</Time>
        <Count>21</Count>
        <Pose0>-0.219634</Pose0>
        <Pose1>-0.219634</Pose1>
        <Pose2>-0.219634</Pose2>
        <Pose3>-0.219634</Pose3>
        <Pose4>-0.219634</Pose4>
        <Pose5>-0.219634</Pose5>
        <Pose6>-0.219634</Pose6>
        <Pose7>-0.542392</Pose7>
        <Pose8>-0.00187969</Pose8>
        <Pose9>1.03617e-23</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-0.219634</Pose11>
        <Pose12>-0.219634</Pose12>
        <Pose13>-0.219634</Pose13>
        <Pose14>0.903969</Pose14>
        <Pose15>-0.0187996</Pose15>
        <Pose16>-0.0628</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>-0.219634</Pose18>
        <Pose19>-0.219634</Pose19>
        <Pose20>-0.219634</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction28>
    <newAction29>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.0964259</Pose0>
        <Pose1>-0.0964259</Pose1>
        <Pose2>-0.0964259</Pose2>
        <Pose3>-0.0964259</Pose3>
        <Pose4>-0.0964259</Pose4>
        <Pose5>-0.0964259</Pose5>
        <Pose6>-0.0964259</Pose6>
        <Pose7>-9.7067e-06</Pose7>
        <Pose8>-0.00187966</Pose8>
        <Pose9>9.86833e-24</Pose9>
        <Pose10>-1.20259</Pose10>
        <Pose11>-0.0964259</Pose11>
        <Pose12>-0.0964259</Pose12>
        <Pose13>-0.0964259</Pose13>
        <Pose14>-8.74065e-06</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>-0.0628</Pose16>
        <Pose17>-1.20259</Pose17>
        <Pose18>-0.0964259</Pose18>
        <Pose19>-0.0964259</Pose19>
        <Pose20>-0.0964259</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction29>
    <newAction30>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-0.771282</Pose0>
        <Pose1>-0.771282</Pose1>
        <Pose2>-0.771282</Pose2>
        <Pose3>-0.771282</Pose3>
        <Pose4>-0.771282</Pose4>
        <Pose5>-0.771282</Pose5>
        <Pose6>-0.771282</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>1.5266e-23</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>-0.771282</Pose11>
        <Pose12>-0.771282</Pose12>
        <Pose13>-0.771282</Pose13>
        <Pose14>-1.51436e-06</Pose14>
        <Pose15>-0.000188084</Pose15>
        <Pose16>9.80815e-18</Pose16>
        <Pose17>-0.000199714</Pose17>
        <Pose18>-0.771282</Pose18>
        <Pose19>-0.771282</Pose19>
        <Pose20>-0.771282</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction30>
    <newAction31>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-0.625275</Pose0>
        <Pose1>-0.625275</Pose1>
        <Pose2>-0.625275</Pose2>
        <Pose3>-0.625275</Pose3>
        <Pose4>-0.625275</Pose4>
        <Pose5>-0.625275</Pose5>
        <Pose6>-0.625275</Pose6>
        <Pose7>-2.48019e-06</Pose7>
        <Pose8>-0.00187963</Pose8>
        <Pose9>1.24292e-23</Pose9>
        <Pose10>-0.000199708</Pose10>
        <Pose11>-0.625275</Pose11>
        <Pose12>-0.625275</Pose12>
        <Pose13>-0.625275</Pose13>
        <Pose14>-1.57042e-06</Pose14>
        <Pose15>-0.000187862</Pose15>
        <Pose16>3.38393e-18</Pose16>
        <Pose17>-0.000199688</Pose17>
        <Pose18>-0.625275</Pose18>
        <Pose19>-0.625275</Pose19>
        <Pose20>-0.625275</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction31>
</Actions>
