<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-5.4882e-05</Pose0>
        <Pose1>1.88605e-05</Pose1>
        <Pose2>-0.00223877</Pose2>
        <Pose3>1.88605e-05</Pose3>
        <Pose4>-5.80971e-09</Pose4>
        <Pose5>3.86716e-09</Pose5>
        <Pose6>1.88605e-05</Pose6>
        <Pose7>1.88605e-05</Pose7>
        <Pose8>4.75156e-06</Pose8>
        <Pose9>1.88605e-05</Pose9>
        <Pose10>-3.82149e-08</Pose10>
        <Pose11>1.88605e-05</Pose11>
        <Pose12>1.88605e-05</Pose12>
        <Pose13>1.88605e-05</Pose13>
        <Pose14>1.88605e-05</Pose14>
        <Pose15>-3.549e-06</Pose15>
        <Pose16>1.88605e-05</Pose16>
        <Pose17>-5.33209e-08</Pose17>
        <Pose18>1.88605e-05</Pose18>
        <Pose19>1.88605e-05</Pose19>
        <Pose20>1.88605e-05</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-5.48968e-05</Pose0>
        <Pose1>0.000670878</Pose1>
        <Pose2>-0.0279062</Pose2>
        <Pose3>0.000670878</Pose3>
        <Pose4>1.70782e-08</Pose4>
        <Pose5>-9.19675e-06</Pose5>
        <Pose6>0.000670878</Pose6>
        <Pose7>0.000670878</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.000670878</Pose9>
        <Pose10>-3.30359e-05</Pose10>
        <Pose11>0.000670878</Pose11>
        <Pose12>0.000670878</Pose12>
        <Pose13>0.000670878</Pose13>
        <Pose14>0.000670878</Pose14>
        <Pose15>-0.000187788</Pose15>
        <Pose16>0.000670878</Pose16>
        <Pose17>-3.30501e-05</Pose17>
        <Pose18>0.000670878</Pose18>
        <Pose19>0.000670878</Pose19>
        <Pose20>0.000670878</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-5.25563e-05</Pose0>
        <Pose1>0.000751848</Pose1>
        <Pose2>-0.0336376</Pose2>
        <Pose3>0.000751848</Pose3>
        <Pose4>-1.19815e-08</Pose4>
        <Pose5>-9.19672e-06</Pose5>
        <Pose6>0.000751848</Pose6>
        <Pose7>0.000751848</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.000751848</Pose9>
        <Pose10>-3.30353e-05</Pose10>
        <Pose11>0.000751848</Pose11>
        <Pose12>0.000751848</Pose12>
        <Pose13>0.000751848</Pose13>
        <Pose14>0.000751848</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.000751848</Pose16>
        <Pose17>-3.3048e-05</Pose17>
        <Pose18>0.000751848</Pose18>
        <Pose19>0.000751848</Pose19>
        <Pose20>0.000751848</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction2>
    <newAction3>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-0.0239541</Pose0>
        <Pose1>0.00383041</Pose1>
        <Pose2>-0.0588074</Pose2>
        <Pose3>0.00383041</Pose3>
        <Pose4>-2.31506e-07</Pose4>
        <Pose5>-9.19629e-06</Pose5>
        <Pose6>0.00383041</Pose6>
        <Pose7>0.00383041</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.00383041</Pose9>
        <Pose10>-3.30386e-05</Pose10>
        <Pose11>0.00383041</Pose11>
        <Pose12>0.00383041</Pose12>
        <Pose13>0.00383041</Pose13>
        <Pose14>0.00383041</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.00383041</Pose16>
        <Pose17>-3.30506e-05</Pose17>
        <Pose18>0.00383041</Pose18>
        <Pose19>0.00383041</Pose19>
        <Pose20>0.00383041</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction3>
    <newAction4>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-0.148124</Pose0>
        <Pose1>0.0439751</Pose1>
        <Pose2>-0.0813628</Pose2>
        <Pose3>0.0439751</Pose3>
        <Pose4>-2.28428e-06</Pose4>
        <Pose5>-9.19749e-06</Pose5>
        <Pose6>0.0439751</Pose6>
        <Pose7>0.0439751</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.0439751</Pose9>
        <Pose10>-3.30354e-05</Pose10>
        <Pose11>0.0439751</Pose11>
        <Pose12>0.0439751</Pose12>
        <Pose13>0.0439751</Pose13>
        <Pose14>0.0439751</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.0439751</Pose16>
        <Pose17>-3.3032e-05</Pose17>
        <Pose18>0.0439751</Pose18>
        <Pose19>0.0439751</Pose19>
        <Pose20>0.0439751</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction4>
    <newAction5>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-0.2320</Pose0>
        <Pose1>0.0122392</Pose1>
        <Pose2>-0.0659004</Pose2>
        <Pose3>0.0122392</Pose3>
        <Pose4>-2.96984e-06</Pose4>
        <Pose5>-9.20002e-06</Pose5>
        <Pose6>0.0122392</Pose6>
        <Pose7>0.0122392</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.0122392</Pose9>
        <Pose10>-3.30135e-05</Pose10>
        <Pose11>0.0122392</Pose11>
        <Pose12>0.0122392</Pose12>
        <Pose13>0.0122392</Pose13>
        <Pose14>0.0122392</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.0122392</Pose16>
        <Pose17>-3.2997e-05</Pose17>
        <Pose18>0.0122392</Pose18>
        <Pose19>0.0122392</Pose19>
        <Pose20>0.0122392</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction5>
    <newAction6>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-0.2320</Pose0>
        <Pose1>0.0124629</Pose1>
        <Pose2>-0.0757724</Pose2>
        <Pose3>0.0124629</Pose3>
        <Pose4>0.254651</Pose4>
        <Pose5>-9.19987e-06</Pose5>
        <Pose6>0.0124629</Pose6>
        <Pose7>0.0124629</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.0124629</Pose9>
        <Pose10>-3.30112e-05</Pose10>
        <Pose11>0.0124629</Pose11>
        <Pose12>0.0124629</Pose12>
        <Pose13>0.0124629</Pose13>
        <Pose14>0.0124629</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.0124629</Pose16>
        <Pose17>-3.29958e-05</Pose17>
        <Pose18>0.0124629</Pose18>
        <Pose19>0.0124629</Pose19>
        <Pose20>0.0124629</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction6>
    <newAction7>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-0.2320</Pose0>
        <Pose1>0.0126814</Pose1>
        <Pose2>-0.083866</Pose2>
        <Pose3>0.0126814</Pose3>
        <Pose4>0.254651</Pose4>
        <Pose5>-9.20004e-06</Pose5>
        <Pose6>0.0126814</Pose6>
        <Pose7>0.0126814</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.0126814</Pose9>
        <Pose10>-1.07334</Pose10>
        <Pose11>0.0126814</Pose11>
        <Pose12>0.0126814</Pose12>
        <Pose13>0.0126814</Pose13>
        <Pose14>0.0126814</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.0126814</Pose16>
        <Pose17>-3.29975e-05</Pose17>
        <Pose18>0.0126814</Pose18>
        <Pose19>0.0126814</Pose19>
        <Pose20>0.0126814</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction7>
    <newAction8>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-0.2320</Pose0>
        <Pose1>0.0127098</Pose1>
        <Pose2>-0.0859794</Pose2>
        <Pose3>0.0127098</Pose3>
        <Pose4>0.254651</Pose4>
        <Pose5>-9.19985e-06</Pose5>
        <Pose6>0.0127098</Pose6>
        <Pose7>0.0127098</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.0127098</Pose9>
        <Pose10>-1.07334</Pose10>
        <Pose11>0.0127098</Pose11>
        <Pose12>0.0127098</Pose12>
        <Pose13>0.0127098</Pose13>
        <Pose14>0.0127098</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.0127098</Pose16>
        <Pose17>-1.0199</Pose17>
        <Pose18>0.0127098</Pose18>
        <Pose19>0.0127098</Pose19>
        <Pose20>0.0127098</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction8>
    <newAction9>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-0.2320</Pose0>
        <Pose1>0.0130046</Pose1>
        <Pose2>-0.10064</Pose2>
        <Pose3>0.0130046</Pose3>
        <Pose4>0.254651</Pose4>
        <Pose5>-9.19996e-06</Pose5>
        <Pose6>0.0130046</Pose6>
        <Pose7>0.0130046</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.0130046</Pose9>
        <Pose10>-0.635301</Pose10>
        <Pose11>0.0130046</Pose11>
        <Pose12>0.0130046</Pose12>
        <Pose13>0.0130046</Pose13>
        <Pose14>0.0130046</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.0130046</Pose16>
        <Pose17>-0.131796</Pose17>
        <Pose18>0.0130046</Pose18>
        <Pose19>0.0130046</Pose19>
        <Pose20>0.0130046</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction9>
    <newAction10>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-0.2320</Pose0>
        <Pose1>0.013122</Pose1>
        <Pose2>-0.11034</Pose2>
        <Pose3>0.013122</Pose3>
        <Pose4>0.254651</Pose4>
        <Pose5>-9.20002e-06</Pose5>
        <Pose6>0.013122</Pose6>
        <Pose7>0.013122</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.013122</Pose9>
        <Pose10>-0.216799</Pose10>
        <Pose11>0.013122</Pose11>
        <Pose12>0.013122</Pose12>
        <Pose13>0.013122</Pose13>
        <Pose14>0.013122</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.013122</Pose16>
        <Pose17>-0.737004</Pose17>
        <Pose18>0.013122</Pose18>
        <Pose19>0.013122</Pose19>
        <Pose20>0.013122</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction10>
    <newAction11>
        <Time>40</Time>
        <Count>21</Count>
        <Pose0>-0.2320</Pose0>
        <Pose1>0.013299</Pose1>
        <Pose2>-0.121921</Pose2>
        <Pose3>0.013299</Pose3>
        <Pose4>0</Pose4>
        <Pose5>-9.20005e-06</Pose5>
        <Pose6>0.013299</Pose6>
        <Pose7>0.013299</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.013299</Pose9>
        <Pose10>-0.216799</Pose10>
        <Pose11>0.013299</Pose11>
        <Pose12>0.013299</Pose12>
        <Pose13>0.013299</Pose13>
        <Pose14>0.013299</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.013299</Pose16>
        <Pose17>-0.737004</Pose17>
        <Pose18>0.013299</Pose18>
        <Pose19>0.013299</Pose19>
        <Pose20>0.013299</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction11>
    <newAction12>
        <Time>40</Time>
        <Count>21</Count>
        <Pose0>-0.2320</Pose0>
        <Pose1>0.0135445</Pose1>
        <Pose2>-0.135948</Pose2>
        <Pose3>0.0135445</Pose3>
        <Pose4>0</Pose4>
        <Pose5>-9.19999e-06</Pose5>
        <Pose6>0.0135445</Pose6>
        <Pose7>0.0135445</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.0135445</Pose9>
        <Pose10>0.00614599</Pose10>
        <Pose11>0.0135445</Pose11>
        <Pose12>0.0135445</Pose12>
        <Pose13>0.0135445</Pose13>
        <Pose14>0.0135445</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.0135445</Pose16>
        <Pose17>0.005645</Pose17>
        <Pose18>0.0135445</Pose18>
        <Pose19>0.0135445</Pose19>
        <Pose20>0.0135445</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction12>
    <newAction13>
        <Time>40</Time>
        <Count>21</Count>
        <Pose0>-0.14479</Pose0>
        <Pose1>0.0505283</Pose1>
        <Pose2>-0.0350127</Pose2>
        <Pose3>0.0505283</Pose3>
        <Pose4>0</Pose4>
        <Pose5>-9.19742e-06</Pose5>
        <Pose6>0.0505283</Pose6>
        <Pose7>0.0505283</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.0505283</Pose9>
        <Pose10>0.00597896</Pose10>
        <Pose11>0.0505283</Pose11>
        <Pose12>0.0505283</Pose12>
        <Pose13>0.0505283</Pose13>
        <Pose14>0.0505283</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.0505283</Pose16>
        <Pose17>0.00564497</Pose17>
        <Pose18>0.0505283</Pose18>
        <Pose19>0.0505283</Pose19>
        <Pose20>0.0505283</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction13>
    <newAction14>
        <Time>40</Time>
        <Count>21</Count>
        <Pose0>-0.0743355</Pose0>
        <Pose1>0.0633882</Pose1>
        <Pose2>-0.0984493</Pose2>
        <Pose3>0.0633882</Pose3>
        <Pose4>0</Pose4>
        <Pose5>-9.19658e-06</Pose5>
        <Pose6>0.0633882</Pose6>
        <Pose7>0.0633882</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.0633882</Pose9>
        <Pose10>0.00597896</Pose10>
        <Pose11>0.0633882</Pose11>
        <Pose12>0.0633882</Pose12>
        <Pose13>0.0633882</Pose13>
        <Pose14>0.0633882</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.0633882</Pose16>
        <Pose17>0.00564495</Pose17>
        <Pose18>0.0633882</Pose18>
        <Pose19>0.0633882</Pose19>
        <Pose20>0.0633882</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction14>
    <newAction15>
        <Time>40</Time>
        <Count>21</Count>
        <Pose0>-0.0372781</Pose0>
        <Pose1>0.145053</Pose1>
        <Pose2>-0.136194</Pose2>
        <Pose3>0.145053</Pose3>
        <Pose4>0</Pose4>
        <Pose5>-9.19629e-06</Pose5>
        <Pose6>0.145053</Pose6>
        <Pose7>0.145053</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.145053</Pose9>
        <Pose10>0.00597896</Pose10>
        <Pose11>0.145053</Pose11>
        <Pose12>0.145053</Pose12>
        <Pose13>0.145053</Pose13>
        <Pose14>0.145053</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.145053</Pose16>
        <Pose17>0.00564495</Pose17>
        <Pose18>0.145053</Pose18>
        <Pose19>0.145053</Pose19>
        <Pose20>0.145053</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction15>
    <newAction16>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>0.00156903</Pose0>
        <Pose1>0.133781</Pose1>
        <Pose2>-0.157975</Pose2>
        <Pose3>0.133781</Pose3>
        <Pose4>0</Pose4>
        <Pose5>-9.19579e-06</Pose5>
        <Pose6>0.133781</Pose6>
        <Pose7>0.133781</Pose7>
        <Pose8>-0.1500</Pose8>
        <Pose9>0.133781</Pose9>
        <Pose10>0.00597896</Pose10>
        <Pose11>0.133781</Pose11>
        <Pose12>0.133781</Pose12>
        <Pose13>0.133781</Pose13>
        <Pose14>0.133781</Pose14>
        <Pose15>-0.1500</Pose15>
        <Pose16>0.133781</Pose16>
        <Pose17>0.00564494</Pose17>
        <Pose18>0.133781</Pose18>
        <Pose19>0.133781</Pose19>
        <Pose20>0.133781</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction16>
</Actions>
