<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>-4.90096e-05</Pose0>
        <Pose1>0.00025835</Pose1>
        <Pose2>-0.0120873</Pose2>
        <Pose3>0.00025835</Pose3>
        <Pose4>-3.76299e-09</Pose4>
        <Pose5>-0.000991996</Pose5>
        <Pose6>0.00025835</Pose6>
        <Pose7>0.00025835</Pose7>
        <Pose8>-0.00187852</Pose8>
        <Pose9>0.00025835</Pose9>
        <Pose10>-0.000200038</Pose10>
        <Pose11>0.00025835</Pose11>
        <Pose12>0.00025835</Pose12>
        <Pose13>0.00025835</Pose13>
        <Pose14>0.00025835</Pose14>
        <Pose15>-0.000189482</Pose15>
        <Pose16>0.00025835</Pose16>
        <Pose17>-0.000200052</Pose17>
        <Pose18>0.00025835</Pose18>
        <Pose19>0.00025835</Pose19>
        <Pose20>0.00025835</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-5.29254e-05</Pose0>
        <Pose1>0.00255016</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>0.00255016</Pose3>
        <Pose4>-7.74784e-09</Pose4>
        <Pose5>-0.01082</Pose5>
        <Pose6>0.00255016</Pose6>
        <Pose7>0.00255016</Pose7>
        <Pose8>-0.167281</Pose8>
        <Pose9>0.00255016</Pose9>
        <Pose10>-0.000200038</Pose10>
        <Pose11>0.00255016</Pose11>
        <Pose12>0.00255016</Pose12>
        <Pose13>0.00255016</Pose13>
        <Pose14>0.00255016</Pose14>
        <Pose15>-0.0188007</Pose15>
        <Pose16>0.00255016</Pose16>
        <Pose17>-0.000200052</Pose17>
        <Pose18>0.00255016</Pose18>
        <Pose19>0.00255016</Pose19>
        <Pose20>0.00255016</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-4.92447e-05</Pose0>
        <Pose1>0.00293322</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>0.00293322</Pose3>
        <Pose4>-2.8079e-08</Pose4>
        <Pose5>-0.01082</Pose5>
        <Pose6>0.00293322</Pose6>
        <Pose7>0.00293322</Pose7>
        <Pose8>-0.16728</Pose8>
        <Pose9>0.00293322</Pose9>
        <Pose10>-0.000200039</Pose10>
        <Pose11>0.00293322</Pose11>
        <Pose12>0.00293322</Pose12>
        <Pose13>0.00293322</Pose13>
        <Pose14>0.00293322</Pose14>
        <Pose15>-0.16356</Pose15>
        <Pose16>0.00293322</Pose16>
        <Pose17>-0.000200053</Pose17>
        <Pose18>0.00293322</Pose18>
        <Pose19>0.00293322</Pose19>
        <Pose20>0.00293322</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction2>
    <newAction3>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-5.40404e-05</Pose0>
        <Pose1>0.003134</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>0.003134</Pose3>
        <Pose4>-2.57895e-08</Pose4>
        <Pose5>-0.01082</Pose5>
        <Pose6>0.003134</Pose6>
        <Pose7>0.003134</Pose7>
        <Pose8>-0.167282</Pose8>
        <Pose9>0.003134</Pose9>
        <Pose10>-0.000200033</Pose10>
        <Pose11>0.003134</Pose11>
        <Pose12>0.003134</Pose12>
        <Pose13>0.003134</Pose13>
        <Pose14>0.003134</Pose14>
        <Pose15>-0.163559</Pose15>
        <Pose16>0.003134</Pose16>
        <Pose17>-0.000200051</Pose17>
        <Pose18>0.003134</Pose18>
        <Pose19>0.003134</Pose19>
        <Pose20>0.003134</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction3>
    <newAction4>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>-0.234833</Pose0>
        <Pose1>-0.0495862</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>-0.0495862</Pose3>
        <Pose4>-2.99259e-06</Pose4>
        <Pose5>-0.01082</Pose5>
        <Pose6>-0.0495862</Pose6>
        <Pose7>-0.0495862</Pose7>
        <Pose8>-0.16721</Pose8>
        <Pose9>-0.0495862</Pose9>
        <Pose10>-0.000200016</Pose10>
        <Pose11>-0.0495862</Pose11>
        <Pose12>-0.0495862</Pose12>
        <Pose13>-0.0495862</Pose13>
        <Pose14>-0.0495862</Pose14>
        <Pose15>-0.163491</Pose15>
        <Pose16>-0.0495862</Pose16>
        <Pose17>-0.0002</Pose17>
        <Pose18>-0.0495862</Pose18>
        <Pose19>-0.0495862</Pose19>
        <Pose20>-0.0495862</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction4>
    <newAction5>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.234826</Pose0>
        <Pose1>-0.0495324</Pose1>
        <Pose2>0.290161</Pose2>
        <Pose3>-0.0495324</Pose3>
        <Pose4>-3.12151e-06</Pose4>
        <Pose5>-0.01082</Pose5>
        <Pose6>-0.0495324</Pose6>
        <Pose7>-0.0495324</Pose7>
        <Pose8>-0.167206</Pose8>
        <Pose9>-0.0495324</Pose9>
        <Pose10>-0.000200016</Pose10>
        <Pose11>-0.0495324</Pose11>
        <Pose12>-0.0495324</Pose12>
        <Pose13>-0.0495324</Pose13>
        <Pose14>-0.0495324</Pose14>
        <Pose15>-0.163488</Pose15>
        <Pose16>-0.0495324</Pose16>
        <Pose17>-0.0002</Pose17>
        <Pose18>-0.0495324</Pose18>
        <Pose19>-0.0495324</Pose19>
        <Pose20>-0.0495324</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction5>
    <newAction6>
        <Time>15</Time>
        <Count>21</Count>
        <Pose0>-0.234837</Pose0>
        <Pose1>-0.049336</Pose1>
        <Pose2>0.290161</Pose2>
        <Pose3>-0.049336</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>-0.01082</Pose5>
        <Pose6>-0.049336</Pose6>
        <Pose7>-0.049336</Pose7>
        <Pose8>-0.167214</Pose8>
        <Pose9>-0.049336</Pose9>
        <Pose10>-0.000200016</Pose10>
        <Pose11>-0.049336</Pose11>
        <Pose12>-0.049336</Pose12>
        <Pose13>-0.049336</Pose13>
        <Pose14>-0.049336</Pose14>
        <Pose15>-0.163496</Pose15>
        <Pose16>-0.049336</Pose16>
        <Pose17>-0.000200001</Pose17>
        <Pose18>-0.049336</Pose18>
        <Pose19>-0.049336</Pose19>
        <Pose20>-0.049336</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction6>
    <newAction7>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>-0.234832</Pose0>
        <Pose1>-0.0490505</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>-0.0490505</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>-0.42032</Pose5>
        <Pose6>-0.0490505</Pose6>
        <Pose7>-0.0490505</Pose7>
        <Pose8>-0.167212</Pose8>
        <Pose9>-0.0490505</Pose9>
        <Pose10>-0.000200016</Pose10>
        <Pose11>-0.0490505</Pose11>
        <Pose12>-0.0490505</Pose12>
        <Pose13>-0.0490505</Pose13>
        <Pose14>-0.0490505</Pose14>
        <Pose15>-0.163494</Pose15>
        <Pose16>-0.0490505</Pose16>
        <Pose17>-0.0002</Pose17>
        <Pose18>-0.0490505</Pose18>
        <Pose19>-0.0490505</Pose19>
        <Pose20>-0.0490505</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction7>
    <newAction8>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-0.234834</Pose0>
        <Pose1>-0.0489978</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>-0.0489978</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>-0.42032</Pose5>
        <Pose6>-0.0489978</Pose6>
        <Pose7>-0.0489978</Pose7>
        <Pose8>-0.167212</Pose8>
        <Pose9>-0.0489978</Pose9>
        <Pose10>-0.000200016</Pose10>
        <Pose11>-0.0489978</Pose11>
        <Pose12>-0.0489978</Pose12>
        <Pose13>-0.0489978</Pose13>
        <Pose14>-0.0489978</Pose14>
        <Pose15>-0.163494</Pose15>
        <Pose16>-0.0489978</Pose16>
        <Pose17>-0.000200001</Pose17>
        <Pose18>-0.0489978</Pose18>
        <Pose19>-0.0489978</Pose19>
        <Pose20>-0.0489978</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction8>
    <newAction9>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>-0.234831</Pose0>
        <Pose1>-0.0488685</Pose1>
        <Pose2>0.290168</Pose2>
        <Pose3>-0.0488685</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>0.43144</Pose5>
        <Pose6>-0.0488685</Pose6>
        <Pose7>-0.0488685</Pose7>
        <Pose8>-0.167214</Pose8>
        <Pose9>-0.0488685</Pose9>
        <Pose10>-0.000200014</Pose10>
        <Pose11>-0.0488685</Pose11>
        <Pose12>-0.0488685</Pose12>
        <Pose13>-0.0488685</Pose13>
        <Pose14>-0.0488685</Pose14>
        <Pose15>-0.163496</Pose15>
        <Pose16>-0.0488685</Pose16>
        <Pose17>-0.000199999</Pose17>
        <Pose18>-0.0488685</Pose18>
        <Pose19>-0.0488685</Pose19>
        <Pose20>-0.0488685</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction9>
    <newAction10>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-0.234827</Pose0>
        <Pose1>-0.048835</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>-0.048835</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>0.43144</Pose5>
        <Pose6>-0.048835</Pose6>
        <Pose7>-0.048835</Pose7>
        <Pose8>-0.167215</Pose8>
        <Pose9>-0.048835</Pose9>
        <Pose10>-0.000200015</Pose10>
        <Pose11>-0.048835</Pose11>
        <Pose12>-0.048835</Pose12>
        <Pose13>-0.048835</Pose13>
        <Pose14>-0.048835</Pose14>
        <Pose15>-0.163497</Pose15>
        <Pose16>-0.048835</Pose16>
        <Pose17>-0.0002</Pose17>
        <Pose18>-0.048835</Pose18>
        <Pose19>-0.048835</Pose19>
        <Pose20>-0.048835</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction10>
    <newAction11>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>-0.234829</Pose0>
        <Pose1>-0.0487389</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>-0.0487389</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0487389</Pose6>
        <Pose7>-0.0487389</Pose7>
        <Pose8>-0.167215</Pose8>
        <Pose9>-0.0487389</Pose9>
        <Pose10>-0.000200015</Pose10>
        <Pose11>-0.0487389</Pose11>
        <Pose12>-0.0487389</Pose12>
        <Pose13>-0.0487389</Pose13>
        <Pose14>-0.0487389</Pose14>
        <Pose15>-0.163496</Pose15>
        <Pose16>-0.0487389</Pose16>
        <Pose17>-0.0002</Pose17>
        <Pose18>-0.0487389</Pose18>
        <Pose19>-0.0487389</Pose19>
        <Pose20>-0.0487389</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction11>
    <newAction12>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.234833</Pose0>
        <Pose1>-0.0485012</Pose1>
        <Pose2>0.290161</Pose2>
        <Pose3>-0.0485012</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0485012</Pose6>
        <Pose7>-0.0485012</Pose7>
        <Pose8>-0.167216</Pose8>
        <Pose9>-0.0485012</Pose9>
        <Pose10>-0.3008</Pose10>
        <Pose11>-0.0485012</Pose11>
        <Pose12>-0.0485012</Pose12>
        <Pose13>-0.0485012</Pose13>
        <Pose14>-0.0485012</Pose14>
        <Pose15>-0.163498</Pose15>
        <Pose16>-0.0485012</Pose16>
        <Pose17>-0.000200001</Pose17>
        <Pose18>-0.0485012</Pose18>
        <Pose19>-0.0485012</Pose19>
        <Pose20>-0.0485012</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction12>
    <newAction13>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.234821</Pose0>
        <Pose1>-0.0484782</Pose1>
        <Pose2>0.290153</Pose2>
        <Pose3>-0.0484782</Pose3>
        <Pose4>0.188398</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0484782</Pose6>
        <Pose7>-0.0484782</Pose7>
        <Pose8>-0.167223</Pose8>
        <Pose9>-0.0484782</Pose9>
        <Pose10>-0.3008</Pose10>
        <Pose11>-0.0484782</Pose11>
        <Pose12>-0.0484782</Pose12>
        <Pose13>-0.0484782</Pose13>
        <Pose14>-0.0484782</Pose14>
        <Pose15>-0.163505</Pose15>
        <Pose16>-0.0484782</Pose16>
        <Pose17>-0.000200002</Pose17>
        <Pose18>-0.0484782</Pose18>
        <Pose19>-0.0484782</Pose19>
        <Pose20>-0.0484782</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction13>
    <newAction14>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.234826</Pose0>
        <Pose1>-0.0484006</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>-0.0484006</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0484006</Pose6>
        <Pose7>-0.0484006</Pose7>
        <Pose8>-0.167206</Pose8>
        <Pose9>-0.0484006</Pose9>
        <Pose10>-0.000200016</Pose10>
        <Pose11>-0.0484006</Pose11>
        <Pose12>-0.0484006</Pose12>
        <Pose13>-0.0484006</Pose13>
        <Pose14>-0.0484006</Pose14>
        <Pose15>-0.163487</Pose15>
        <Pose16>-0.0484006</Pose16>
        <Pose17>-0.0002</Pose17>
        <Pose18>-0.0484006</Pose18>
        <Pose19>-0.0484006</Pose19>
        <Pose20>-0.0484006</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction14>
    <newAction15>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.234826</Pose0>
        <Pose1>-0.0482961</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>-0.0482961</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0482961</Pose6>
        <Pose7>-0.0482961</Pose7>
        <Pose8>-0.167215</Pose8>
        <Pose9>-0.0482961</Pose9>
        <Pose10>-0.000200015</Pose10>
        <Pose11>-0.0482961</Pose11>
        <Pose12>-0.0482961</Pose12>
        <Pose13>-0.0482961</Pose13>
        <Pose14>-0.0482961</Pose14>
        <Pose15>-0.163497</Pose15>
        <Pose16>-0.0482961</Pose16>
        <Pose17>-0.3008</Pose17>
        <Pose18>-0.0482961</Pose18>
        <Pose19>-0.0482961</Pose19>
        <Pose20>-0.0482961</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction15>
    <newAction16>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.234828</Pose0>
        <Pose1>-0.0482739</Pose1>
        <Pose2>0.29016</Pose2>
        <Pose3>-0.0482739</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0482739</Pose6>
        <Pose7>-0.0482739</Pose7>
        <Pose8>-0.167212</Pose8>
        <Pose9>-0.0482739</Pose9>
        <Pose10>-0.000200015</Pose10>
        <Pose11>-0.0482739</Pose11>
        <Pose12>-0.0482739</Pose12>
        <Pose13>-0.0482739</Pose13>
        <Pose14>-0.0482739</Pose14>
        <Pose15>-0.163494</Pose15>
        <Pose16>-0.0482739</Pose16>
        <Pose17>-0.3008</Pose17>
        <Pose18>-0.0482739</Pose18>
        <Pose19>-0.0482739</Pose19>
        <Pose20>-0.0482739</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction16>
    <newAction17>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.234831</Pose0>
        <Pose1>-0.0482156</Pose1>
        <Pose2>0.290163</Pose2>
        <Pose3>-0.0482156</Pose3>
        <Pose4>0.188397</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0482156</Pose6>
        <Pose7>-0.0482156</Pose7>
        <Pose8>-0.167211</Pose8>
        <Pose9>-0.0482156</Pose9>
        <Pose10>-0.000200015</Pose10>
        <Pose11>-0.0482156</Pose11>
        <Pose12>-0.0482156</Pose12>
        <Pose13>-0.0482156</Pose13>
        <Pose14>-0.0482156</Pose14>
        <Pose15>-0.163493</Pose15>
        <Pose16>-0.0482156</Pose16>
        <Pose17>-0.0002</Pose17>
        <Pose18>-0.0482156</Pose18>
        <Pose19>-0.0482156</Pose19>
        <Pose20>-0.0482156</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction17>
    <newAction18>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.234826</Pose0>
        <Pose1>-0.0464788</Pose1>
        <Pose2>0.27634</Pose2>
        <Pose3>-0.0464788</Pose3>
        <Pose4>0.156997</Pose4>
        <Pose5>0.44782</Pose5>
        <Pose6>-0.0464788</Pose6>
        <Pose7>-0.0464788</Pose7>
        <Pose8>-0.167214</Pose8>
        <Pose9>-0.0464788</Pose9>
        <Pose10>-0.0169</Pose10>
        <Pose11>-0.0464788</Pose11>
        <Pose12>-0.0464788</Pose12>
        <Pose13>-0.0464788</Pose13>
        <Pose14>-0.0464788</Pose14>
        <Pose15>-0.163496</Pose15>
        <Pose16>-0.0464788</Pose16>
        <Pose17>-0.3008</Pose17>
        <Pose18>-0.0464788</Pose18>
        <Pose19>-0.0464788</Pose19>
        <Pose20>-0.0464788</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction18>
    <newAction19>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.234835</Pose0>
        <Pose1>-0.0464591</Pose1>
        <Pose2>0.27634</Pose2>
        <Pose3>-0.0464591</Pose3>
        <Pose4>0.156997</Pose4>
        <Pose5>0.44782</Pose5>
        <Pose6>-0.0464591</Pose6>
        <Pose7>-0.0464591</Pose7>
        <Pose8>-0.16721</Pose8>
        <Pose9>-0.0464591</Pose9>
        <Pose10>-0.0169</Pose10>
        <Pose11>-0.0464591</Pose11>
        <Pose12>-0.0464591</Pose12>
        <Pose13>-0.0464591</Pose13>
        <Pose14>-0.0464591</Pose14>
        <Pose15>-0.163492</Pose15>
        <Pose16>-0.0464591</Pose16>
        <Pose17>-0.3008</Pose17>
        <Pose18>-0.0464591</Pose18>
        <Pose19>-0.0464591</Pose19>
        <Pose20>-0.0464591</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction19>
    <newAction20>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.234722</Pose0>
        <Pose1>-0.0463498</Pose1>
        <Pose2>0.290104</Pose2>
        <Pose3>-0.0463498</Pose3>
        <Pose4>0.188393</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0463498</Pose6>
        <Pose7>-0.0463498</Pose7>
        <Pose8>-0.167106</Pose8>
        <Pose9>-0.0463498</Pose9>
        <Pose10>-0.000200031</Pose10>
        <Pose11>-0.0463498</Pose11>
        <Pose12>-0.0463498</Pose12>
        <Pose13>-0.0463498</Pose13>
        <Pose14>-0.0463498</Pose14>
        <Pose15>-0.163429</Pose15>
        <Pose16>-0.0463498</Pose16>
        <Pose17>-0.000200001</Pose17>
        <Pose18>-0.0463498</Pose18>
        <Pose19>-0.0463498</Pose19>
        <Pose20>-0.0463498</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction20>
    <newAction21>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.234726</Pose0>
        <Pose1>-0.0463193</Pose1>
        <Pose2>0.290111</Pose2>
        <Pose3>-0.0463193</Pose3>
        <Pose4>0.188394</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0463193</Pose6>
        <Pose7>-0.0463193</Pose7>
        <Pose8>-0.167111</Pose8>
        <Pose9>-0.0463193</Pose9>
        <Pose10>-0.000200028</Pose10>
        <Pose11>-0.0463193</Pose11>
        <Pose12>-0.0463193</Pose12>
        <Pose13>-0.0463193</Pose13>
        <Pose14>-0.0463193</Pose14>
        <Pose15>-0.163434</Pose15>
        <Pose16>-0.0463193</Pose16>
        <Pose17>-0.000199999</Pose17>
        <Pose18>-0.0463193</Pose18>
        <Pose19>-0.0463193</Pose19>
        <Pose20>-0.0463193</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction21>
    <newAction22>
        <Time>25</Time>
        <Count>21</Count>
        <Pose0>-0.234829</Pose0>
        <Pose1>-0.0458626</Pose1>
        <Pose2>0.27634</Pose2>
        <Pose3>-0.0458626</Pose3>
        <Pose4>0.156997</Pose4>
        <Pose5>-0.45308</Pose5>
        <Pose6>-0.0458626</Pose6>
        <Pose7>-0.0458626</Pose7>
        <Pose8>-0.16721</Pose8>
        <Pose9>-0.0458626</Pose9>
        <Pose10>-0.3509</Pose10>
        <Pose11>-0.0458626</Pose11>
        <Pose12>-0.0458626</Pose12>
        <Pose13>-0.0458626</Pose13>
        <Pose14>-0.0458626</Pose14>
        <Pose15>-0.163492</Pose15>
        <Pose16>-0.0458626</Pose16>
        <Pose17>-0.0002</Pose17>
        <Pose18>-0.0458626</Pose18>
        <Pose19>-0.0458626</Pose19>
        <Pose20>-0.0458626</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction22>
    <newAction23>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.234821</Pose0>
        <Pose1>-0.0458467</Pose1>
        <Pose2>0.276339</Pose2>
        <Pose3>-0.0458467</Pose3>
        <Pose4>0.156997</Pose4>
        <Pose5>-0.45308</Pose5>
        <Pose6>-0.0458467</Pose6>
        <Pose7>-0.0458467</Pose7>
        <Pose8>-0.167216</Pose8>
        <Pose9>-0.0458467</Pose9>
        <Pose10>-0.3509</Pose10>
        <Pose11>-0.0458467</Pose11>
        <Pose12>-0.0458467</Pose12>
        <Pose13>-0.0458467</Pose13>
        <Pose14>-0.0458467</Pose14>
        <Pose15>-0.163498</Pose15>
        <Pose16>-0.0458467</Pose16>
        <Pose17>-0.0002</Pose17>
        <Pose18>-0.0458467</Pose18>
        <Pose19>-0.0458467</Pose19>
        <Pose20>-0.0458467</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction23>
    <newAction24>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.234607</Pose0>
        <Pose1>-0.0456297</Pose1>
        <Pose2>0.290051</Pose2>
        <Pose3>-0.0456297</Pose3>
        <Pose4>0.188391</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.0456297</Pose6>
        <Pose7>-0.0456297</Pose7>
        <Pose8>-0.167004</Pose8>
        <Pose9>-0.0456297</Pose9>
        <Pose10>-0.000200044</Pose10>
        <Pose11>-0.0456297</Pose11>
        <Pose12>-0.0456297</Pose12>
        <Pose13>-0.0456297</Pose13>
        <Pose14>-0.0456297</Pose14>
        <Pose15>-0.163369</Pose15>
        <Pose16>-0.0456297</Pose16>
        <Pose17>-0.000199999</Pose17>
        <Pose18>-0.0456297</Pose18>
        <Pose19>-0.0456297</Pose19>
        <Pose20>-0.0456297</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction24>
    <newAction25>
        <Time>30</Time>
        <Count>21</Count>
        <Pose0>1.82107e-05</Pose0>
        <Pose1>-0.186535</Pose1>
        <Pose2>0.276343</Pose2>
        <Pose3>-0.186535</Pose3>
        <Pose4>0.157</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.186535</Pose6>
        <Pose7>-0.186535</Pose7>
        <Pose8>-0.167282</Pose8>
        <Pose9>-0.186535</Pose9>
        <Pose10>-0.000200037</Pose10>
        <Pose11>-0.186535</Pose11>
        <Pose12>-0.186535</Pose12>
        <Pose13>-0.186535</Pose13>
        <Pose14>-0.186535</Pose14>
        <Pose15>-0.163561</Pose15>
        <Pose16>-0.186535</Pose16>
        <Pose17>-0.000200047</Pose17>
        <Pose18>-0.186535</Pose18>
        <Pose19>-0.186535</Pose19>
        <Pose20>-0.186535</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction25>
    <newAction26>
        <Time>20</Time>
        <Count>21</Count>
        <Pose0>3.07466e-05</Pose0>
        <Pose1>-0.187037</Pose1>
        <Pose2>0.276285</Pose2>
        <Pose3>-0.187037</Pose3>
        <Pose4>0.157</Pose4>
        <Pose5>0.00556001</Pose5>
        <Pose6>-0.187037</Pose6>
        <Pose7>-0.187037</Pose7>
        <Pose8>-0.00187124</Pose8>
        <Pose9>-0.187037</Pose9>
        <Pose10>-0.00020008</Pose10>
        <Pose11>-0.187037</Pose11>
        <Pose12>-0.187037</Pose12>
        <Pose13>-0.187037</Pose13>
        <Pose14>-0.187037</Pose14>
        <Pose15>-0.163562</Pose15>
        <Pose16>-0.187037</Pose16>
        <Pose17>-0.000200098</Pose17>
        <Pose18>-0.187037</Pose18>
        <Pose19>-0.187037</Pose19>
        <Pose20>-0.187037</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction26>
    <newAction27>
        <Time>20</Time>
        <Count>21</Count>
        <Pose0>1.66615e-05</Pose0>
        <Pose1>-0.187219</Pose1>
        <Pose2>0.262523</Pose2>
        <Pose3>-0.187219</Pose3>
        <Pose4>0.1256</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.187219</Pose6>
        <Pose7>-0.187219</Pose7>
        <Pose8>-0.00187401</Pose8>
        <Pose9>-0.187219</Pose9>
        <Pose10>-0.000200035</Pose10>
        <Pose11>-0.187219</Pose11>
        <Pose12>-0.187219</Pose12>
        <Pose13>-0.187219</Pose13>
        <Pose14>-0.187219</Pose14>
        <Pose15>0.00187578</Pose15>
        <Pose16>-0.187219</Pose16>
        <Pose17>-0.000200057</Pose17>
        <Pose18>-0.187219</Pose18>
        <Pose19>-0.187219</Pose19>
        <Pose20>-0.187219</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction27>
    <newAction28>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>1.79918e-05</Pose0>
        <Pose1>-0.187247</Pose1>
        <Pose2>0.262523</Pose2>
        <Pose3>-0.187247</Pose3>
        <Pose4>-0.2512</Pose4>
        <Pose5>0.00556</Pose5>
        <Pose6>-0.187247</Pose6>
        <Pose7>-0.187247</Pose7>
        <Pose8>-0.00187799</Pose8>
        <Pose9>-0.187247</Pose9>
        <Pose10>-0.000200038</Pose10>
        <Pose11>-0.187247</Pose11>
        <Pose12>-0.187247</Pose12>
        <Pose13>-0.187247</Pose13>
        <Pose14>-0.187247</Pose14>
        <Pose15>0.00187972</Pose15>
        <Pose16>-0.187247</Pose16>
        <Pose17>-0.000200052</Pose17>
        <Pose18>-0.187247</Pose18>
        <Pose19>-0.187247</Pose19>
        <Pose20>-0.187247</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction28>
    <newAction29>
        <Time>10</Time>
        <Count>21</Count>
        <Pose0>-4.38271e-05</Pose0>
        <Pose1>0.000247082</Pose1>
        <Pose2>-0.0110722</Pose2>
        <Pose3>0.000247082</Pose3>
        <Pose4>-3.05259e-08</Pose4>
        <Pose5>-0.000991996</Pose5>
        <Pose6>0.000247082</Pose6>
        <Pose7>0.000247082</Pose7>
        <Pose8>-0.0018764</Pose8>
        <Pose9>0.000247082</Pose9>
        <Pose10>-0.000200039</Pose10>
        <Pose11>0.000247082</Pose11>
        <Pose12>0.000247082</Pose12>
        <Pose13>0.000247082</Pose13>
        <Pose14>0.000247082</Pose14>
        <Pose15>-0.000188416</Pose15>
        <Pose16>0.000247082</Pose16>
        <Pose17>-0.000200053</Pose17>
        <Pose18>0.000247082</Pose18>
        <Pose19>0.000247082</Pose19>
        <Pose20>0.000247082</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction29>
</Actions>
