<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>20</Time>
        <Count>21</Count>
        <Pose0>2.21694</Pose0>
        <Pose1>2.21694</Pose1>
        <Pose2>2.21694</Pose2>
        <Pose3>2.21694</Pose3>
        <Pose4>2.21694</Pose4>
        <Pose5>2.21694</Pose5>
        <Pose6>2.21694</Pose6>
        <Pose7>1.40117</Pose7>
        <Pose8>0.453077</Pose8>
        <Pose9>2.21694</Pose9>
        <Pose10>-0.000192258</Pose10>
        <Pose11>2.21694</Pose11>
        <Pose12>2.21694</Pose12>
        <Pose13>2.21694</Pose13>
        <Pose14>1.62718</Pose14>
        <Pose15>-0.701241</Pose15>
        <Pose16>2.21694</Pose16>
        <Pose17>-1.4364</Pose17>
        <Pose18>2.21694</Pose18>
        <Pose19>2.21694</Pose19>
        <Pose20>2.21694</Pose20>
        <Count>10</Count>
        <HandPose0>0.014</HandPose0>
        <HandPose1>0.027</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0.027</HandPose4>
        <HandPose5>0.026</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0.024</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>20</Time>
        <Count>21</Count>
        <Pose0>3.04819</Pose0>
        <Pose1>3.04819</Pose1>
        <Pose2>3.04819</Pose2>
        <Pose3>3.04819</Pose3>
        <Pose4>3.04819</Pose4>
        <Pose5>3.04819</Pose5>
        <Pose6>3.04819</Pose6>
        <Pose7>1.67237</Pose7>
        <Pose8>-0.188001</Pose8>
        <Pose9>3.04819</Pose9>
        <Pose10>-1.1358</Pose10>
        <Pose11>3.04819</Pose11>
        <Pose12>3.04819</Pose12>
        <Pose13>3.04819</Pose13>
        <Pose14>1.44637</Pose14>
        <Pose15>0.187999</Pose15>
        <Pose16>3.04819</Pose16>
        <Pose17>-1.1859</Pose17>
        <Pose18>3.04819</Pose18>
        <Pose19>3.04819</Pose19>
        <Pose20>3.04819</Pose20>
        <Count>10</Count>
        <HandPose0>0.017</HandPose0>
        <HandPose1>0.025</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0.02</HandPose4>
        <HandPose5>0.015</HandPose5>
        <HandPose6>0.024</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0.019</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
</Actions>
