<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>0.165838</Pose0>
        <Pose1>0.4082</Pose1>
        <Pose2>1.7643e-05</Pose2>
        <Pose3>1.90735e-05</Pose3>
        <Pose4>-7.14011e-05</Pose4>
        <Pose5>-0.0108522</Pose5>
        <Pose6>3.05176e-05</Pose6>
        <Pose7>5.00679e-05</Pose7>
        <Pose8>-0.00189241</Pose8>
        <Pose9>-2.12991e-05</Pose9>
        <Pose10>-0.96874</Pose10>
        <Pose11>7.39098e-05</Pose11>
        <Pose12>-0.0140198</Pose12>
        <Pose13>-0.0139563</Pose13>
        <Pose14>-4.73547e-05</Pose14>
        <Pose15>-0.00188205</Pose15>
        <Pose16>9.05991e-06</Pose16>
        <Pose17>-0.000215475</Pose17>
        <Pose18>-9.29606e-06</Pose18>
        <Pose19>-0.0140026</Pose19>
        <Pose20>-0.0139753</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0.744</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
    </newAction0>
    <newAction1>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>0.165837</Pose0>
        <Pose1>0.4082</Pose1>
        <Pose2>-2.65575e-06</Pose2>
        <Pose3>4.24385e-05</Pose3>
        <Pose4>2.67029e-05</Pose4>
        <Pose5>-0.0107821</Pose5>
        <Pose6>-9.42254e-05</Pose6>
        <Pose7>1.71661e-05</Pose7>
        <Pose8>-0.00188521</Pose8>
        <Pose9>3.14713e-05</Pose9>
        <Pose10>-0.968697</Pose10>
        <Pose11>-4.98264e-05</Pose11>
        <Pose12>-0.014025</Pose12>
        <Pose13>-0.0139793</Pose13>
        <Pose14>-1.70148e-05</Pose14>
        <Pose15>-0.00188318</Pose15>
        <Pose16>9.05991e-06</Pose16>
        <Pose17>-0.000214976</Pose17>
        <Pose18>-1.70075e-05</Pose18>
        <Pose19>-0.0140032</Pose19>
        <Pose20>-0.0139741</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
    </newAction1>
    <newAction2>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>0.165842</Pose0>
        <Pose1>0.4082</Pose1>
        <Pose2>-3.44265e-06</Pose2>
        <Pose3>-3.76385e-05</Pose3>
        <Pose4>6.4373e-05</Pose4>
        <Pose5>-0.0108324</Pose5>
        <Pose6>5.10216e-05</Pose6>
        <Pose7>3.57628e-05</Pose7>
        <Pose8>-0.00188741</Pose8>
        <Pose9>-1.7505e-05</Pose9>
        <Pose10>-0.968671</Pose10>
        <Pose11>3.76701e-05</Pose11>
        <Pose12>-0.0140235</Pose12>
        <Pose13>-0.013916</Pose13>
        <Pose14>-1.01949e-05</Pose14>
        <Pose15>-0.00188246</Pose15>
        <Pose16>7.15256e-06</Pose16>
        <Pose17>-0.00020629</Pose17>
        <Pose18>-7.92111e-06</Pose18>
        <Pose19>-0.0140039</Pose19>
        <Pose20>-0.0139793</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.75</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
    </newAction2>
</Actions>
