<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.0690989</Pose0>
        <Pose1>-0.0313998</Pose1>
        <Pose2>0.138202</Pose2>
        <Pose3>-4.13883e-05</Pose3>
        <Pose4>3.38554e-05</Pose4>
        <Pose5>-0.0107944</Pose5>
        <Pose6>-0.025201</Pose6>
        <Pose7>0.406808</Pose7>
        <Pose8>0.328999</Pose8>
        <Pose9>1.81198e-05</Pose9>
        <Pose10>-0.000260739</Pose10>
        <Pose11>4.43459e-05</Pose11>
        <Pose12>-0.036017</Pose12>
        <Pose13>-0.0303534</Pose13>
        <Pose14>0.4972</Pose14>
        <Pose15>-0.187995</Pose15>
        <Pose16>1.00136e-05</Pose16>
        <Pose17>-0.0169795</Pose17>
        <Pose18>2.00272e-05</Pose18>
        <Pose19>-0.0140114</Pose19>
        <Pose20>-0.0303339</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>1</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>4.76837e-06</Pose0>
        <Pose1>4.76837e-07</Pose1>
        <Pose2>9.53674e-07</Pose2>
        <Pose3>3.33786e-06</Pose3>
        <Pose4>-1.14741e-05</Pose4>
        <Pose5>-0.0108198</Pose5>
        <Pose6>9.53674e-07</Pose6>
        <Pose7>-9.87195e-07</Pose7>
        <Pose8>-0.00188035</Pose8>
        <Pose9>9.53674e-07</Pose9>
        <Pose10>-0.000200423</Pose10>
        <Pose11>6.19888e-06</Pose11>
        <Pose12>-0.0139999</Pose12>
        <Pose13>-0.01398</Pose13>
        <Pose14>5.24521e-06</Pose14>
        <Pose15>-0.00188068</Pose15>
        <Pose16>3.8147e-06</Pose16>
        <Pose17>-0.00020043</Pose17>
        <Pose18>1.66893e-05</Pose18>
        <Pose19>-0.0140009</Pose19>
        <Pose20>-0.0139801</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.165844</Pose0>
        <Pose1>0.0628004</Pose1>
        <Pose2>0.373138</Pose2>
        <Pose3>1.66893e-05</Pose3>
        <Pose4>-0.0314022</Pose4>
        <Pose5>-0.0108738</Pose5>
        <Pose6>2.00272e-05</Pose6>
        <Pose7>-0.0452022</Pose7>
        <Pose8>-0.0225608</Pose8>
        <Pose9>-2.50078e-06</Pose9>
        <Pose10>-0.0168996</Pose10>
        <Pose11>6.19888e-06</Pose11>
        <Pose12>-0.0140022</Pose12>
        <Pose13>-0.0139783</Pose13>
        <Pose14>3.8147e-06</Pose14>
        <Pose15>-0.022559</Pose15>
        <Pose16>8.58307e-06</Pose16>
        <Pose17>-0.0169107</Pose17>
        <Pose18>6.67572e-06</Pose18>
        <Pose19>-0.0360016</Pose19>
        <Pose20>-0.030326</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>2</OmniVel2>
    </newAction2>
    <newAction3>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>4.76837e-06</Pose0>
        <Pose1>-4.94688e-07</Pose1>
        <Pose2>1.43051e-06</Pose2>
        <Pose3>-1.73322e-06</Pose3>
        <Pose4>4.29153e-06</Pose4>
        <Pose5>-0.010818</Pose5>
        <Pose6>-3.54212e-06</Pose6>
        <Pose7>3.8147e-06</Pose7>
        <Pose8>-0.00188294</Pose8>
        <Pose9>-3.88844e-06</Pose9>
        <Pose10>-0.000199505</Pose10>
        <Pose11>-9.42724e-06</Pose11>
        <Pose12>-0.0140038</Pose12>
        <Pose13>-0.0139811</Pose13>
        <Pose14>-3.55399e-06</Pose14>
        <Pose15>-0.00187919</Pose15>
        <Pose16>3.8147e-06</Pose16>
        <Pose17>-0.000199803</Pose17>
        <Pose18>9.53674e-06</Pose18>
        <Pose19>-0.0139983</Pose19>
        <Pose20>-0.0139804</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction3>
</Actions>
