<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>2.86102e-06</Pose0>
        <Pose1>7.62939e-06</Pose1>
        <Pose2>3.52859e-05</Pose2>
        <Pose3>-1.90352e-05</Pose3>
        <Pose4>-1.1304</Pose4>
        <Pose5>-0.0108137</Pose5>
        <Pose6>-1.13231e-05</Pose6>
        <Pose7>-0.994399</Pose7>
        <Pose8>0.556468</Pose8>
        <Pose9>-1.19323</Pose9>
        <Pose10>-1.25263</Pose10>
        <Pose11>-2.94282e-05</Pose11>
        <Pose12>-0.0139465</Pose12>
        <Pose13>-0.569522</Pose13>
        <Pose14>-0.99438</Pose14>
        <Pose15>-0.515116</Pose15>
        <Pose16>0.565201</Pose16>
        <Pose17>-1.4364</Pose17>
        <Pose18>-1.256</Pose18>
        <Pose19>-0.0139666</Pose19>
        <Pose20>0.388064</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-6.38361e-06</Pose0>
        <Pose1>-0.0313998</Pose1>
        <Pose2>1.43051e-05</Pose2>
        <Pose3>3.33786e-06</Pose3>
        <Pose4>1.22459</Pose4>
        <Pose5>-0.0271958</Pose5>
        <Pose6>-0.0251772</Pose6>
        <Pose7>-1.26554</Pose7>
        <Pose8>0.721915</Pose8>
        <Pose9>1.75844</Pose9>
        <Pose10>-1.13583</Pose10>
        <Pose11>-0.942138</Pose11>
        <Pose12>-0.0139637</Pose12>
        <Pose13>0.443438</Pose13>
        <Pose14>0.406819</Pose14>
        <Pose15>-1.40433</Pose15>
        <Pose16>-1.06759</Pose16>
        <Pose17>-0.868655</Pose17>
        <Pose18>0.942</Pose18>
        <Pose19>-0.0139914</Pose19>
        <Pose20>-0.689978</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>6.67572e-06</Pose0>
        <Pose1>-0.0313999</Pose1>
        <Pose2>-4.44005e-06</Pose2>
        <Pose3>3.33786e-05</Pose3>
        <Pose4>-1.256</Pose4>
        <Pose5>-0.534989</Pose5>
        <Pose6>-0.0252018</Pose6>
        <Pose7>0.090404</Pose7>
        <Pose8>0.266937</Pose8>
        <Pose9>-1.13039</Pose9>
        <Pose10>-1.1358</Pose10>
        <Pose11>-2.2608</Pose11>
        <Pose12>0.00801468</Pose12>
        <Pose13>-0.291722</Pose13>
        <Pose14>0.0452064</Pose14>
        <Pose15>-0.411702</Pose15>
        <Pose16>1.256</Pose16>
        <Pose17>-1.36954</Pose17>
        <Pose18>1.7584</Pose18>
        <Pose19>-0.0139813</Pose19>
        <Pose20>0.78402</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction2>
    <newAction3>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-8.73945e-06</Pose0>
        <Pose1>-0.0314002</Pose1>
        <Pose2>-3.58075e-06</Pose2>
        <Pose3>1.28746e-05</Pose3>
        <Pose4>1.2246</Pose4>
        <Pose5>0.169363</Pose5>
        <Pose6>-0.478804</Pose6>
        <Pose7>1.0396</Pose7>
        <Pose8>1.32163</Pose8>
        <Pose9>0.125618</Pose9>
        <Pose10>-1.31951</Pose10>
        <Pose11>-0.0627892</Pose11>
        <Pose12>0.00800896</Pose12>
        <Pose13>-0.0466604</Pose13>
        <Pose14>-2.12438</Pose14>
        <Pose15>-1.363</Pose15>
        <Pose16>-1.19321</Pose16>
        <Pose17>-1.3696</Pose17>
        <Pose18>0.0627363</Pose18>
        <Pose19>-0.0466642</Pose19>
        <Pose20>-0.492011</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction3>
    <newAction4>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-7.86297e-06</Pose0>
        <Pose1>1.00136e-05</Pose1>
        <Pose2>4.76837e-06</Pose2>
        <Pose3>2.43187e-05</Pose3>
        <Pose4>1.85966e-05</Pose4>
        <Pose5>-0.0108063</Pose5>
        <Pose6>3.24249e-05</Pose6>
        <Pose7>-3.33786e-06</Pose7>
        <Pose8>-0.00187731</Pose8>
        <Pose9>-1.19209e-06</Pose9>
        <Pose10>-0.000204325</Pose10>
        <Pose11>2.38419e-06</Pose11>
        <Pose12>-0.0140009</Pose12>
        <Pose13>-0.013993</Pose13>
        <Pose14>3.09944e-06</Pose14>
        <Pose15>-0.0187993</Pose15>
        <Pose16>1.43051e-06</Pose16>
        <Pose17>-0.000198841</Pose17>
        <Pose18>2.14577e-06</Pose18>
        <Pose19>-0.0139799</Pose19>
        <Pose20>-0.0079999</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction4>
</Actions>
