<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-9.09377e-06</Pose0>
        <Pose1>1.43051e-06</Pose1>
        <Pose2>-3.06674e-06</Pose2>
        <Pose3>1.71661e-05</Pose3>
        <Pose4>-1.19318e-05</Pose4>
        <Pose5>-0.0108205</Pose5>
        <Pose6>1.90735e-06</Pose6>
        <Pose7>0.5876</Pose7>
        <Pose8>-0.00188112</Pose8>
        <Pose9>3.45403e-05</Pose9>
        <Pose10>-1.56998</Pose10>
        <Pose11>-4.25412e-05</Pose11>
        <Pose12>-0.0140012</Pose12>
        <Pose13>-0.0139165</Pose13>
        <Pose14>0.587605</Pose14>
        <Pose15>-0.0187993</Pose15>
        <Pose16>-1.32913e-05</Pose16>
        <Pose17>-1.57</Pose17>
        <Pose18>1.95503e-05</Pose18>
        <Pose19>-0.00800207</Pose19>
        <Pose20>-0.0139937</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-3.29245e-06</Pose0>
        <Pose1>-6.10123e-06</Pose1>
        <Pose2>-3.97534e-06</Pose2>
        <Pose3>4.86374e-05</Pose3>
        <Pose4>0.565195</Pose4>
        <Pose5>0.251259</Pose5>
        <Pose6>1.38283e-05</Pose6>
        <Pose7>-0.406778</Pose7>
        <Pose8>-0.0225663</Pose8>
        <Pose9>-0.0627997</Pose9>
        <Pose10>-1.56994</Pose10>
        <Pose11>-1.69561</Pose11>
        <Pose12>-0.0140018</Pose12>
        <Pose13>-0.520446</Pose13>
        <Pose14>2.41995e-05</Pose14>
        <Pose15>-0.039479</Pose15>
        <Pose16>-0.502397</Pose16>
        <Pose17>-1.05232</Pose17>
        <Pose18>8.7738e-05</Pose18>
        <Pose19>-0.013967</Pose19>
        <Pose20>0.388</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-1.76188e-05</Pose0>
        <Pose1>6.19888e-06</Pose1>
        <Pose2>5.05447e-05</Pose2>
        <Pose3>3.57628e-05</Pose3>
        <Pose4>0.565198</Pose4>
        <Pose5>0.267605</Pose5>
        <Pose6>-1.47973e-05</Pose6>
        <Pose7>-0.406696</Pose7>
        <Pose8>-0.00188351</Pose8>
        <Pose9>-3.46005e-05</Pose9>
        <Pose10>-1.5698</Pose10>
        <Pose11>-1.69559</Pose11>
        <Pose12>-0.0139661</Pose12>
        <Pose13>-0.0139515</Pose13>
        <Pose14>0.0001086</Pose14>
        <Pose15>-0.0188062</Pose15>
        <Pose16>-0.439598</Pose16>
        <Pose17>-1.05207</Pose17>
        <Pose18>-0.000145435</Pose18>
        <Pose19>-0.00803328</Pose19>
        <Pose20>-0.0138798</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.75</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction2>
    <newAction3>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>1.90735e-06</Pose0>
        <Pose1>-5.41275e-06</Pose1>
        <Pose2>-7.90464e-06</Pose2>
        <Pose3>-6.67495e-05</Pose3>
        <Pose4>0.565194</Pose4>
        <Pose5>0.267663</Pose5>
        <Pose6>-1.08542e-05</Pose6>
        <Pose7>-0.406734</Pose7>
        <Pose8>-0.00188494</Pose8>
        <Pose9>-4.12762e-05</Pose9>
        <Pose10>-1.56978</Pose10>
        <Pose11>-1.6956</Pose11>
        <Pose12>-0.0139532</Pose12>
        <Pose13>-0.0139015</Pose13>
        <Pose14>7.18832e-05</Pose14>
        <Pose15>-0.0188024</Pose15>
        <Pose16>-0.439612</Pose16>
        <Pose17>-1.0521</Pose17>
        <Pose18>-0.000130653</Pose18>
        <Pose19>-0.0079217</Pose19>
        <Pose20>-0.0138746</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.75</HandPose1>
        <HandPose2>0.9009</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction3>
    <newAction4>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-7.10066e-06</Pose0>
        <Pose1>-1.12224e-05</Pose1>
        <Pose2>1.43051e-05</Pose2>
        <Pose3>-7.41694e-05</Pose3>
        <Pose4>0.565204</Pose4>
        <Pose5>0.267595</Pose5>
        <Pose6>2.38419e-05</Pose6>
        <Pose7>-0.40672</Pose7>
        <Pose8>-0.00188828</Pose8>
        <Pose9>-3.98457e-05</Pose9>
        <Pose10>-1.56972</Pose10>
        <Pose11>-1.69561</Pose11>
        <Pose12>-0.0139155</Pose12>
        <Pose13>-0.0139101</Pose13>
        <Pose14>9.81092e-05</Pose14>
        <Pose15>-0.0188019</Pose15>
        <Pose16>-0.4396</Pose16>
        <Pose17>-1.05211</Pose17>
        <Pose18>-0.000151396</Pose18>
        <Pose19>-0.00799179</Pose19>
        <Pose20>-0.0139027</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.75</HandPose1>
        <HandPose2>0.9009</HandPose2>
        <HandPose3>0.948</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction4>
    <newAction5>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>9.53674e-06</Pose0>
        <Pose1>-8.5562e-06</Pose1>
        <Pose2>1.4782e-05</Pose2>
        <Pose3>3.57628e-05</Pose3>
        <Pose4>0.565197</Pose4>
        <Pose5>0.267631</Pose5>
        <Pose6>1.04904e-05</Pose6>
        <Pose7>-0.406712</Pose7>
        <Pose8>-0.00188541</Pose8>
        <Pose9>-4.41372e-05</Pose9>
        <Pose10>-1.56996</Pose10>
        <Pose11>-1.6956</Pose11>
        <Pose12>-0.0139451</Pose12>
        <Pose13>-0.0139692</Pose13>
        <Pose14>8.66652e-05</Pose14>
        <Pose15>-0.0188048</Pose15>
        <Pose16>-0.4396</Pose16>
        <Pose17>-1.05214</Pose17>
        <Pose18>-0.000171423</Pose18>
        <Pose19>-0.00800276</Pose19>
        <Pose20>-0.0138698</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.75</HandPose1>
        <HandPose2>0.9009</HandPose2>
        <HandPose3>0.948</HandPose3>
        <HandPose4>1.16</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction5>
    <newAction6>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>2.09808e-05</Pose0>
        <Pose1>-1.01753e-05</Pose1>
        <Pose2>2.3365e-05</Pose2>
        <Pose3>-7.65335e-05</Pose3>
        <Pose4>0.565197</Pose4>
        <Pose5>0.267651</Pose5>
        <Pose6>1.66893e-05</Pose6>
        <Pose7>-0.406714</Pose7>
        <Pose8>-0.00188851</Pose8>
        <Pose9>1.28448e-05</Pose9>
        <Pose10>-1.56984</Pose10>
        <Pose11>-1.6956</Pose11>
        <Pose12>-0.0139275</Pose12>
        <Pose13>-0.0139885</Pose13>
        <Pose14>0.000109553</Pose14>
        <Pose15>-0.0188019</Pose15>
        <Pose16>-0.439591</Pose16>
        <Pose17>-1.05217</Pose17>
        <Pose18>-0.000182152</Pose18>
        <Pose19>-0.00799274</Pose19>
        <Pose20>-0.0138035</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction6>
    <newAction7>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>4.29153e-06</Pose0>
        <Pose1>-8.67477e-06</Pose1>
        <Pose2>1.00136e-05</Pose2>
        <Pose3>4.29153e-05</Pose3>
        <Pose4>0.565197</Pose4>
        <Pose5>0.267637</Pose5>
        <Pose6>2.47955e-05</Pose6>
        <Pose7>-0.406689</Pose7>
        <Pose8>-0.00189066</Pose8>
        <Pose9>2.04736e-05</Pose9>
        <Pose10>-1.56985</Pose10>
        <Pose11>-1.6956</Pose11>
        <Pose12>-0.0139048</Pose12>
        <Pose13>-0.0139995</Pose13>
        <Pose14>9.799e-05</Pose14>
        <Pose15>-0.0188065</Pose15>
        <Pose16>-0.4396</Pose16>
        <Pose17>-1.05208</Pose17>
        <Pose18>-0.000169754</Pose18>
        <Pose19>-0.00797966</Pose19>
        <Pose20>-0.0138426</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.8</HandPose1>
        <HandPose2>0.9711</HandPose2>
        <HandPose3>1.032</HandPose3>
        <HandPose4>1.1745</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction7>
    <newAction8>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.013822</Pose0>
        <Pose1>-0.0313999</Pose1>
        <Pose2>-0.0276481</Pose2>
        <Pose3>-8.10864e-05</Pose3>
        <Pose4>-0.251206</Pose4>
        <Pose5>0.284022</Pose5>
        <Pose6>-0.0251995</Pose6>
        <Pose7>-0.361628</Pose7>
        <Pose8>-0.043237</Pose8>
        <Pose9>0.314002</Pose9>
        <Pose10>-0.95212</Pose10>
        <Pose11>-0.1256</Pose11>
        <Pose12>-0.410038</Pose12>
        <Pose13>-0.0139835</Pose13>
        <Pose14>-0.226001</Pose14>
        <Pose15>-0.0187981</Pose15>
        <Pose16>-0.314002</Pose16>
        <Pose17>-1.56998</Pose17>
        <Pose18>1.13039</Pose18>
        <Pose19>0.247476</Pose19>
        <Pose20>-0.0520587</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction8>
    <newAction9>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.0138255</Pose0>
        <Pose1>1.23978e-05</Pose1>
        <Pose2>-0.013778</Pose2>
        <Pose3>2.14577e-05</Pose3>
        <Pose4>-0.219795</Pose4>
        <Pose5>0.284014</Pose5>
        <Pose6>2.09808e-05</Pose6>
        <Pose7>-0.316338</Pose7>
        <Pose8>-0.022562</Pose8>
        <Pose9>0.314014</Pose9>
        <Pose10>-0.95195</Pose10>
        <Pose11>-0.062802</Pose11>
        <Pose12>-0.03601</Pose12>
        <Pose13>-0.0139074</Pose13>
        <Pose14>-0.225915</Pose14>
        <Pose15>-0.0187995</Pose15>
        <Pose16>-0.31402</Pose16>
        <Pose17>-1.56995</Pose17>
        <Pose18>1.19322</Pose18>
        <Pose19>-0.0299425</Pose19>
        <Pose20>-0.0303293</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>1.131</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction9>
    <newAction10>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-0.0138246</Pose0>
        <Pose1>1.04904e-05</Pose1>
        <Pose2>-0.0137784</Pose2>
        <Pose3>2.28882e-05</Pose3>
        <Pose4>-0.219797</Pose4>
        <Pose5>0.284025</Pose5>
        <Pose6>-2.71566e-05</Pose6>
        <Pose7>-0.316344</Pose7>
        <Pose8>-0.022562</Pose8>
        <Pose9>0.313998</Pose9>
        <Pose10>-0.951968</Pose10>
        <Pose11>-0.0627967</Pose11>
        <Pose12>-0.0360448</Pose12>
        <Pose13>-0.0139251</Pose13>
        <Pose14>-0.225958</Pose14>
        <Pose15>-0.0187938</Pose15>
        <Pose16>-0.314022</Pose16>
        <Pose17>-1.56998</Pose17>
        <Pose18>1.19321</Pose18>
        <Pose19>-0.0300164</Pose19>
        <Pose20>-0.0303178</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0.948</HandPose8>
        <HandPose9>1.131</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction10>
    <newAction11>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-0.0138255</Pose0>
        <Pose1>-8.73471e-06</Pose1>
        <Pose2>-0.0138272</Pose2>
        <Pose3>-5.57807e-05</Pose3>
        <Pose4>-0.219799</Pose4>
        <Pose5>0.284</Pose5>
        <Pose6>7.15256e-06</Pose6>
        <Pose7>-0.316362</Pose7>
        <Pose8>-0.0225599</Pose8>
        <Pose9>0.314003</Pose9>
        <Pose10>-0.951961</Pose10>
        <Pose11>-0.0627924</Pose11>
        <Pose12>-0.0359786</Pose12>
        <Pose13>-0.0139036</Pose13>
        <Pose14>-0.225984</Pose14>
        <Pose15>-0.0187976</Pose15>
        <Pose16>-0.314015</Pose16>
        <Pose17>-1.56991</Pose17>
        <Pose18>1.19322</Pose18>
        <Pose19>-0.029974</Pose19>
        <Pose20>-0.0303033</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0.9477</HandPose7>
        <HandPose8>0.948</HandPose8>
        <HandPose9>1.131</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction11>
    <newAction12>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-0.0138183</Pose0>
        <Pose1>8.58307e-06</Pose1>
        <Pose2>-0.0137942</Pose2>
        <Pose3>9.72748e-05</Pose3>
        <Pose4>-0.219805</Pose4>
        <Pose5>0.284023</Pose5>
        <Pose6>-2.43765e-05</Pose6>
        <Pose7>-0.316415</Pose7>
        <Pose8>-0.0225565</Pose8>
        <Pose9>0.314</Pose9>
        <Pose10>-0.952072</Pose10>
        <Pose11>-0.0628017</Pose11>
        <Pose12>-0.0359581</Pose12>
        <Pose13>-0.0139384</Pose13>
        <Pose14>-0.225983</Pose14>
        <Pose15>-0.0188</Pose15>
        <Pose16>-0.314012</Pose16>
        <Pose17>-1.56994</Pose17>
        <Pose18>1.19321</Pose18>
        <Pose19>-0.0299549</Pose19>
        <Pose20>-0.0303417</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.78</HandPose6>
        <HandPose7>0.9477</HandPose7>
        <HandPose8>0.948</HandPose8>
        <HandPose9>1.131</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction12>
    <newAction13>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.0138178</Pose0>
        <Pose1>-2.84553e-06</Pose1>
        <Pose2>-0.0137809</Pose2>
        <Pose3>-1.23504e-05</Pose3>
        <Pose4>-0.219795</Pose4>
        <Pose5>0.283993</Pose5>
        <Pose6>5.14984e-05</Pose6>
        <Pose7>-0.316352</Pose7>
        <Pose8>-0.022562</Pose8>
        <Pose9>0.314004</Pose9>
        <Pose10>-0.95187</Pose10>
        <Pose11>-0.0627893</Pose11>
        <Pose12>-0.035979</Pose12>
        <Pose13>-0.0138967</Pose13>
        <Pose14>-0.225926</Pose14>
        <Pose15>-0.0187967</Pose15>
        <Pose16>-0.314014</Pose16>
        <Pose17>-1.57004</Pose17>
        <Pose18>1.19322</Pose18>
        <Pose19>-0.0299845</Pose19>
        <Pose20>-0.0302913</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction13>
    <newAction14>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0138181</Pose0>
        <Pose1>6.67572e-06</Pose1>
        <Pose2>-0.0137948</Pose2>
        <Pose3>-3.76836e-05</Pose3>
        <Pose4>-0.219797</Pose4>
        <Pose5>0.284012</Pose5>
        <Pose6>2.67029e-05</Pose6>
        <Pose7>-0.316369</Pose7>
        <Pose8>-0.0225627</Pose8>
        <Pose9>0.313999</Pose9>
        <Pose10>-0.952022</Pose10>
        <Pose11>-0.0627922</Pose11>
        <Pose12>-0.0360017</Pose12>
        <Pose13>-0.0139017</Pose13>
        <Pose14>-0.225972</Pose14>
        <Pose15>-0.0188007</Pose15>
        <Pose16>-0.31401</Pose16>
        <Pose17>-1.57004</Pose17>
        <Pose18>1.1932</Pose18>
        <Pose19>-0.0299745</Pose19>
        <Pose20>-0.0302873</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.77</HandPose6>
        <HandPose7>0.9009</HandPose7>
        <HandPose8>0.9</HandPose8>
        <HandPose9>1.102</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction14>
    <newAction15>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.0138175</Pose0>
        <Pose1>7.15256e-06</Pose1>
        <Pose2>-0.0137515</Pose2>
        <Pose3>1.95503e-05</Pose3>
        <Pose4>-0.219802</Pose4>
        <Pose5>0.284043</Pose5>
        <Pose6>7.48634e-05</Pose6>
        <Pose7>-0.316336</Pose7>
        <Pose8>-0.0225642</Pose8>
        <Pose9>0.314007</Pose9>
        <Pose10>-0.951979</Pose10>
        <Pose11>-0.0627881</Pose11>
        <Pose12>-0.0359747</Pose12>
        <Pose13>-0.0139201</Pose13>
        <Pose14>-0.225942</Pose14>
        <Pose15>-0.0188015</Pose15>
        <Pose16>-0.31401</Pose16>
        <Pose17>-1.56991</Pose17>
        <Pose18>1.19322</Pose18>
        <Pose19>-0.0300345</Pose19>
        <Pose20>-0.0303169</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction15>
    <newAction16>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-6.61356e-06</Pose0>
        <Pose1>3.8147e-06</Pose1>
        <Pose2>6.19888e-06</Pose2>
        <Pose3>3.67165e-05</Pose3>
        <Pose4>-3.18688e-05</Pose4>
        <Pose5>-0.0108273</Pose5>
        <Pose6>-2.35934e-05</Pose6>
        <Pose7>0.587585</Pose7>
        <Pose8>-0.00188136</Pose8>
        <Pose9>3.95775e-05</Pose9>
        <Pose10>-1.56994</Pose10>
        <Pose11>2.74181e-06</Pose11>
        <Pose12>-0.014009</Pose12>
        <Pose13>-0.0139141</Pose13>
        <Pose14>0.587577</Pose14>
        <Pose15>-0.0187945</Pose15>
        <Pose16>-2.18749e-05</Pose16>
        <Pose17>-1.57001</Pose17>
        <Pose18>3.6478e-05</Pose18>
        <Pose19>-0.00799611</Pose19>
        <Pose20>-0.0139699</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction16>
    <newAction17>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0138225</Pose0>
        <Pose1>5.24521e-06</Pose1>
        <Pose2>2.67029e-05</Pose2>
        <Pose3>-1.1902e-05</Pose3>
        <Pose4>-0.0314006</Pose4>
        <Pose5>-0.0271919</Pose5>
        <Pose6>-0.0252008</Pose6>
        <Pose7>-1.67238</Pose7>
        <Pose8>1.38368</Pose8>
        <Pose9>-4.24385e-05</Pose9>
        <Pose10>-0.334225</Pose10>
        <Pose11>-1.25601</Pose11>
        <Pose12>-0.0360079</Pose12>
        <Pose13>-0.0139885</Pose13>
        <Pose14>-1.62717</Pose14>
        <Pose15>-1.44572</Pose15>
        <Pose16>-2.563e-06</Pose16>
        <Pose17>-0.33412</Pose17>
        <Pose18>1.256</Pose18>
        <Pose19>-0.00801184</Pose19>
        <Pose20>-0.0139689</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction17>
    <newAction18>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0276355</Pose0>
        <Pose1>-2.43083e-06</Pose1>
        <Pose2>-0.0138179</Pose2>
        <Pose3>1.7643e-05</Pose3>
        <Pose4>-0.0314011</Pose4>
        <Pose5>-0.0435905</Pose5>
        <Pose6>-0.0503997</Pose6>
        <Pose7>-1.7176</Pose7>
        <Pose8>1.363</Pose8>
        <Pose9>-4.79817e-06</Pose9>
        <Pose10>-1.15249</Pose10>
        <Pose11>-1.25599</Pose11>
        <Pose12>-0.0579982</Pose12>
        <Pose13>-0.471505</Pose13>
        <Pose14>-1.6724</Pose14>
        <Pose15>-1.44572</Pose15>
        <Pose16>-0.0627963</Pose16>
        <Pose17>-1.2527</Pose17>
        <Pose18>1.256</Pose18>
        <Pose19>-0.0139747</Pose19>
        <Pose20>0.454004</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.77</HandPose1>
        <HandPose2>0.8307</HandPose2>
        <HandPose3>0.852</HandPose3>
        <HandPose4>1.0295</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.76</HandPose6>
        <HandPose7>0.8775</HandPose7>
        <HandPose8>0.912</HandPose8>
        <HandPose9>1.0875</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction18>
    <newAction19>
        <Time>2</Time>
        <Count>21</Count>
        <Pose0>-0.0138191</Pose0>
        <Pose1>9.53674e-06</Pose1>
        <Pose2>-9.60689e-06</Pose2>
        <Pose3>3.05176e-05</Pose3>
        <Pose4>-1.256</Pose4>
        <Pose5>-0.0272214</Pose5>
        <Pose6>-1.70425e-05</Pose6>
        <Pose7>-1.6724</Pose7>
        <Pose8>1.38368</Pose8>
        <Pose9>2.50041e-05</Pose9>
        <Pose10>-1.15246</Pose10>
        <Pose11>-1.256</Pose11>
        <Pose12>-0.0359793</Pose12>
        <Pose13>-0.0139794</Pose13>
        <Pose14>-1.6272</Pose14>
        <Pose15>-1.44572</Pose15>
        <Pose16>-6.3777e-06</Pose16>
        <Pose17>-1.25266</Pose17>
        <Pose18>1.256</Pose18>
        <Pose19>-0.00800133</Pose19>
        <Pose20>-0.0139904</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.77</HandPose1>
        <HandPose2>0.8307</HandPose2>
        <HandPose3>0.852</HandPose3>
        <HandPose4>1.0295</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.76</HandPose6>
        <HandPose7>0.8775</HandPose7>
        <HandPose8>0.912</HandPose8>
        <HandPose9>1.0875</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction19>
    <newAction20>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0138148</Pose0>
        <Pose1>1.43051e-06</Pose1>
        <Pose2>2.38419e-06</Pose2>
        <Pose3>2.71797e-05</Pose3>
        <Pose4>1.1932</Pose4>
        <Pose5>-0.0272036</Pose5>
        <Pose6>-3.83376e-05</Pose6>
        <Pose7>-1.67239</Pose7>
        <Pose8>1.38368</Pose8>
        <Pose9>2.14577e-06</Pose9>
        <Pose10>-1.15249</Pose10>
        <Pose11>-1.25601</Pose11>
        <Pose12>-0.0359948</Pose12>
        <Pose13>-0.0139804</Pose13>
        <Pose14>-1.6272</Pose14>
        <Pose15>-1.44572</Pose15>
        <Pose16>7.7486e-07</Pose16>
        <Pose17>-1.2527</Pose17>
        <Pose18>1.256</Pose18>
        <Pose19>-0.00799849</Pose19>
        <Pose20>-0.013978</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.77</HandPose1>
        <HandPose2>0.8307</HandPose2>
        <HandPose3>0.852</HandPose3>
        <HandPose4>1.0295</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.76</HandPose6>
        <HandPose7>0.8775</HandPose7>
        <HandPose8>0.912</HandPose8>
        <HandPose9>1.0875</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction20>
    <newAction21>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>5.72205e-06</Pose0>
        <Pose1>-1.31399e-05</Pose1>
        <Pose2>2.71797e-05</Pose2>
        <Pose3>2.71797e-05</Pose3>
        <Pose4>4.72069e-05</Pose4>
        <Pose5>-0.0108159</Pose5>
        <Pose6>-3.23692e-05</Pose6>
        <Pose7>-0.858784</Pose7>
        <Pose8>-0.00188184</Pose8>
        <Pose9>0.0628133</Pose9>
        <Pose10>-1.45298</Pose10>
        <Pose11>-0.000176311</Pose11>
        <Pose12>-0.0139985</Pose12>
        <Pose13>-0.013885</Pose13>
        <Pose14>-0.858765</Pose14>
        <Pose15>-0.0187879</Pose15>
        <Pose16>-0.0627906</Pose16>
        <Pose17>-1.43648</Pose17>
        <Pose18>0.000166893</Pose18>
        <Pose19>-0.00798752</Pose19>
        <Pose20>-0.0139422</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.75</HandPose6>
        <HandPose7>0.8775</HandPose7>
        <HandPose8>0.912</HandPose8>
        <HandPose9>1.0585</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction21>
    <newAction22>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>1.00136e-05</Pose0>
        <Pose1>2.24113e-05</Pose1>
        <Pose2>8.10623e-06</Pose2>
        <Pose3>-0.000126334</Pose3>
        <Pose4>-3.35055e-05</Pose4>
        <Pose5>-0.0108069</Pose5>
        <Pose6>2.47955e-05</Pose6>
        <Pose7>-0.903983</Pose7>
        <Pose8>0.122197</Pose8>
        <Pose9>-0.439601</Pose9>
        <Pose10>-0.71823</Pose10>
        <Pose11>0.565194</Pose11>
        <Pose12>-0.0140055</Pose12>
        <Pose13>-0.0139627</Pose13>
        <Pose14>-0.813573</Pose14>
        <Pose15>-0.0187945</Pose15>
        <Pose16>0.376816</Pose16>
        <Pose17>-1.51994</Pose17>
        <Pose18>-0.690841</Pose18>
        <Pose19>-0.00798562</Pose19>
        <Pose20>-0.013948</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction22>
    <newAction23>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>7.62939e-06</Pose0>
        <Pose1>2.38419e-06</Pose1>
        <Pose2>2.6226e-05</Pose2>
        <Pose3>2.52724e-05</Pose3>
        <Pose4>3.14713e-05</Pose4>
        <Pose5>-0.0108127</Pose5>
        <Pose6>1.90735e-05</Pose6>
        <Pose7>-1.44637</Pose7>
        <Pose8>0.122203</Pose8>
        <Pose9>0.125631</Pose9>
        <Pose10>-1.13573</Pose10>
        <Pose11>1.06765</Pose11>
        <Pose12>-0.0140395</Pose12>
        <Pose13>-0.013978</Pose13>
        <Pose14>-0.271163</Pose14>
        <Pose15>0.0845923</Pose15>
        <Pose16>-0.502412</Pose16>
        <Pose17>-1.51993</Pose17>
        <Pose18>-1.44437</Pose18>
        <Pose19>-0.00799801</Pose19>
        <Pose20>-0.0139871</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction23>
    <newAction24>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-1.50649e-06</Pose0>
        <Pose1>-2.37923e-06</Pose1>
        <Pose2>-0.0138259</Pose2>
        <Pose3>-6.71152e-05</Pose3>
        <Pose4>-0.0314071</Pose4>
        <Pose5>-0.0272004</Pose5>
        <Pose6>-0.0251945</Pose6>
        <Pose7>-6.67572e-06</Pose7>
        <Pose8>-0.0225658</Pose8>
        <Pose9>-2.65241e-06</Pose9>
        <Pose10>-0.0169015</Pose10>
        <Pose11>2.02656e-06</Pose11>
        <Pose12>-0.0140007</Pose12>
        <Pose13>-0.0139825</Pose13>
        <Pose14>-1.13001</Pose14>
        <Pose15>-0.0187972</Pose15>
        <Pose16>-6.59823e-05</Pose16>
        <Pose17>-1.23604</Pose17>
        <Pose18>1.31883</Pose18>
        <Pose19>-0.0139871</Pose19>
        <Pose20>-0.294042</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction24>
    <newAction25>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>8.58307e-06</Pose0>
        <Pose1>7.62939e-06</Pose1>
        <Pose2>-0.0138066</Pose2>
        <Pose3>-2.70259e-05</Pose3>
        <Pose4>-0.0314045</Pose4>
        <Pose5>-0.0272059</Pose5>
        <Pose6>-0.0252187</Pose6>
        <Pose7>3.24249e-05</Pose7>
        <Pose8>-0.0225637</Pose8>
        <Pose9>-1.88649e-05</Pose9>
        <Pose10>-0.0168595</Pose10>
        <Pose11>-4.49419e-05</Pose11>
        <Pose12>-0.0139794</Pose12>
        <Pose13>-0.0139904</Pose13>
        <Pose14>-1.12993</Pose14>
        <Pose15>-0.0187783</Pose15>
        <Pose16>-4.09484e-05</Pose16>
        <Pose17>-1.23566</Pose17>
        <Pose18>1.31879</Pose18>
        <Pose19>-0.0139403</Pose19>
        <Pose20>0.497865</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.4</HandPose6>
        <HandPose7>0.6201</HandPose7>
        <HandPose8>0.6</HandPose8>
        <HandPose9>0.6815</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction25>
    <newAction26>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-1.17967e-05</Pose0>
        <Pose1>-2.66022e-05</Pose1>
        <Pose2>-0.0138104</Pose2>
        <Pose3>-9.00071e-05</Pose3>
        <Pose4>-0.0314188</Pose4>
        <Pose5>-0.0272173</Pose5>
        <Pose6>-0.0252358</Pose6>
        <Pose7>-1.16825e-05</Pose7>
        <Pose8>-0.0225668</Pose8>
        <Pose9>-7.18236e-06</Pose9>
        <Pose10>-0.0168862</Pose10>
        <Pose11>2.11e-05</Pose11>
        <Pose12>-0.0139909</Pose12>
        <Pose13>-0.0139816</Pose13>
        <Pose14>-1.13001</Pose14>
        <Pose15>-0.0187693</Pose15>
        <Pose16>-8.12411e-05</Pose16>
        <Pose17>-1.23587</Pose17>
        <Pose18>1.31877</Pose18>
        <Pose19>-0.0139527</Pose19>
        <Pose20>-0.294062</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction26>
    <newAction27>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>8.10623e-06</Pose0>
        <Pose1>-4.38844e-06</Pose1>
        <Pose2>5.72205e-06</Pose2>
        <Pose3>1.14441e-05</Pose3>
        <Pose4>-4.189e-05</Pose4>
        <Pose5>-4.49181e-05</Pose5>
        <Pose6>1.28746e-05</Pose6>
        <Pose7>-7.86781e-06</Pose7>
        <Pose8>0</Pose8>
        <Pose9>5.21479e-06</Pose9>
        <Pose10>-8.58307e-06</Pose10>
        <Pose11>-8.44726e-06</Pose11>
        <Pose12>0</Pose12>
        <Pose13>9.23872e-07</Pose13>
        <Pose14>4.37327e-06</Pose14>
        <Pose15>-4.76837e-07</Pose15>
        <Pose16>5.06694e-06</Pose16>
        <Pose17>-1.28746e-05</Pose17>
        <Pose18>3.09944e-06</Pose18>
        <Pose19>-4.29153e-06</Pose19>
        <Pose20>1.16788e-06</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction27>
</Actions>
