<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <justright>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0691019</Pose0>
        <Pose1>0.3768</Pose1>
        <Pose2>0.0553188</Pose2>
        <Pose3>-0.0201977</Pose3>
        <Pose4>-0.596599</Pose4>
        <Pose5>0.120228</Pose5>
        <Pose6>0.176396</Pose6>
        <Pose7>-0.903968</Pose7>
        <Pose8>-0.0225551</Pose8>
        <Pose9>0.502395</Pose9>
        <Pose10>-1.46979</Pose10>
        <Pose11>0.0627733</Pose11>
        <Pose12>0.514023</Pose12>
        <Pose13>-0.78196</Pose13>
        <Pose14>-0.632775</Pose14>
        <Pose15>-0.308306</Pose15>
        <Pose16>0.251209</Pose16>
        <Pose17>-1.51989</Pose17>
        <Pose18>-0.376793</Pose18>
        <Pose19>-0.184</Pose19>
        <Pose20>-0.781924</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.62</HandPose1>
        <HandPose2>0.4329</HandPose2>
        <HandPose3>0.192</HandPose3>
        <HandPose4>0.058</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.67</HandPose6>
        <HandPose7>0.2925</HandPose7>
        <HandPose8>0.144</HandPose8>
        <HandPose9>0.029</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </justright>
    <prasiethesun>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.124381</Pose0>
        <Pose1>-0.0313998</Pose1>
        <Pose2>-0.290219</Pose2>
        <Pose3>-0.0201867</Pose3>
        <Pose4>2.24113e-05</Pose4>
        <Pose5>-0.715193</Pose5>
        <Pose6>-0.0755974</Pose6>
        <Pose7>-2.21478</Pose7>
        <Pose8>1.21825</Pose8>
        <Pose9>-0.502434</Pose9>
        <Pose10>-0.000173569</Pose10>
        <Pose11>-0.690875</Pose11>
        <Pose12>-0.0579858</Pose12>
        <Pose13>-0.0303369</Pose13>
        <Pose14>-2.25999</Pose14>
        <Pose15>-1.2596</Pose15>
        <Pose16>0.565215</Pose16>
        <Pose17>-0.0169051</Pose17>
        <Pose18>0.314064</Pose18>
        <Pose19>-0.0520072</Pose19>
        <Pose20>-0.0139797</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </prasiethesun>
    <idk>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.0553074</Pose0>
        <Pose1>-0.0314001</Pose1>
        <Pose2>-0.0137944</Pose2>
        <Pose3>0.404094</Pose3>
        <Pose4>-0.0314077</Pose4>
        <Pose5>-0.0272009</Pose5>
        <Pose6>-3.93716e-05</Pose6>
        <Pose7>-0.226012</Pose7>
        <Pose8>1.15621</Pose8>
        <Pose9>1.94679</Pose9>
        <Pose10>-0.484659</Pose10>
        <Pose11>-0.062764</Pose11>
        <Pose12>-0.0359888</Pose12>
        <Pose13>-0.0305142</Pose13>
        <Pose14>-0.0452046</Pose14>
        <Pose15>-1.79724</Pose15>
        <Pose16>1.44439</Pose16>
        <Pose17>-0.668105</Pose17>
        <Pose18>-0.0628295</Pose18>
        <Pose19>-0.00798586</Pose19>
        <Pose20>-0.0137937</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </idk>
    <idkagain>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.0691037</Pose0>
        <Pose1>-0.0314003</Pose1>
        <Pose2>-0.0138104</Pose2>
        <Pose3>-0.323328</Pose3>
        <Pose4>-0.0314009</Pose4>
        <Pose5>-0.0271561</Pose5>
        <Pose6>4.52995e-05</Pose6>
        <Pose7>-0.225994</Pose7>
        <Pose8>1.40431</Pose8>
        <Pose9>-1.63279</Pose9>
        <Pose10>-0.467517</Pose10>
        <Pose11>-0.0628103</Pose11>
        <Pose12>-0.0139706</Pose12>
        <Pose13>-0.0138845</Pose13>
        <Pose14>-4.57764e-05</Pose14>
        <Pose15>-1.03208</Pose15>
        <Pose16>1.6328</Pose16>
        <Pose17>-0.000191927</Pose17>
        <Pose18>-0.000110865</Pose18>
        <Pose19>-0.00800255</Pose19>
        <Pose20>-0.0138385</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </idkagain>
    <tellsomebody>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.262571</Pose0>
        <Pose1>-0.282599</Pose1>
        <Pose2>0.691077</Pose2>
        <Pose3>-0.343419</Pose3>
        <Pose4>0.0627785</Pose4>
        <Pose5>-0.387533</Pose5>
        <Pose6>0.453539</Pose6>
        <Pose7>-0.723179</Pose7>
        <Pose8>0.618519</Pose8>
        <Pose9>1.6328</Pose9>
        <Pose10>-0.701595</Pose10>
        <Pose11>-0.188402</Pose11>
        <Pose12>-0.0579996</Pose12>
        <Pose13>-0.0466542</Pose13>
        <Pose14>-1.98882</Pose14>
        <Pose15>-0.473734</Pose15>
        <Pose16>0.188403</Pose16>
        <Pose17>-2.55108e-05</Pose17>
        <Pose18>0.314009</Pose18>
        <Pose19>0.123998</Pose19>
        <Pose20>-0.0139287</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0.7605</HandPose7>
        <HandPose8>0.804</HandPose8>
        <HandPose9>0.9425</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </tellsomebody>
    <Zero>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-5.42828e-06</Pose0>
        <Pose1>-1.42492e-06</Pose1>
        <Pose2>-6.9638e-07</Pose2>
        <Pose3>4.29153e-06</Pose3>
        <Pose4>-2.05159e-05</Pose4>
        <Pose5>-0.0108205</Pose5>
        <Pose6>-1.92874e-06</Pose6>
        <Pose7>-7.15256e-07</Pose7>
        <Pose8>-0.00188065</Pose8>
        <Pose9>0</Pose9>
        <Pose10>-0.000196934</Pose10>
        <Pose11>-3.45707e-06</Pose11>
        <Pose12>-0.0139976</Pose12>
        <Pose13>-0.0139809</Pose13>
        <Pose14>9.53674e-07</Pose14>
        <Pose15>-0.0188</Pose15>
        <Pose16>-1.66893e-06</Pose16>
        <Pose17>-0.000201464</Pose17>
        <Pose18>-9.53674e-07</Pose18>
        <Pose19>-0.00800061</Pose19>
        <Pose20>-0.0139782</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </Zero>
</Actions>
