<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <justright>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0690926</Pose0>
        <Pose1>0.3768</Pose1>
        <Pose2>0.055315</Pose2>
        <Pose3>-0.0201962</Pose3>
        <Pose4>-0.596596</Pose4>
        <Pose5>0.120234</Pose5>
        <Pose6>0.176401</Pose6>
        <Pose7>-0.903902</Pose7>
        <Pose8>-0.0225468</Pose8>
        <Pose9>0.502494</Pose9>
        <Pose10>-1.46968</Pose10>
        <Pose11>0.0628292</Pose11>
        <Pose12>0.513995</Pose12>
        <Pose13>-0.781936</Pose13>
        <Pose14>-0.632591</Pose14>
        <Pose15>-0.308261</Pose15>
        <Pose16>0.251199</Pose16>
        <Pose17>-1.51969</Pose17>
        <Pose18>-0.376888</Pose18>
        <Pose19>-0.183961</Pose19>
        <Pose20>-0.781872</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.74</HandPose1>
        <HandPose2>0.5265</HandPose2>
        <HandPose3>0.252</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.78</HandPose6>
        <HandPose7>0.4914</HandPose7>
        <HandPose8>0.24</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </justright>
    <newAction1>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0690922</Pose0>
        <Pose1>0.3768</Pose1>
        <Pose2>0.055316</Pose2>
        <Pose3>-0.0201952</Pose3>
        <Pose4>-0.596598</Pose4>
        <Pose5>0.120234</Pose5>
        <Pose6>0.1764</Pose6>
        <Pose7>-0.183514</Pose7>
        <Pose8>-0.0149434</Pose8>
        <Pose9>0.670066</Pose9>
        <Pose10>-0.057946</Pose10>
        <Pose11>-0.228788</Pose11>
        <Pose12>0.0983107</Pose12>
        <Pose13>-0.0341802</Pose13>
        <Pose14>0.24679</Pose14>
        <Pose15>0.0795665</Pose15>
        <Pose16>0.67341</Pose16>
        <Pose17>-0.122542</Pose17>
        <Pose18>-0.289042</Pose18>
        <Pose19>0.0262952</Pose19>
        <Pose20>-0.291764</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.74</HandPose1>
        <HandPose2>0.5265</HandPose2>
        <HandPose3>0.252</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.78</HandPose6>
        <HandPose7>0.4914</HandPose7>
        <HandPose8>0.24</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0829237</Pose0>
        <Pose1>-0.4082</Pose1>
        <Pose2>0.207304</Pose2>
        <Pose3>-0.343407</Pose3>
        <Pose4>0.282599</Pose4>
        <Pose5>-0.289311</Pose5>
        <Pose6>0.1512</Pose6>
        <Pose7>0.544412</Pose7>
        <Pose8>0.255296</Pose8>
        <Pose9>0.423655</Pose9>
        <Pose10>-0.895269</Pose10>
        <Pose11>-0.588623</Pose11>
        <Pose12>0.38815</Pose12>
        <Pose13>0.0617633</Pose13>
        <Pose14>-0.189045</Pose14>
        <Pose15>0.158541</Pose15>
        <Pose16>0.811902</Pose16>
        <Pose17>-0.0535734</Pose17>
        <Pose18>-0.954763</Pose18>
        <Pose19>0.182148</Pose19>
        <Pose20>0.0266235</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.74</HandPose1>
        <HandPose2>0.5265</HandPose2>
        <HandPose3>0.252</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.78</HandPose6>
        <HandPose7>0.4914</HandPose7>
        <HandPose8>0.24</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction2>
</Actions>
