<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <justright>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0552754</Pose0>
        <Pose1>0.4082</Pose1>
        <Pose2>0.055306</Pose2>
        <Pose3>-0.0201836</Pose3>
        <Pose4>-0.376798</Pose4>
        <Pose5>-0.0272092</Pose5>
        <Pose6>-0.0503965</Pose6>
        <Pose7>-0.903974</Pose7>
        <Pose8>-0.00188279</Pose8>
        <Pose9>0.502406</Pose9>
        <Pose10>-1.46978</Pose10>
        <Pose11>0.125536</Pose11>
        <Pose12>0.536031</Pose12>
        <Pose13>-0.765616</Pose13>
        <Pose14>-0.632763</Pose14>
        <Pose15>-0.308312</Pose15>
        <Pose16>0.314002</Pose16>
        <Pose17>-1.51984</Pose17>
        <Pose18>-0.376765</Pose18>
        <Pose19>-0.183989</Pose19>
        <Pose20>-0.781964</Pose20>
        <Count>10</Count>
        <HandPose0>0.4477</HandPose0>
        <HandPose1>0.62</HandPose1>
        <HandPose2>0.4329</HandPose2>
        <HandPose3>0.192</HandPose3>
        <HandPose4>0.058</HandPose4>
        <HandPose5>0.1331</HandPose5>
        <HandPose6>0.67</HandPose6>
        <HandPose7>0.2925</HandPose7>
        <HandPose8>0.144</HandPose8>
        <HandPose9>0.029</HandPose9>
        <Count>3</Count>
        <OmniVel0>0.5</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </justright>
    <prasiethesun>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.13819</Pose0>
        <Pose1>-0.0313998</Pose1>
        <Pose2>-0.290229</Pose2>
        <Pose3>-2.8258e-05</Pose3>
        <Pose4>-3.01034e-05</Pose4>
        <Pose5>-0.0272048</Pose5>
        <Pose6>-0.0504026</Pose6>
        <Pose7>-2.21477</Pose7>
        <Pose8>1.21825</Pose8>
        <Pose9>-0.502398</Pose9>
        <Pose10>-0.000126123</Pose10>
        <Pose11>-0.690712</Pose11>
        <Pose12>-0.0579427</Pose12>
        <Pose13>-0.0139866</Pose13>
        <Pose14>-2.25998</Pose14>
        <Pose15>-1.2596</Pose15>
        <Pose16>0.628013</Pose16>
        <Pose17>-0.0167756</Pose17>
        <Pose18>0.376758</Pose18>
        <Pose19>-0.0300083</Pose19>
        <Pose20>-0.0139651</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0.5</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </prasiethesun>
    <idk>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.0552821</Pose0>
        <Pose1>-0.0313996</Pose1>
        <Pose2>-0.0138174</Pose2>
        <Pose3>0.404092</Pose3>
        <Pose4>-0.0314069</Pose4>
        <Pose5>-0.027234</Pose5>
        <Pose6>4.673e-05</Pose6>
        <Pose7>-0.226006</Pose7>
        <Pose8>1.1562</Pose8>
        <Pose9>1.94679</Pose9>
        <Pose10>-0.484643</Pose10>
        <Pose11>-0.0627874</Pose11>
        <Pose12>-0.0359762</Pose12>
        <Pose13>-0.0304303</Pose13>
        <Pose14>-0.0451989</Pose14>
        <Pose15>-1.79724</Pose15>
        <Pose16>1.44439</Pose16>
        <Pose17>-0.668106</Pose17>
        <Pose18>-0.0627995</Pose18>
        <Pose19>-0.00798896</Pose19>
        <Pose20>-0.0137835</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>-0.5</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </idk>
    <idkagain>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.0690994</Pose0>
        <Pose1>-0.0314002</Pose1>
        <Pose2>-0.0138165</Pose2>
        <Pose3>-0.323283</Pose3>
        <Pose4>-0.031398</Pose4>
        <Pose5>-0.0271566</Pose5>
        <Pose6>2.81334e-05</Pose6>
        <Pose7>-0.225996</Pose7>
        <Pose8>1.40435</Pose8>
        <Pose9>-1.6328</Pose9>
        <Pose10>-0.467645</Pose10>
        <Pose11>-0.062812</Pose11>
        <Pose12>-0.0139814</Pose12>
        <Pose13>-0.013886</Pose13>
        <Pose14>-3.91006e-05</Pose14>
        <Pose15>-1.03209</Pose15>
        <Pose16>1.6328</Pose16>
        <Pose17>-0.000183582</Pose17>
        <Pose18>-6.27041e-05</Pose18>
        <Pose19>-0.00800279</Pose19>
        <Pose20>-0.0138874</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>-0.5</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </idkagain>
    <tellsomebody>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.262561</Pose0>
        <Pose1>-0.251201</Pose1>
        <Pose2>0.691092</Pose2>
        <Pose3>-0.323197</Pose3>
        <Pose4>0.188406</Pose4>
        <Pose5>-0.191018</Pose5>
        <Pose6>0.176366</Pose6>
        <Pose7>-0.678057</Pose7>
        <Pose8>0.618522</Pose8>
        <Pose9>1.63283</Pose9>
        <Pose10>-0.684911</Pose10>
        <Pose11>-0.125654</Pose11>
        <Pose12>-0.0359948</Pose12>
        <Pose13>-0.0303288</Pose13>
        <Pose14>-1.94363</Pose14>
        <Pose15>-0.473752</Pose15>
        <Pose16>0.251199</Pose16>
        <Pose17>-8.89301e-05</Pose17>
        <Pose18>0.37679</Pose18>
        <Pose19>0.124007</Pose19>
        <Pose20>-0.0138867</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0.7605</HandPose7>
        <HandPose8>0.804</HandPose8>
        <HandPose9>0.9425</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>1</OmniVel2>
    </tellsomebody>
    <getyomuny>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.262582</Pose0>
        <Pose1>-0.251202</Pose1>
        <Pose2>0.691156</Pose2>
        <Pose3>-0.323205</Pose3>
        <Pose4>0.188433</Pose4>
        <Pose5>-0.191148</Pose5>
        <Pose6>0.176358</Pose6>
        <Pose7>-0.678073</Pose7>
        <Pose8>0.618518</Pose8>
        <Pose9>1.63282</Pose9>
        <Pose10>-0.684902</Pose10>
        <Pose11>-0.125575</Pose11>
        <Pose12>-0.0360169</Pose12>
        <Pose13>-0.0303264</Pose13>
        <Pose14>-1.94361</Pose14>
        <Pose15>-0.473736</Pose15>
        <Pose16>0.251192</Pose16>
        <Pose17>-0.000113726</Pose17>
        <Pose18>0.376813</Pose18>
        <Pose19>0.124019</Pose19>
        <Pose20>-0.0138299</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0.7605</HandPose7>
        <HandPose8>0.804</HandPose8>
        <HandPose9>0.9425</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </getyomuny>
    <Zero>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-5.42828e-06</Pose0>
        <Pose1>-1.42492e-06</Pose1>
        <Pose2>-6.9638e-07</Pose2>
        <Pose3>4.29153e-06</Pose3>
        <Pose4>-2.05159e-05</Pose4>
        <Pose5>-0.0108205</Pose5>
        <Pose6>-1.92874e-06</Pose6>
        <Pose7>-7.15256e-07</Pose7>
        <Pose8>-0.00188065</Pose8>
        <Pose9>0</Pose9>
        <Pose10>-0.000196934</Pose10>
        <Pose11>-3.45707e-06</Pose11>
        <Pose12>-0.0139976</Pose12>
        <Pose13>-0.0139809</Pose13>
        <Pose14>9.53674e-07</Pose14>
        <Pose15>-0.0188</Pose15>
        <Pose16>-1.66893e-06</Pose16>
        <Pose17>-0.000201464</Pose17>
        <Pose18>-9.53674e-07</Pose18>
        <Pose19>-0.00800061</Pose19>
        <Pose20>-0.0139782</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </Zero>
</Actions>
