<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <justright>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.0690926</Pose0>
        <Pose1>0.3768</Pose1>
        <Pose2>0.055315</Pose2>
        <Pose3>-0.0201962</Pose3>
        <Pose4>-0.596596</Pose4>
        <Pose5>0.120234</Pose5>
        <Pose6>0.176401</Pose6>
        <Pose7>-0.903902</Pose7>
        <Pose8>-0.0225468</Pose8>
        <Pose9>0.502494</Pose9>
        <Pose10>-1.46968</Pose10>
        <Pose11>0.0628292</Pose11>
        <Pose12>0.513995</Pose12>
        <Pose13>-0.781936</Pose13>
        <Pose14>-0.632591</Pose14>
        <Pose15>-0.308261</Pose15>
        <Pose16>0.251199</Pose16>
        <Pose17>-1.51969</Pose17>
        <Pose18>-0.376888</Pose18>
        <Pose19>-0.183961</Pose19>
        <Pose20>-0.781872</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.74</HandPose1>
        <HandPose2>0.5265</HandPose2>
        <HandPose3>0.252</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0.78</HandPose6>
        <HandPose7>0.4914</HandPose7>
        <HandPose8>0.24</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </justright>
    <prasiethesun>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.124378</Pose0>
        <Pose1>-0.0314001</Pose1>
        <Pose2>-0.290219</Pose2>
        <Pose3>-0.0201889</Pose3>
        <Pose4>-6.14919e-05</Pose4>
        <Pose5>-0.715176</Pose5>
        <Pose6>-0.0755981</Pose6>
        <Pose7>-2.21475</Pose7>
        <Pose8>1.21826</Pose8>
        <Pose9>-0.502494</Pose9>
        <Pose10>-0.000117302</Pose10>
        <Pose11>-0.691097</Pose11>
        <Pose12>-0.0578955</Pose12>
        <Pose13>-0.0303426</Pose13>
        <Pose14>-2.25996</Pose14>
        <Pose15>-1.2596</Pose15>
        <Pose16>0.565224</Pose16>
        <Pose17>-0.0168951</Pose17>
        <Pose18>0.313969</Pose18>
        <Pose19>-0.0520079</Pose19>
        <Pose20>-0.0139766</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0.8892</HandPose2>
        <HandPose3>0.84</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0.1694</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>1.0062</HandPose7>
        <HandPose8>0.912</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </prasiethesun>
    <idk>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.0553098</Pose0>
        <Pose1>-0.0314001</Pose1>
        <Pose2>-0.0137933</Pose2>
        <Pose3>0.404089</Pose3>
        <Pose4>-0.0314083</Pose4>
        <Pose5>-0.0272197</Pose5>
        <Pose6>-5.54408e-05</Pose6>
        <Pose7>-0.22602</Pose7>
        <Pose8>1.1562</Pose8>
        <Pose9>1.94678</Pose9>
        <Pose10>-0.484656</Pose10>
        <Pose11>-0.0628003</Pose11>
        <Pose12>-0.0359655</Pose12>
        <Pose13>-0.0305505</Pose13>
        <Pose14>-0.0452201</Pose14>
        <Pose15>-1.79721</Pose15>
        <Pose16>1.44439</Pose16>
        <Pose17>-0.668035</Pose17>
        <Pose18>-0.06285</Pose18>
        <Pose19>-0.00797155</Pose19>
        <Pose20>-0.0136766</Pose20>
        <Count>10</Count>
        <HandPose0>0.5203</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0.924</HandPose3>
        <HandPose4>0.9715</HandPose4>
        <HandPose5>0.7865</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0.783</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </idk>
    <idkagain>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>0.0691066</Pose0>
        <Pose1>-0.0314002</Pose1>
        <Pose2>-0.0138088</Pose2>
        <Pose3>-0.323364</Pose3>
        <Pose4>-0.0313967</Pose4>
        <Pose5>-0.0271564</Pose5>
        <Pose6>2.52724e-05</Pose6>
        <Pose7>-0.22599</Pose7>
        <Pose8>1.40424</Pose8>
        <Pose9>-1.63281</Pose9>
        <Pose10>-0.467348</Pose10>
        <Pose11>-0.0628089</Pose11>
        <Pose12>-0.0139845</Pose12>
        <Pose13>-0.0138812</Pose13>
        <Pose14>-5.24521e-05</Pose14>
        <Pose15>-1.03205</Pose15>
        <Pose16>1.6328</Pose16>
        <Pose17>-0.000204802</Pose17>
        <Pose18>-0.00020504</Pose18>
        <Pose19>-0.00800374</Pose19>
        <Pose20>-0.0138364</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0.468</HandPose2>
        <HandPose3>0.984</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0.8107</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0.744</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </idkagain>
    <tellsomebody>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-0.262601</Pose0>
        <Pose1>-0.282598</Pose1>
        <Pose2>0.691156</Pose2>
        <Pose3>-0.343422</Pose3>
        <Pose4>0.0628023</Pose4>
        <Pose5>-0.387298</Pose5>
        <Pose6>0.453541</Pose6>
        <Pose7>-0.72305</Pose7>
        <Pose8>0.618526</Pose8>
        <Pose9>1.63283</Pose9>
        <Pose10>-0.70161</Pose10>
        <Pose11>-0.188368</Pose11>
        <Pose12>-0.0580051</Pose12>
        <Pose13>-0.0466332</Pose13>
        <Pose14>-1.98874</Pose14>
        <Pose15>-0.473671</Pose15>
        <Pose16>0.188389</Pose16>
        <Pose17>-7.22408e-05</Pose17>
        <Pose18>0.314051</Pose18>
        <Pose19>0.123994</Pose19>
        <Pose20>-0.0138726</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0.33</HandPose1>
        <HandPose2>0.1872</HandPose2>
        <HandPose3>0.54</HandPose3>
        <HandPose4>1.189</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0.9009</HandPose7>
        <HandPose8>0.924</HandPose8>
        <HandPose9>1.131</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </tellsomebody>
    <Zero>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>-5.42828e-06</Pose0>
        <Pose1>-1.42492e-06</Pose1>
        <Pose2>-6.9638e-07</Pose2>
        <Pose3>4.29153e-06</Pose3>
        <Pose4>-2.05159e-05</Pose4>
        <Pose5>-0.0108205</Pose5>
        <Pose6>-1.92874e-06</Pose6>
        <Pose7>-7.15256e-07</Pose7>
        <Pose8>-0.00188065</Pose8>
        <Pose9>0</Pose9>
        <Pose10>-0.000196934</Pose10>
        <Pose11>-3.45707e-06</Pose11>
        <Pose12>-0.0139976</Pose12>
        <Pose13>-0.0139809</Pose13>
        <Pose14>9.53674e-07</Pose14>
        <Pose15>-0.0188</Pose15>
        <Pose16>-1.66893e-06</Pose16>
        <Pose17>-0.000201464</Pose17>
        <Pose18>-9.53674e-07</Pose18>
        <Pose19>-0.00800061</Pose19>
        <Pose20>-0.0139782</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </Zero>
</Actions>
