<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <rise_up_gesture>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>5.24521e-06</Pose0>
        <Pose1>7.15256e-06</Pose1>
        <Pose2>1.14441e-05</Pose2>
        <Pose3>-3.44704e-05</Pose3>
        <Pose4>2.76566e-05</Pose4>
        <Pose5>-0.0108054</Pose5>
        <Pose6>-7.51007e-06</Pose6>
        <Pose7>-0.723178</Pose7>
        <Pose8>0.287621</Pose8>
        <Pose9>-1.50724</Pose9>
        <Pose10>-1.51983</Pose10>
        <Pose11>-1.44452</Pose11>
        <Pose12>-0.0139001</Pose12>
        <Pose13>-0.0140419</Pose13>
        <Pose14>-3.95114e-07</Pose14>
        <Pose15>-0.018805</Pose15>
        <Pose16>-4.23138e-06</Pose16>
        <Pose17>-0.000198364</Pose17>
        <Pose18>-1.38283e-05</Pose18>
        <Pose19>-0.0080035</Pose19>
        <Pose20>-0.0139828</Pose20>
        <Count>10</Count>
        <HandPose0>0.4477</HandPose0>
        <HandPose1>0.62</HandPose1>
        <HandPose2>0.3276</HandPose2>
        <HandPose3>0.18</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </rise_up_gesture>
    <rise_up_arm>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>2.86102e-06</Pose0>
        <Pose1>-6.63758e-06</Pose1>
        <Pose2>-3.93131e-06</Pose2>
        <Pose3>6.7234e-05</Pose3>
        <Pose4>-4.85019e-06</Pose4>
        <Pose5>-0.0108212</Pose5>
        <Pose6>-1.22874e-05</Pose6>
        <Pose7>-2.2148</Pose7>
        <Pose8>0.65988</Pose8>
        <Pose9>-0.502393</Pose9>
        <Pose10>-0.000125647</Pose10>
        <Pose11>-6.13928e-05</Pose11>
        <Pose12>-0.0139988</Pose12>
        <Pose13>-0.0139842</Pose13>
        <Pose14>-3.97116e-06</Pose14>
        <Pose15>-0.0187964</Pose15>
        <Pose16>-1.78814e-07</Pose16>
        <Pose17>-0.000191689</Pose17>
        <Pose18>-2.14577e-06</Pose18>
        <Pose19>-0.00800016</Pose19>
        <Pose20>-0.0139751</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </rise_up_arm>
    <chop>
        <Time>3</Time>
        <Count>21</Count>
        <Pose0>2.86102e-06</Pose0>
        <Pose1>-3.98647e-07</Pose1>
        <Pose2>-6.47472e-07</Pose2>
        <Pose3>-4.26624e-06</Pose3>
        <Pose4>-1.20583e-06</Pose4>
        <Pose5>-0.0108201</Pose5>
        <Pose6>2.38419e-06</Pose6>
        <Pose7>0.180801</Pose7>
        <Pose8>0.0601559</Pose8>
        <Pose9>3.33786e-06</Pose9>
        <Pose10>-0.417685</Pose10>
        <Pose11>-2.98023e-06</Pose11>
        <Pose12>-0.0139985</Pose12>
        <Pose13>-0.0139775</Pose13>
        <Pose14>3.20375e-07</Pose14>
        <Pose15>-0.0187998</Pose15>
        <Pose16>5.96046e-08</Pose16>
        <Pose17>-0.000201225</Pose17>
        <Pose18>2.38419e-07</Pose18>
        <Pose19>-0.00799825</Pose19>
        <Pose20>-0.0139799</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </chop>
</Actions>
