<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Actions>
    <newAction0>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>4.29153e-06</Pose0>
        <Pose1>4.29153e-06</Pose1>
        <Pose2>-4.83432e-06</Pose2>
        <Pose3>2.0504e-05</Pose3>
        <Pose4>-1.1618</Pose4>
        <Pose5>-0.0108088</Pose5>
        <Pose6>2.67029e-05</Pose6>
        <Pose7>6.4373e-06</Pose7>
        <Pose8>-0.00188684</Pose8>
        <Pose9>-3.04135e-08</Pose9>
        <Pose10>-0.000194073</Pose10>
        <Pose11>1.11031e-05</Pose11>
        <Pose12>-0.0139985</Pose12>
        <Pose13>-0.0139778</Pose13>
        <Pose14>-1.16008e-05</Pose14>
        <Pose15>-0.0187936</Pose15>
        <Pose16>-8.93517e-07</Pose16>
        <Pose17>-0.000200272</Pose17>
        <Pose18>-8.10623e-06</Pose18>
        <Pose19>-0.0139785</Pose19>
        <Pose20>-0.00800445</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction0>
    <newAction1>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>1.90735e-06</Pose0>
        <Pose1>2.86102e-06</Pose1>
        <Pose2>-8.05071e-06</Pose2>
        <Pose3>-4.35853e-06</Pose3>
        <Pose4>1.1618</Pose4>
        <Pose5>-0.0108345</Pose5>
        <Pose6>-1.70945e-05</Pose6>
        <Pose7>-1.33514e-05</Pose7>
        <Pose8>-0.00188255</Pose8>
        <Pose9>-3.04135e-08</Pose9>
        <Pose10>-0.000202179</Pose10>
        <Pose11>1.56631e-06</Pose11>
        <Pose12>-0.0139995</Pose12>
        <Pose13>-0.0139878</Pose13>
        <Pose14>8.66479e-06</Pose14>
        <Pose15>-0.0187993</Pose15>
        <Pose16>-1.60877e-06</Pose16>
        <Pose17>-0.000200748</Pose17>
        <Pose18>-5.00679e-06</Pose18>
        <Pose19>-0.013979</Pose19>
        <Pose20>-0.00800064</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction1>
    <newAction2>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-2.21446e-06</Pose0>
        <Pose1>1.43051e-06</Pose1>
        <Pose2>-1.21016e-05</Pose2>
        <Pose3>1.43051e-06</Pose3>
        <Pose4>-3.36042e-05</Pose4>
        <Pose5>-0.534978</Pose5>
        <Pose6>-8.15137e-06</Pose6>
        <Pose7>-3.09944e-06</Pose7>
        <Pose8>-0.00188136</Pose8>
        <Pose9>3.30745e-06</Pose9>
        <Pose10>-0.000204086</Pose10>
        <Pose11>4.42733e-06</Pose11>
        <Pose12>-0.0140028</Pose12>
        <Pose13>-0.0139797</Pose13>
        <Pose14>-3.01772e-06</Pose14>
        <Pose15>-0.0187926</Pose15>
        <Pose16>1.25225e-06</Pose16>
        <Pose17>-0.000203133</Pose17>
        <Pose18>-7.15256e-06</Pose18>
        <Pose19>-0.013978</Pose19>
        <Pose20>-0.00799301</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction2>
    <newAction3>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>-4.83618e-06</Pose0>
        <Pose1>-2.19603e-06</Pose1>
        <Pose2>7.15256e-06</Pose2>
        <Pose3>-1.32441e-05</Pose3>
        <Pose4>1.00136e-05</Pose4>
        <Pose5>0.152978</Pose5>
        <Pose6>-3.3789e-05</Pose6>
        <Pose7>-2.38419e-07</Pose7>
        <Pose8>-0.00188279</Pose8>
        <Pose9>-1.93776e-06</Pose9>
        <Pose10>-0.000205517</Pose10>
        <Pose11>1.35798e-07</Pose11>
        <Pose12>-0.013999</Pose12>
        <Pose13>-0.013978</Pose13>
        <Pose14>-5.4019e-06</Pose14>
        <Pose15>-0.0187941</Pose15>
        <Pose16>1.19811e-05</Pose16>
        <Pose17>-0.000202179</Pose17>
        <Pose18>-2.38419e-06</Pose18>
        <Pose19>-0.0139799</Pose19>
        <Pose20>-0.00799444</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction3>
    <newAction4>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>5.24521e-06</Pose0>
        <Pose1>-2.88625e-06</Pose1>
        <Pose2>-1.01961e-05</Pose2>
        <Pose3>-1.43721e-05</Pose3>
        <Pose4>4.95911e-05</Pose4>
        <Pose5>-0.0108196</Pose5>
        <Pose6>-0.529208</Pose6>
        <Pose7>-3.57628e-06</Pose7>
        <Pose8>-0.0018816</Pose8>
        <Pose9>4.46424e-07</Pose9>
        <Pose10>-0.000197411</Pose10>
        <Pose11>-6.3015e-06</Pose11>
        <Pose12>-0.0140004</Pose12>
        <Pose13>-0.0139785</Pose13>
        <Pose14>7.96994e-07</Pose14>
        <Pose15>-0.0187917</Pose15>
        <Pose16>-3.03928e-06</Pose16>
        <Pose17>-0.000196934</Pose17>
        <Pose18>1.95503e-05</Pose18>
        <Pose19>-0.0139804</Pose19>
        <Pose20>-0.00799921</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction4>
    <newAction5>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>5.24521e-06</Pose0>
        <Pose1>2.38419e-06</Pose1>
        <Pose2>-2.17577e-06</Pose2>
        <Pose3>-2.09217e-06</Pose3>
        <Pose4>-5.65697e-06</Pose4>
        <Pose5>-0.0108269</Pose5>
        <Pose6>0.529208</Pose6>
        <Pose7>1.90735e-06</Pose7>
        <Pose8>-0.00187945</Pose8>
        <Pose9>-3.04135e-08</Pose9>
        <Pose10>-0.000199795</Pose10>
        <Pose11>-4.39415e-06</Pose11>
        <Pose12>-0.0139999</Pose12>
        <Pose13>-0.0139814</Pose13>
        <Pose14>-1.58719e-06</Pose14>
        <Pose15>-0.0188003</Pose15>
        <Pose16>4.11327e-06</Pose16>
        <Pose17>-0.000200748</Pose17>
        <Pose18>-2.45571e-05</Pose18>
        <Pose19>-0.0139794</Pose19>
        <Pose20>-0.00800254</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction5>
    <newAction6>
        <Time>1</Time>
        <Count>21</Count>
        <Pose0>4.29153e-06</Pose0>
        <Pose1>4.76837e-06</Pose1>
        <Pose2>-4.99578e-07</Pose2>
        <Pose3>-1.16757e-05</Pose3>
        <Pose4>-2.23868e-05</Pose4>
        <Pose5>-0.0108108</Pose5>
        <Pose6>9.53674e-07</Pose6>
        <Pose7>-8.82149e-06</Pose7>
        <Pose8>-0.00187922</Pose8>
        <Pose9>2.08005e-07</Pose9>
        <Pose10>-0.000200272</Pose10>
        <Pose11>-1.17851e-05</Pose11>
        <Pose12>-0.0140028</Pose12>
        <Pose13>-0.0139807</Pose13>
        <Pose14>-3.0177e-06</Pose14>
        <Pose15>-0.0187998</Pose15>
        <Pose16>7.92797e-06</Pose16>
        <Pose17>-0.000207424</Pose17>
        <Pose18>-2.5034e-05</Pose18>
        <Pose19>-0.0139828</Pose19>
        <Pose20>-0.00799348</Pose20>
        <Count>10</Count>
        <HandPose0>0</HandPose0>
        <HandPose1>0</HandPose1>
        <HandPose2>0</HandPose2>
        <HandPose3>0</HandPose3>
        <HandPose4>0</HandPose4>
        <HandPose5>0</HandPose5>
        <HandPose6>0</HandPose6>
        <HandPose7>0</HandPose7>
        <HandPose8>0</HandPose8>
        <HandPose9>0</HandPose9>
        <Count>3</Count>
        <OmniVel0>0</OmniVel0>
        <OmniVel1>0</OmniVel1>
        <OmniVel2>0</OmniVel2>
    </newAction6>
</Actions>
